<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\CaCertificate;
use Axiam\Sdk\Management\Models\CreateCaCertificateRequest;
use Axiam\Sdk\Management\Models\CreateIntermediateCaRequest;
use Axiam\Sdk\Management\Models\GeneratedCaCertificate;
use Axiam\Sdk\Management\Models\ImportCaCertificateRequest;
use Axiam\Sdk\Management\Models\MigrateCustodyResponse;
use Axiam\Sdk\Management\Models\MtlsTrustAnchorResponse;
use Axiam\Sdk\Management\Models\SetMtlsTrustAnchor;
use Axiam\Sdk\Management\Models\SignIntermediateCsrRequest;

/**
 * Organization CAs and the per-tenant signing CAs chained beneath them.
 *
 * The `ca_certificates` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->caCertificates()`. Every method here goes through the one shared
 * {@see ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16
 * retry and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class CaCertificatesApi extends ManagementSupport
{
    /**
     * `GET /api/v1/organizations/{org_id}/ca-certificates`
     *
     * `GET /api/v1/organizations/{org_id}/ca-certificates`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<CaCertificate>
     */
    public function listItems(
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'ca_certificates.list',
            '/api/v1/organizations/{org_id}/ca-certificates',
            ['org_id' => $this->orgId()],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): CaCertificate => CaCertificate::fromArray($item),
        );
    }

    /**
     * `POST /api/v1/organizations/{org_id}/ca-certificates`
     *
     * `POST /api/v1/organizations/{org_id}/ca-certificates`.
     *
     * The response carries a ONE-TIME secret (`private_key_pem`): the server will not return
     * it again, so a caller that does not persist it here cannot recover it (§27.5).
     * @param CreateCaCertificateRequest $body the request body
     * @return GeneratedCaCertificate
     */
    public function generate(
        CreateCaCertificateRequest $body,
    ): GeneratedCaCertificate {
        $decoded = $this->transport->send(
            'ca_certificates.generate',
            'POST',
            '/api/v1/organizations/{org_id}/ca-certificates',
            ['org_id' => $this->orgId()],
            [],
            $body->toArray(),
        );

        return GeneratedCaCertificate::fromArray($decoded ?? []);
    }

    /**
     * `POST /api/v1/organizations/{org_id}/ca-certificates/import`
     *
     * `POST /api/v1/organizations/{org_id}/ca-certificates/import`.
     * @param ImportCaCertificateRequest $body the request body
     * @return CaCertificate
     */
    public function importCa(
        ImportCaCertificateRequest $body,
    ): CaCertificate {
        $decoded = $this->transport->send(
            'ca_certificates.import_ca',
            'POST',
            '/api/v1/organizations/{org_id}/ca-certificates/import',
            ['org_id' => $this->orgId()],
            [],
            $body->toArray(),
        );

        return CaCertificate::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/organizations/{org_id}/ca-certificates/{id}`
     *
     * `GET /api/v1/organizations/{org_id}/ca-certificates/{id}`.
     * @param string $id the `{id}` path parameter
     * @return CaCertificate
     */
    public function get(
        string $id,
    ): CaCertificate {
        $decoded = $this->transport->send(
            'ca_certificates.get',
            'GET',
            '/api/v1/organizations/{org_id}/ca-certificates/{id}',
            ['org_id' => $this->orgId(), 'id' => $id],
            [],
            null,
        );

        return CaCertificate::fromArray($decoded ?? []);
    }

    /**
     * `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke`
     *
     * `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $id the `{id}` path parameter
     */
    public function revoke(
        string $id,
    ): void {
        $this->transport->send(
            'ca_certificates.revoke',
            'POST',
            '/api/v1/organizations/{org_id}/ca-certificates/{id}/revoke',
            ['org_id' => $this->orgId(), 'id' => $id],
            [],
            null,
        );
    }

    /**
     * `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody`
     *
     * `POST /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody`.
     * @param string $id the `{id}` path parameter
     * @return MigrateCustodyResponse
     */
    public function migrateCustody(
        string $id,
    ): MigrateCustodyResponse {
        $decoded = $this->transport->send(
            'ca_certificates.migrate_custody',
            'POST',
            '/api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody',
            ['org_id' => $this->orgId(), 'id' => $id],
            [],
            null,
        );

        return MigrateCustodyResponse::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor`
     *
     * `PUT /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor`.
     * @param string $id the `{id}` path parameter
     * @param SetMtlsTrustAnchor $body the request body
     * @return MtlsTrustAnchorResponse
     */
    public function setMtlsTrustAnchor(
        string $id,
        SetMtlsTrustAnchor $body,
    ): MtlsTrustAnchorResponse {
        $decoded = $this->transport->send(
            'ca_certificates.set_mtls_trust_anchor',
            'PUT',
            '/api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor',
            ['org_id' => $this->orgId(), 'id' => $id],
            [],
            $body->toArray(),
        );

        return MtlsTrustAnchorResponse::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`
     *
     * `GET /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param string $tenantId the `{tenant_id}` path parameter
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<CaCertificate>
     */
    public function listSigningCas(
        string $tenantId,
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'ca_certificates.list_signing_cas',
            '/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas',
            ['org_id' => $this->orgId(), 'tenant_id' => $tenantId],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): CaCertificate => CaCertificate::fromArray($item),
        );
    }

    /**
     * `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`
     *
     * `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas`.
     *
     * The response carries a ONE-TIME secret (`private_key_pem`): the server will not return
     * it again, so a caller that does not persist it here cannot recover it (§27.5).
     * @param string $tenantId the `{tenant_id}` path parameter
     * @param CreateIntermediateCaRequest $body the request body
     * @return GeneratedCaCertificate
     */
    public function generateSigningCa(
        string $tenantId,
        CreateIntermediateCaRequest $body,
    ): GeneratedCaCertificate {
        $decoded = $this->transport->send(
            'ca_certificates.generate_signing_ca',
            'POST',
            '/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas',
            ['org_id' => $this->orgId(), 'tenant_id' => $tenantId],
            [],
            $body->toArray(),
        );

        return GeneratedCaCertificate::fromArray($decoded ?? []);
    }

    /**
     * `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr`
     *
     * `POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr`.
     * @param string $tenantId the `{tenant_id}` path parameter
     * @param SignIntermediateCsrRequest $body the request body
     * @return CaCertificate
     */
    public function signSigningCaCsr(
        string $tenantId,
        SignIntermediateCsrRequest $body,
    ): CaCertificate {
        $decoded = $this->transport->send(
            'ca_certificates.sign_signing_ca_csr',
            'POST',
            '/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr',
            ['org_id' => $this->orgId(), 'tenant_id' => $tenantId],
            [],
            $body->toArray(),
        );

        return CaCertificate::fromArray($decoded ?? []);
    }
}
