<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\DirectoryConfig;
use Axiam\Sdk\Management\Models\DirectoryLinkResult;
use Axiam\Sdk\Management\Models\DirectorySyncStatus;
use Axiam\Sdk\Management\Models\LinkDirectoryAccount;
use Axiam\Sdk\Management\Models\SetDirectoryConfig;
use Axiam\Sdk\Management\Models\UpdateDirectoryConfig;

/**
 * A tenant's LDAP / Active Directory identity source (CONTRACT §30): the one configuration,
 * the explicit act that links an existing local account to its directory entry, and a
 * read-only view of the sync job. Signing in needs nothing new -- a directory account calls
 * the same §1 `login`.
 *
 * The `directory` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->directory()`. Every method here goes through the one shared {@see
 * ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16 retry
 * and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class DirectoryApi extends ManagementSupport
{
    /**
     * `GET /api/v1/tenants/{tenant_id}/directory`
     *
     * `GET /api/v1/tenants/{tenant_id}/directory`.
     * @return DirectoryConfig
     */
    public function get(): DirectoryConfig
    {
        $decoded = $this->transport->send(
            'directory.get',
            'GET',
            '/api/v1/tenants/{tenant_id}/directory',
            ['tenant_id' => $this->tenantId()],
            [],
            null,
        );

        return DirectoryConfig::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/tenants/{tenant_id}/directory` — create or **replace**.
     *
     * `PUT /api/v1/tenants/{tenant_id}/directory`.
     *
     * **Moving the connection requires the secret again** (§30.3 rule 2): a `set` that changes
     * `url`, `start_tls`, `bind_dn` or `trust_anchors_pem` without `bindSecret` is refused
     * `400` and changes nothing. The SDK holds no copy of the secret and cannot re-send one
     * for you. `bindSecret` is required while the tenant has no configuration; otherwise
     * absent keeps the stored secret. Every other optional member left out is **reset to its
     * default** -- start from {@see \Axiam\Sdk\Management\ReadModifyWrite::directoryConfig()}.
     * An enabled directory and an effective `opaque_mode = required` never coexist (`409`);
     * without the deployment's directory key a write carrying a secret is `503`.
     * @param SetDirectoryConfig $body the request body
     * @return DirectoryConfig
     */
    public function set(
        SetDirectoryConfig $body,
    ): DirectoryConfig {
        $decoded = $this->transport->send(
            'directory.set',
            'PUT',
            '/api/v1/tenants/{tenant_id}/directory',
            ['tenant_id' => $this->tenantId()],
            [],
            $body->toArray(),
        );

        return DirectoryConfig::fromArray($decoded ?? []);
    }

    /**
     * `PATCH /api/v1/tenants/{tenant_id}/directory` — a **sparse** update.
     *
     * `PATCH /api/v1/tenants/{tenant_id}/directory`.
     *
     * **Moving the connection requires the secret again** (§30.3 rule 2): an `update` that
     * changes `url`, `start_tls`, `bind_dn` or `trust_anchors_pem` without `bindSecret` is
     * refused `400` and changes nothing; the SDK holds no copy of the secret to re-send. A
     * member left `null` is not sent and stays as stored; `groupBaseDn` / `groupFilter` set to
     * {@see \Axiam\Sdk\Management\JsonNull::Null} are sent as `null` and clear the value. An
     * enabled directory and an effective `opaque_mode = required` never coexist (`409`).
     * @param UpdateDirectoryConfig $body the request body
     * @return DirectoryConfig
     */
    public function update(
        UpdateDirectoryConfig $body,
    ): DirectoryConfig {
        $decoded = $this->transport->send(
            'directory.update',
            'PATCH',
            '/api/v1/tenants/{tenant_id}/directory',
            ['tenant_id' => $this->tenantId()],
            [],
            $body->toArray(),
        );

        return DirectoryConfig::fromArray($decoded ?? []);
    }

    /**
     * `DELETE /api/v1/tenants/{tenant_id}/directory`
     *
     * `DELETE /api/v1/tenants/{tenant_id}/directory`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     *
     * **Deleting stops the directory, and only that** (§30.3 rule 5): directory accounts can
     * no longer sign in with a password -- there is no fallback to a local hash -- and the
     * sync stops. Sessions, refresh tokens and passkeys those accounts already hold keep
     * working until they expire or the accounts are deactivated. There is no unlink: a linked
     * account stays a directory account.
     */
    public function delete(): void
    {
        $this->transport->send(
            'directory.delete',
            'DELETE',
            '/api/v1/tenants/{tenant_id}/directory',
            ['tenant_id' => $this->tenantId()],
            [],
            null,
        );
    }

    /**
     * `POST /api/v1/tenants/{tenant_id}/directory/links` — link a local account to its
     * directory entry (D-28).
     *
     * `POST /api/v1/tenants/{tenant_id}/directory/links`.
     *
     * **Signs the account's owner out everywhere** (§30.3 rule 6): linking deletes the
     * account's WebAuthn credentials and federation links, revokes its `User` certificates,
     * all its sessions and its OAuth2 refresh tokens (TOTP is kept). The entry is found by the
     * account's own username; a repeat on an already-linked account answers
     * `was_already_linked` and repeats the revocations.
     * @param LinkDirectoryAccount $body the request body
     * @return DirectoryLinkResult
     */
    public function linkAccount(
        LinkDirectoryAccount $body,
    ): DirectoryLinkResult {
        $decoded = $this->transport->send(
            'directory.link_account',
            'POST',
            '/api/v1/tenants/{tenant_id}/directory/links',
            ['tenant_id' => $this->tenantId()],
            [],
            $body->toArray(),
        );

        return DirectoryLinkResult::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/tenants/{tenant_id}/directory/sync-status`
     *
     * `GET /api/v1/tenants/{tenant_id}/directory/sync-status`.
     * @return DirectorySyncStatus
     */
    public function getSyncStatus(): DirectorySyncStatus
    {
        $decoded = $this->transport->send(
            'directory.get_sync_status',
            'GET',
            '/api/v1/tenants/{tenant_id}/directory/sync-status',
            ['tenant_id' => $this->tenantId()],
            [],
            null,
        );

        return DirectorySyncStatus::fromArray($decoded ?? []);
    }
}
