<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\CreateOAuth2ClientRequest;
use Axiam\Sdk\Management\Models\CreateRegistrationTokenRequest;
use Axiam\Sdk\Management\Models\CreateRegistrationTokenResponse;
use Axiam\Sdk\Management\Models\OAuth2ClientCreatedResponse;
use Axiam\Sdk\Management\Models\OAuth2ClientResponse;
use Axiam\Sdk\Management\Models\RegistrationTokenResponse;
use Axiam\Sdk\Management\Models\UpdateOAuth2ClientRequest;

/**
 * Registered OAuth2/OIDC clients -- the registration half of what §12, §21 and §26 then speak
 * to.
 *
 * The `oauth2_clients` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->oauth2Clients()`. Every method here goes through the one shared
 * {@see ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16
 * retry and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class Oauth2ClientsApi extends ManagementSupport
{
    /**
     * `GET /api/v1/oauth2-clients`
     *
     * `GET /api/v1/oauth2-clients`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<OAuth2ClientResponse>
     */
    public function listItems(
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'oauth2_clients.list',
            '/api/v1/oauth2-clients',
            [],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): OAuth2ClientResponse => OAuth2ClientResponse::fromArray($item),
        );
    }

    /**
     * `POST /api/v1/oauth2-clients`
     *
     * `POST /api/v1/oauth2-clients`.
     *
     * The response carries a ONE-TIME secret (`client_secret`): the server will not return it
     * again, so a caller that does not persist it here cannot recover it (§27.5).
     * @param CreateOAuth2ClientRequest $body the request body
     * @return OAuth2ClientCreatedResponse
     */
    public function create(
        CreateOAuth2ClientRequest $body,
    ): OAuth2ClientCreatedResponse {
        $decoded = $this->transport->send(
            'oauth2_clients.create',
            'POST',
            '/api/v1/oauth2-clients',
            [],
            [],
            $body->toArray(),
        );

        return OAuth2ClientCreatedResponse::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/oauth2-clients/{id}`
     *
     * `GET /api/v1/oauth2-clients/{id}`.
     * @param string $id the `{id}` path parameter
     * @return OAuth2ClientResponse
     */
    public function get(
        string $id,
    ): OAuth2ClientResponse {
        $decoded = $this->transport->send(
            'oauth2_clients.get',
            'GET',
            '/api/v1/oauth2-clients/{id}',
            ['id' => $id],
            [],
            null,
        );

        return OAuth2ClientResponse::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/oauth2-clients/{id}`
     *
     * `PUT /api/v1/oauth2-clients/{id}`.
     * @param string $id the `{id}` path parameter
     * @param UpdateOAuth2ClientRequest $body the request body
     * @return OAuth2ClientResponse
     */
    public function update(
        string $id,
        UpdateOAuth2ClientRequest $body,
    ): OAuth2ClientResponse {
        $decoded = $this->transport->send(
            'oauth2_clients.update',
            'PUT',
            '/api/v1/oauth2-clients/{id}',
            ['id' => $id],
            [],
            $body->toArray(),
        );

        return OAuth2ClientResponse::fromArray($decoded ?? []);
    }

    /**
     * `DELETE /api/v1/oauth2-clients/{id}`
     *
     * `DELETE /api/v1/oauth2-clients/{id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $id the `{id}` path parameter
     */
    public function delete(
        string $id,
    ): void {
        $this->transport->send(
            'oauth2_clients.delete',
            'DELETE',
            '/api/v1/oauth2-clients/{id}',
            ['id' => $id],
            [],
            null,
        );
    }

    /**
     * `POST /api/v1/oauth2-clients/registration-tokens`
     *
     * `POST /api/v1/oauth2-clients/registration-tokens`.
     *
     * The response carries a ONE-TIME secret (`initial_access_token`): the server will not
     * return it again, so a caller that does not persist it here cannot recover it (§27.5).
     * @param CreateRegistrationTokenRequest $body the request body
     * @return CreateRegistrationTokenResponse
     */
    public function createRegistrationToken(
        CreateRegistrationTokenRequest $body,
    ): CreateRegistrationTokenResponse {
        $decoded = $this->transport->send(
            'oauth2_clients.create_registration_token',
            'POST',
            '/api/v1/oauth2-clients/registration-tokens',
            [],
            [],
            $body->toArray(),
        );

        return CreateRegistrationTokenResponse::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/oauth2-clients/registration-tokens`
     *
     * `GET /api/v1/oauth2-clients/registration-tokens`.
     *
     * Returns the server's complete list. This endpoint is NOT paginated, so the result is a
     * plain list and never a `Page` (§27.4 rule 4).
     * @return list<RegistrationTokenResponse>
     */
    public function listRegistrationTokens(): array
    {
        $decoded = $this->transport->send(
            'oauth2_clients.list_registration_tokens',
            'GET',
            '/api/v1/oauth2-clients/registration-tokens',
            [],
            [],
            null,
        );

        $items = [];
        foreach ($decoded ?? [] as $item) {
            if (is_array($item)) {
                $items[] = RegistrationTokenResponse::fromArray($item);
            }
        }

        return $items;
    }
}
