<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\Organization;
use Axiam\Sdk\Management\Models\UpdateOrganizationRequest;

/**
 * Organizations an SDK client may read and configure. Creation and deletion are outside the
 * SDK boundary (§27.0).
 *
 * The `organizations` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->organizations()`. Every method here goes through the one shared
 * {@see ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16
 * retry and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class OrganizationsApi extends ManagementSupport
{
    /**
     * `GET /api/v1/organizations`
     *
     * `GET /api/v1/organizations`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<Organization>
     */
    public function listItems(
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'organizations.list',
            '/api/v1/organizations',
            [],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): Organization => Organization::fromArray($item),
        );
    }

    /**
     * `GET /api/v1/organizations/{org_id}`
     *
     * `GET /api/v1/organizations/{org_id}`.
     * @return Organization
     */
    public function get(): Organization
    {
        $decoded = $this->transport->send(
            'organizations.get',
            'GET',
            '/api/v1/organizations/{org_id}',
            ['org_id' => $this->orgId()],
            [],
            null,
        );

        return Organization::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/organizations/{org_id}`
     *
     * `PUT /api/v1/organizations/{org_id}`.
     * @param UpdateOrganizationRequest $body the request body
     * @return Organization
     */
    public function update(
        UpdateOrganizationRequest $body,
    ): Organization {
        $decoded = $this->transport->send(
            'organizations.update',
            'PUT',
            '/api/v1/organizations/{org_id}',
            ['org_id' => $this->orgId()],
            [],
            $body->toArray(),
        );

        return Organization::fromArray($decoded ?? []);
    }
}
