<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\CreatePermissionRequest;
use Axiam\Sdk\Management\Models\Permission;
use Axiam\Sdk\Management\Models\UpdatePermissionRequest;

/**
 * Permissions -- an action on a resource, optionally narrowed by a scope.
 *
 * The `permissions` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->permissions()`. Every method here goes through the one shared {@see
 * ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16 retry
 * and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class PermissionsApi extends ManagementSupport
{
    /**
     * `GET /api/v1/permissions`
     *
     * `GET /api/v1/permissions`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<Permission>
     */
    public function listItems(
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'permissions.list',
            '/api/v1/permissions',
            [],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): Permission => Permission::fromArray($item),
        );
    }

    /**
     * `POST /api/v1/permissions`
     *
     * `POST /api/v1/permissions`.
     * @param CreatePermissionRequest $body the request body
     * @return Permission
     */
    public function create(
        CreatePermissionRequest $body,
    ): Permission {
        $decoded = $this->transport->send(
            'permissions.create',
            'POST',
            '/api/v1/permissions',
            [],
            [],
            $body->toArray(),
        );

        return Permission::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/permissions/{permission_id}`
     *
     * `GET /api/v1/permissions/{permission_id}`.
     * @param string $permissionId the `{permission_id}` path parameter
     * @return Permission
     */
    public function get(
        string $permissionId,
    ): Permission {
        $decoded = $this->transport->send(
            'permissions.get',
            'GET',
            '/api/v1/permissions/{permission_id}',
            ['permission_id' => $permissionId],
            [],
            null,
        );

        return Permission::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/permissions/{permission_id}`
     *
     * `PUT /api/v1/permissions/{permission_id}`.
     * @param string $permissionId the `{permission_id}` path parameter
     * @param UpdatePermissionRequest $body the request body
     * @return Permission
     */
    public function update(
        string $permissionId,
        UpdatePermissionRequest $body,
    ): Permission {
        $decoded = $this->transport->send(
            'permissions.update',
            'PUT',
            '/api/v1/permissions/{permission_id}',
            ['permission_id' => $permissionId],
            [],
            $body->toArray(),
        );

        return Permission::fromArray($decoded ?? []);
    }

    /**
     * `DELETE /api/v1/permissions/{permission_id}`
     *
     * `DELETE /api/v1/permissions/{permission_id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $permissionId the `{permission_id}` path parameter
     */
    public function delete(
        string $permissionId,
    ): void {
        $this->transport->send(
            'permissions.delete',
            'DELETE',
            '/api/v1/permissions/{permission_id}',
            ['permission_id' => $permissionId],
            [],
            null,
        );
    }
}
