<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\CreatePgpKeyRequest;
use Axiam\Sdk\Management\Models\EncryptRequest;
use Axiam\Sdk\Management\Models\EncryptedExport;
use Axiam\Sdk\Management\Models\GeneratedPgpKey;
use Axiam\Sdk\Management\Models\PgpKey;
use Axiam\Sdk\Management\Models\SignAuditBatchRequest;
use Axiam\Sdk\Management\Models\SignedAuditBatch;

/**
 * OpenPGP keys used for audit signing and encrypted data export.
 *
 * The `pgp_keys` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->pgpKeys()`. Every method here goes through the one shared {@see
 * ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16 retry
 * and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class PgpKeysApi extends ManagementSupport
{
    /**
     * `GET /api/v1/pgp-keys`
     *
     * `GET /api/v1/pgp-keys`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<PgpKey>
     */
    public function listItems(
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'pgp_keys.list',
            '/api/v1/pgp-keys',
            [],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): PgpKey => PgpKey::fromArray($item),
        );
    }

    /**
     * `POST /api/v1/pgp-keys`
     *
     * `POST /api/v1/pgp-keys`.
     *
     * The response carries a ONE-TIME secret (`private_key_armored`): the server will not
     * return it again, so a caller that does not persist it here cannot recover it (§27.5).
     * @param CreatePgpKeyRequest $body the request body
     * @return GeneratedPgpKey
     */
    public function generate(
        CreatePgpKeyRequest $body,
    ): GeneratedPgpKey {
        $decoded = $this->transport->send(
            'pgp_keys.generate',
            'POST',
            '/api/v1/pgp-keys',
            [],
            [],
            $body->toArray(),
        );

        return GeneratedPgpKey::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/pgp-keys/{id}`
     *
     * `GET /api/v1/pgp-keys/{id}`.
     * @param string $id the `{id}` path parameter
     * @return PgpKey
     */
    public function get(
        string $id,
    ): PgpKey {
        $decoded = $this->transport->send(
            'pgp_keys.get',
            'GET',
            '/api/v1/pgp-keys/{id}',
            ['id' => $id],
            [],
            null,
        );

        return PgpKey::fromArray($decoded ?? []);
    }

    /**
     * `POST /api/v1/pgp-keys/{id}/revoke`
     *
     * `POST /api/v1/pgp-keys/{id}/revoke`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $id the `{id}` path parameter
     */
    public function revoke(
        string $id,
    ): void {
        $this->transport->send(
            'pgp_keys.revoke',
            'POST',
            '/api/v1/pgp-keys/{id}/revoke',
            ['id' => $id],
            [],
            null,
        );
    }

    /**
     * `POST /api/v1/pgp-keys/{id}/encrypt`
     *
     * `POST /api/v1/pgp-keys/{id}/encrypt`.
     * @param string $id the `{id}` path parameter
     * @param EncryptRequest $body the request body
     * @return EncryptedExport
     */
    public function encrypt(
        string $id,
        EncryptRequest $body,
    ): EncryptedExport {
        $decoded = $this->transport->send(
            'pgp_keys.encrypt',
            'POST',
            '/api/v1/pgp-keys/{id}/encrypt',
            ['id' => $id],
            [],
            $body->toArray(),
        );

        return EncryptedExport::fromArray($decoded ?? []);
    }

    /**
     * `POST /api/v1/pgp-keys/sign-audit-batch`
     *
     * `POST /api/v1/pgp-keys/sign-audit-batch`.
     * @param SignAuditBatchRequest $body the request body
     * @return SignedAuditBatch
     */
    public function signAuditBatch(
        SignAuditBatchRequest $body,
    ): SignedAuditBatch {
        $decoded = $this->transport->send(
            'pgp_keys.sign_audit_batch',
            'POST',
            '/api/v1/pgp-keys/sign-audit-batch',
            [],
            [],
            $body->toArray(),
        );

        return SignedAuditBatch::fromArray($decoded ?? []);
    }
}
