<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\ConsentView;
use Axiam\Sdk\Management\Models\GrantScopeConsent;

/**
 * GDPR self-service: the authenticated account's own export and erasure. Scoped to the caller,
 * never to another user.
 *
 * The `privacy` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->privacy()`. Every method here goes through the one shared {@see
 * ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16 retry
 * and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class PrivacyApi extends ManagementSupport
{
    /**
     * `POST /api/v1/account/export`
     *
     * `POST /api/v1/account/export`.
     *
     * Returns nothing; the server answers with an empty body.
     */
    public function requestExport(): void
    {
        $this->transport->send(
            'privacy.request_export',
            'POST',
            '/api/v1/account/export',
            [],
            [],
            null,
        );
    }

    /**
     * `GET /api/v1/account/export/{token}`
     *
     * `GET /api/v1/account/export/{token}`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $token the `{token}` path parameter
     */
    public function downloadExport(
        string $token,
    ): void {
        $this->transport->send(
            'privacy.download_export',
            'GET',
            '/api/v1/account/export/{token}',
            ['token' => $token],
            [],
            null,
        );
    }

    /**
     * `POST /api/v1/account/delete`
     *
     * `POST /api/v1/account/delete`.
     *
     * Returns nothing; the server answers with an empty body.
     */
    public function requestDelete(): void
    {
        $this->transport->send(
            'privacy.request_delete',
            'POST',
            '/api/v1/account/delete',
            [],
            [],
            null,
        );
    }

    /**
     * `GET /api/v1/auth/account/delete/cancel?token=<opaque>`
     *
     * `GET /api/v1/auth/account/delete/cancel`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $token the required `token` query parameter
     */
    public function cancelDelete(
        string $token,
    ): void {
        $this->transport->send(
            'privacy.cancel_delete',
            'GET',
            '/api/v1/auth/account/delete/cancel',
            [],
            ['token' => $token],
            null,
        );
    }

    /**
     * `GET /api/v1/account/consents` — the caller's own consent records.
     *
     * `GET /api/v1/account/consents`.
     *
     * Returns the server's complete list. This endpoint is NOT paginated, so the result is a
     * plain list and never a `Page` (§27.4 rule 4).
     * @return list<ConsentView>
     */
    public function listConsents(): array
    {
        $decoded = $this->transport->send(
            'privacy.list_consents',
            'GET',
            '/api/v1/account/consents',
            [],
            [],
            null,
        );

        $items = [];
        foreach ($decoded ?? [] as $item) {
            if (is_array($item)) {
                $items[] = ConsentView::fromArray($item);
            }
        }

        return $items;
    }

    /**
     * `POST /api/v1/account/consents/oidc-scopes` — record a scope-release consent.
     *
     * `POST /api/v1/account/consents/oidc-scopes`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param GrantScopeConsent $body the request body
     */
    public function grantScopeConsent(
        GrantScopeConsent $body,
    ): void {
        $this->transport->send(
            'privacy.grant_scope_consent',
            'POST',
            '/api/v1/account/consents/oidc-scopes',
            [],
            [],
            $body->toArray(),
        );
    }

    /**
     * `DELETE /api/v1/account/consents/oidc-scopes/{client_id}` — withdraw.
     *
     * `DELETE /api/v1/account/consents/oidc-scopes/{client_id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $clientId the `{client_id}` path parameter
     */
    public function withdrawScopeConsent(
        string $clientId,
    ): void {
        $this->transport->send(
            'privacy.withdraw_scope_consent',
            'DELETE',
            '/api/v1/account/consents/oidc-scopes/{client_id}',
            ['client_id' => $clientId],
            [],
            null,
        );
    }
}
