<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\AssignRoleToGroupRequest;
use Axiam\Sdk\Management\Models\AssignRoleToServiceAccountRequest;
use Axiam\Sdk\Management\Models\AssignRoleToUserRequest;
use Axiam\Sdk\Management\Models\CreateRoleRequest;
use Axiam\Sdk\Management\Models\GrantPermissionRequest;
use Axiam\Sdk\Management\Models\ResolvedPermissionGrant;
use Axiam\Sdk\Management\Models\Role;
use Axiam\Sdk\Management\Models\RoleGroupAssignment;
use Axiam\Sdk\Management\Models\RoleServiceAccountAssignment;
use Axiam\Sdk\Management\Models\RoleUserAssignment;
use Axiam\Sdk\Management\Models\UpdateRole;

/**
 * Roles, their permission sets, and their assignment to users and groups.
 *
 * The `roles` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->roles()`. Every method here goes through the one shared {@see
 * ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16 retry
 * and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class RolesApi extends ManagementSupport
{
    /**
     * `GET /api/v1/roles`
     *
     * `GET /api/v1/roles`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<Role>
     */
    public function listItems(
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'roles.list',
            '/api/v1/roles',
            [],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): Role => Role::fromArray($item),
        );
    }

    /**
     * `POST /api/v1/roles`
     *
     * `POST /api/v1/roles`.
     * @param CreateRoleRequest $body the request body
     * @return Role
     */
    public function create(
        CreateRoleRequest $body,
    ): Role {
        $decoded = $this->transport->send(
            'roles.create',
            'POST',
            '/api/v1/roles',
            [],
            [],
            $body->toArray(),
        );

        return Role::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/roles/{role_id}`
     *
     * `GET /api/v1/roles/{role_id}`.
     * @param string $roleId the `{role_id}` path parameter
     * @return Role
     */
    public function get(
        string $roleId,
    ): Role {
        $decoded = $this->transport->send(
            'roles.get',
            'GET',
            '/api/v1/roles/{role_id}',
            ['role_id' => $roleId],
            [],
            null,
        );

        return Role::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/roles/{role_id}`
     *
     * `PUT /api/v1/roles/{role_id}`.
     * @param string $roleId the `{role_id}` path parameter
     * @param UpdateRole $body the request body
     * @return Role
     */
    public function update(
        string $roleId,
        UpdateRole $body,
    ): Role {
        $decoded = $this->transport->send(
            'roles.update',
            'PUT',
            '/api/v1/roles/{role_id}',
            ['role_id' => $roleId],
            [],
            $body->toArray(),
        );

        return Role::fromArray($decoded ?? []);
    }

    /**
     * `DELETE /api/v1/roles/{role_id}`
     *
     * `DELETE /api/v1/roles/{role_id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $roleId the `{role_id}` path parameter
     */
    public function delete(
        string $roleId,
    ): void {
        $this->transport->send(
            'roles.delete',
            'DELETE',
            '/api/v1/roles/{role_id}',
            ['role_id' => $roleId],
            [],
            null,
        );
    }

    /**
     * `GET /api/v1/roles/{role_id}/users`
     *
     * `GET /api/v1/roles/{role_id}/users`.
     *
     * Returns the server's complete list. This endpoint is NOT paginated, so the result is a
     * plain list and never a `Page` (§27.4 rule 4).
     * @param string $roleId the `{role_id}` path parameter
     * @return list<RoleUserAssignment>
     */
    public function listUsers(
        string $roleId,
    ): array {
        $decoded = $this->transport->send(
            'roles.list_users',
            'GET',
            '/api/v1/roles/{role_id}/users',
            ['role_id' => $roleId],
            [],
            null,
        );

        $items = [];
        foreach ($decoded ?? [] as $item) {
            if (is_array($item)) {
                $items[] = RoleUserAssignment::fromArray($item);
            }
        }

        return $items;
    }

    /**
     * `POST /api/v1/roles/{role_id}/users`
     *
     * `POST /api/v1/roles/{role_id}/users`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $roleId the `{role_id}` path parameter
     * @param AssignRoleToUserRequest $body the request body
     */
    public function assignToUser(
        string $roleId,
        AssignRoleToUserRequest $body,
    ): void {
        $this->transport->send(
            'roles.assign_to_user',
            'POST',
            '/api/v1/roles/{role_id}/users',
            ['role_id' => $roleId],
            [],
            $body->toArray(),
        );
    }

    /**
     * `DELETE /api/v1/roles/{role_id}/users/{user_id}`
     *
     * `DELETE /api/v1/roles/{role_id}/users/{user_id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $roleId the `{role_id}` path parameter
     * @param string $userId the `{user_id}` path parameter
     * @param string|null $resourceId the optional `resource_id` query parameter
     */
    public function unassignFromUser(
        string $roleId,
        string $userId,
        ?string $resourceId = null,
    ): void {
        $this->transport->send(
            'roles.unassign_from_user',
            'DELETE',
            '/api/v1/roles/{role_id}/users/{user_id}',
            ['role_id' => $roleId, 'user_id' => $userId],
            ['resource_id' => $resourceId],
            null,
        );
    }

    /**
     * `GET /api/v1/roles/{role_id}/groups`
     *
     * `GET /api/v1/roles/{role_id}/groups`.
     *
     * Returns the server's complete list. This endpoint is NOT paginated, so the result is a
     * plain list and never a `Page` (§27.4 rule 4).
     * @param string $roleId the `{role_id}` path parameter
     * @return list<RoleGroupAssignment>
     */
    public function listGroups(
        string $roleId,
    ): array {
        $decoded = $this->transport->send(
            'roles.list_groups',
            'GET',
            '/api/v1/roles/{role_id}/groups',
            ['role_id' => $roleId],
            [],
            null,
        );

        $items = [];
        foreach ($decoded ?? [] as $item) {
            if (is_array($item)) {
                $items[] = RoleGroupAssignment::fromArray($item);
            }
        }

        return $items;
    }

    /**
     * `POST /api/v1/roles/{role_id}/groups`
     *
     * `POST /api/v1/roles/{role_id}/groups`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $roleId the `{role_id}` path parameter
     * @param AssignRoleToGroupRequest $body the request body
     */
    public function assignToGroup(
        string $roleId,
        AssignRoleToGroupRequest $body,
    ): void {
        $this->transport->send(
            'roles.assign_to_group',
            'POST',
            '/api/v1/roles/{role_id}/groups',
            ['role_id' => $roleId],
            [],
            $body->toArray(),
        );
    }

    /**
     * `DELETE /api/v1/roles/{role_id}/groups/{group_id}`
     *
     * `DELETE /api/v1/roles/{role_id}/groups/{group_id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $roleId the `{role_id}` path parameter
     * @param string $groupId the `{group_id}` path parameter
     * @param string|null $resourceId the optional `resource_id` query parameter
     */
    public function unassignFromGroup(
        string $roleId,
        string $groupId,
        ?string $resourceId = null,
    ): void {
        $this->transport->send(
            'roles.unassign_from_group',
            'DELETE',
            '/api/v1/roles/{role_id}/groups/{group_id}',
            ['role_id' => $roleId, 'group_id' => $groupId],
            ['resource_id' => $resourceId],
            null,
        );
    }

    /**
     * `GET /api/v1/roles/{role_id}/permissions`
     *
     * `GET /api/v1/roles/{role_id}/permissions`.
     *
     * Returns the server's complete list. This endpoint is NOT paginated, so the result is a
     * plain list and never a `Page` (§27.4 rule 4).
     * @param string $roleId the `{role_id}` path parameter
     * @return list<ResolvedPermissionGrant>
     */
    public function listPermissions(
        string $roleId,
    ): array {
        $decoded = $this->transport->send(
            'roles.list_permissions',
            'GET',
            '/api/v1/roles/{role_id}/permissions',
            ['role_id' => $roleId],
            [],
            null,
        );

        $items = [];
        foreach ($decoded ?? [] as $item) {
            if (is_array($item)) {
                $items[] = ResolvedPermissionGrant::fromArray($item);
            }
        }

        return $items;
    }

    /**
     * `POST /api/v1/roles/{role_id}/permissions`
     *
     * `POST /api/v1/roles/{role_id}/permissions`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $roleId the `{role_id}` path parameter
     * @param GrantPermissionRequest $body the request body
     */
    public function grantPermission(
        string $roleId,
        GrantPermissionRequest $body,
    ): void {
        $this->transport->send(
            'roles.grant_permission',
            'POST',
            '/api/v1/roles/{role_id}/permissions',
            ['role_id' => $roleId],
            [],
            $body->toArray(),
        );
    }

    /**
     * `DELETE /api/v1/roles/{role_id}/permissions/{permission_id}`
     *
     * `DELETE /api/v1/roles/{role_id}/permissions/{permission_id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $roleId the `{role_id}` path parameter
     * @param string $permissionId the `{permission_id}` path parameter
     */
    public function revokePermission(
        string $roleId,
        string $permissionId,
    ): void {
        $this->transport->send(
            'roles.revoke_permission',
            'DELETE',
            '/api/v1/roles/{role_id}/permissions/{permission_id}',
            ['role_id' => $roleId, 'permission_id' => $permissionId],
            [],
            null,
        );
    }

    /**
     * `GET /api/v1/roles/{role_id}/service-accounts`
     *
     * `GET /api/v1/roles/{role_id}/service-accounts`.
     *
     * Returns the server's complete list. This endpoint is NOT paginated, so the result is a
     * plain list and never a `Page` (§27.4 rule 4).
     * @param string $roleId the `{role_id}` path parameter
     * @return list<RoleServiceAccountAssignment>
     */
    public function listServiceAccounts(
        string $roleId,
    ): array {
        $decoded = $this->transport->send(
            'roles.list_service_accounts',
            'GET',
            '/api/v1/roles/{role_id}/service-accounts',
            ['role_id' => $roleId],
            [],
            null,
        );

        $items = [];
        foreach ($decoded ?? [] as $item) {
            if (is_array($item)) {
                $items[] = RoleServiceAccountAssignment::fromArray($item);
            }
        }

        return $items;
    }

    /**
     * `POST /api/v1/roles/{role_id}/service-accounts`
     *
     * `POST /api/v1/roles/{role_id}/service-accounts`.
     *
     * Returns nothing; the server answers with an empty body.
     * @param string $roleId the `{role_id}` path parameter
     * @param AssignRoleToServiceAccountRequest $body the request body
     */
    public function assignToServiceAccount(
        string $roleId,
        AssignRoleToServiceAccountRequest $body,
    ): void {
        $this->transport->send(
            'roles.assign_to_service_account',
            'POST',
            '/api/v1/roles/{role_id}/service-accounts',
            ['role_id' => $roleId],
            [],
            $body->toArray(),
        );
    }

    /**
     * `DELETE /api/v1/roles/{role_id}/service-accounts/{service_account_id}`
     *
     * `DELETE /api/v1/roles/{role_id}/service-accounts/{service_account_id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     * @param string $roleId the `{role_id}` path parameter
     * @param string $serviceAccountId the `{service_account_id}` path parameter
     * @param string|null $resourceId the optional `resource_id` query parameter
     */
    public function unassignFromServiceAccount(
        string $roleId,
        string $serviceAccountId,
        ?string $resourceId = null,
    ): void {
        $this->transport->send(
            'roles.unassign_from_service_account',
            'DELETE',
            '/api/v1/roles/{role_id}/service-accounts/{service_account_id}',
            ['role_id' => $roleId, 'service_account_id' => $serviceAccountId],
            ['resource_id' => $resourceId],
            null,
        );
    }
}
