<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\ScimReconcileAccepted;
use Axiam\Sdk\Management\Models\ScimTargetInput;
use Axiam\Sdk\Management\Models\ScimTargetResponse;

/**
 * A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM 2.0 service providers
 * AXIAM pushes the tenant's users and groups to, each with its delivery state. The credential
 * AXIAM pushes with is write-only. Deleting a target does not deprovision anything downstream.
 *
 * The `scim_targets` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->scimTargets()`. Every method here goes through the one shared {@see
 * ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16 retry
 * and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class ScimTargetsApi extends ManagementSupport
{
    /**
     * `GET /api/v1/scim-targets`
     *
     * `GET /api/v1/scim-targets`.
     *
     * Returns ONE page. `Page::$total` is the server's count across all pages and is not
     * `count($page)` — see §27.4 rule 4.
     * @param PageRequest|null $page which page to fetch; defaults to the first
     * @return Page<ScimTargetResponse>
     */
    public function listItems(
        ?PageRequest $page = null,
    ): Page {
        return $this->transport->sendPage(
            'scim_targets.list',
            '/api/v1/scim-targets',
            [],
            [],
            $page ?? new PageRequest(),
            static fn (array $item): ScimTargetResponse => ScimTargetResponse::fromArray($item),
        );
    }

    /**
     * `POST /api/v1/scim-targets`
     *
     * `POST /api/v1/scim-targets`.
     *
     * `credential` is required here (§31.3 rule 2). It is write-only: no response ever carries
     * it, and the SDK keeps no copy.
     * @param ScimTargetInput $body the request body
     * @return ScimTargetResponse
     */
    public function create(
        ScimTargetInput $body,
    ): ScimTargetResponse {
        $decoded = $this->transport->send(
            'scim_targets.create',
            'POST',
            '/api/v1/scim-targets',
            [],
            [],
            $body->toArray(),
        );

        return ScimTargetResponse::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/scim-targets/{id}`
     *
     * `GET /api/v1/scim-targets/{id}`.
     * @param string $id the `{id}` path parameter
     * @return ScimTargetResponse
     */
    public function get(
        string $id,
    ): ScimTargetResponse {
        $decoded = $this->transport->send(
            'scim_targets.get',
            'GET',
            '/api/v1/scim-targets/{id}',
            ['id' => $id],
            [],
            null,
        );

        return ScimTargetResponse::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/scim-targets/{id}`
     *
     * `PUT /api/v1/scim-targets/{id}`.
     *
     * **The credential is bound to its URL** (§31.3 rule 2): absent `credential` keeps the
     * stored one -- except that changing `base_url` of a bearer target, `auth.token_url` or
     * `base_url` of a client-credentials target, or `auth.type`, without `credential` in the
     * same write is refused `400` and changes nothing. The SDK holds no credential to re-send.
     * Every other member left out takes its default -- start from {@see
     * \Axiam\Sdk\Management\ReadModifyWrite::scimTarget()}. An update overtaken by another
     * administrator's write is `409` (§31.3 rule 4): reload, then retry yourself.
     * @param string $id the `{id}` path parameter
     * @param ScimTargetInput $body the request body
     * @return ScimTargetResponse
     */
    public function update(
        string $id,
        ScimTargetInput $body,
    ): ScimTargetResponse {
        $decoded = $this->transport->send(
            'scim_targets.update',
            'PUT',
            '/api/v1/scim-targets/{id}',
            ['id' => $id],
            [],
            $body->toArray(),
        );

        return ScimTargetResponse::fromArray($decoded ?? []);
    }

    /**
     * `DELETE /api/v1/scim-targets/{id}`
     *
     * `DELETE /api/v1/scim-targets/{id}`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     *
     * **Deprovisions nothing downstream** (§31.3 rule 8): the users and groups AXIAM created
     * in the service provider stay there, and AXIAM no longer knows them. To remove them, set
     * `deprovision` to `delete`, let AXIAM push, and only then delete the target.
     * @param string $id the `{id}` path parameter
     */
    public function delete(
        string $id,
    ): void {
        $this->transport->send(
            'scim_targets.delete',
            'DELETE',
            '/api/v1/scim-targets/{id}',
            ['id' => $id],
            [],
            null,
        );
    }

    /**
     * `POST /api/v1/scim-targets/{id}/reconcile`
     *
     * `POST /api/v1/scim-targets/{id}/reconcile`.
     *
     * Starts a reconciliation in the background and answers `202`; its outcome is on the
     * target's `state` (§31.3 rule 7). `409` while a run holds the claim, within five minutes
     * of the last one, or for a disabled target. Not retried, and nothing here polls for the
     * run to finish.
     * @param string $id the `{id}` path parameter
     * @return ScimReconcileAccepted
     */
    public function reconcile(
        string $id,
    ): ScimReconcileAccepted {
        $decoded = $this->transport->send(
            'scim_targets.reconcile',
            'POST',
            '/api/v1/scim-targets/{id}/reconcile',
            ['id' => $id],
            [],
            null,
        );

        return ScimReconcileAccepted::fromArray($decoded ?? []);
    }
}
