<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management;

use Axiam\Sdk\Management\Models\SecuritySettings;
use Axiam\Sdk\Management\Models\SetOrgSettings;
use Axiam\Sdk\Management\Models\TenantSettingsOverride;

/**
 * Effective settings, and the organization/tenant layers they resolve from.
 *
 * The `settings` namespace handle (CONTRACT.md §27.2), reached as
 * `$client->management()->settings()`. Every method here goes through the one shared {@see
 * ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant header, §6 TLS, §16 retry
 * and §19 telemetry apply without this class doing anything to opt in (§27.8).
 */
final class SettingsApi extends ManagementSupport
{
    /**
     * `GET /api/v1/organizations/{org_id}/settings`
     *
     * `GET /api/v1/organizations/{org_id}/settings`.
     * @return SecuritySettings
     */
    public function getOrg(): SecuritySettings
    {
        $decoded = $this->transport->send(
            'settings.get_org',
            'GET',
            '/api/v1/organizations/{org_id}/settings',
            ['org_id' => $this->orgId()],
            [],
            null,
        );

        return SecuritySettings::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/organizations/{org_id}/settings`
     *
     * `PUT /api/v1/organizations/{org_id}/settings`.
     * @param SetOrgSettings $body the request body
     * @return SecuritySettings
     */
    public function setOrg(
        SetOrgSettings $body,
    ): SecuritySettings {
        $decoded = $this->transport->send(
            'settings.set_org',
            'PUT',
            '/api/v1/organizations/{org_id}/settings',
            ['org_id' => $this->orgId()],
            [],
            $body->toArray(),
        );

        return SecuritySettings::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/settings`
     *
     * `GET /api/v1/settings`.
     * @return SecuritySettings
     */
    public function getEffective(): SecuritySettings
    {
        $decoded = $this->transport->send(
            'settings.get_effective',
            'GET',
            '/api/v1/settings',
            [],
            [],
            null,
        );

        return SecuritySettings::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/settings`
     *
     * `PUT /api/v1/settings`.
     * @param TenantSettingsOverride $body the request body
     * @return SecuritySettings
     */
    public function setEffective(
        TenantSettingsOverride $body,
    ): SecuritySettings {
        $decoded = $this->transport->send(
            'settings.set_effective',
            'PUT',
            '/api/v1/settings',
            [],
            [],
            $body->toArray(),
        );

        return SecuritySettings::fromArray($decoded ?? []);
    }

    /**
     * `GET /api/v1/tenants/{tenant_id}/settings`
     *
     * `GET /api/v1/tenants/{tenant_id}/settings`.
     * @return TenantSettingsOverride
     */
    public function getTenantOverride(): TenantSettingsOverride
    {
        $decoded = $this->transport->send(
            'settings.get_tenant_override',
            'GET',
            '/api/v1/tenants/{tenant_id}/settings',
            ['tenant_id' => $this->tenantId()],
            [],
            null,
        );

        return TenantSettingsOverride::fromArray($decoded ?? []);
    }

    /**
     * `PUT /api/v1/tenants/{tenant_id}/settings`
     *
     * `PUT /api/v1/tenants/{tenant_id}/settings`.
     * @param TenantSettingsOverride $body the request body
     * @return TenantSettingsOverride
     */
    public function setTenantOverride(
        TenantSettingsOverride $body,
    ): TenantSettingsOverride {
        $decoded = $this->transport->send(
            'settings.set_tenant_override',
            'PUT',
            '/api/v1/tenants/{tenant_id}/settings',
            ['tenant_id' => $this->tenantId()],
            [],
            $body->toArray(),
        );

        return TenantSettingsOverride::fromArray($decoded ?? []);
    }

    /**
     * `DELETE /api/v1/tenants/{tenant_id}/settings`
     *
     * `DELETE /api/v1/tenants/{tenant_id}/settings`.
     *
     * Returns nothing; the server answers with an empty body.
     *
     * NOT idempotent (§27.4 rule 6): deleting something already deleted raises {@see
     * \Axiam\Sdk\Management\NotFoundError} rather than succeeding quietly.
     */
    public function deleteTenantOverride(): void
    {
        $this->transport->send(
            'settings.delete_tenant_override',
            'DELETE',
            '/api/v1/tenants/{tenant_id}/settings',
            ['tenant_id' => $this->tenantId()],
            [],
            null,
        );
    }
}
