<?php

declare(strict_types=1);

namespace Axiam\Sdk\Tests;

use Axiam\Sdk\Amqp\ReplayGuard;
use Axiam\Sdk\Reactor\ReactorAnswer;
use Axiam\Sdk\Reactor\ReactorEvent;
use Axiam\Sdk\Reactor\ReactorEvents;
use Axiam\Sdk\Reactor\ReactorProtocol;
use Axiam\Sdk\Reactor\ReactorRejection;
use PHPUnit\Framework\TestCase;

/**
 * CONTRACT.md §22.13 — the reactor wire vectors, both directions.
 *
 * The fixture is GENERATED by the server's own reactor sign path
 * (`axiam-amqp::reactor::protocol`) and is committed beside the §8 vectors in
 * `crates/axiam-amqp/tests/fixtures/`, under the same master key, tenant and
 * derived subkey — which is why one loader idiom serves both files.
 *
 * The single most likely place for an SDK to produce a MAC that will not verify
 * is the one canonicalization difference from §8: on a reactor event and a
 * reactor reply, `hmac_signature` is serialized as JSON **null** inside the signed
 * bytes rather than omitted. Every assertion below runs against
 * `canonical_signed_json` byte-for-byte so that difference is a test rather than a
 * paragraph to remember.
 */
final class ReactorVectorsTest extends TestCase
{
    private const REPLY_NONCE = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';

    /** @return array<string, mixed> */
    private static function vectors(): array
    {
        $raw = file_get_contents(__DIR__ . '/Fixtures/reactor_v2_reference_vectors.json');
        self::assertIsString($raw, 'the §22.13 reactor vectors must be vendored beside the §8 ones');
        /** @var array<string, mixed> $decoded */
        $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);

        return $decoded;
    }

    private static function subkey(): string
    {
        /** @var array{hkdf: array{derived_subkey_hex: string}} $v */
        $v = self::vectors();
        $key = hex2bin($v['hkdf']['derived_subkey_hex']);
        self::assertIsString($key);

        return $key;
    }

    private static function now(): int
    {
        /** @var array{verified_at: string} $v */
        $v = self::vectors();
        $ts = strtotime($v['verified_at']);
        self::assertIsInt($ts);

        return $ts;
    }

    /**
     * Renders the on-the-wire form of a vector: its canonical bytes with the
     * `null` placeholder replaced by the committed signature.
     *
     * The fixture's own `message` object is pretty-printed with alphabetically
     * ordered keys, which is fine for a decoder but NOT usable here — `payload` is
     * echoed byte-for-byte into the bytes this SDK re-signs, so re-indenting it
     * would change the MAC. The canonical form IS the wire form modulo that one
     * substitution.
     *
     * @param array{canonical_signed_json: string, hmac_signature_hex: string} $vector
     */
    private static function wireBody(array $vector): string
    {
        return str_replace(
            '"hmac_signature":null',
            '"hmac_signature":"' . $vector['hmac_signature_hex'] . '"',
            $vector['canonical_signed_json'],
        );
    }

    private static function guard(int $now): ReplayGuard
    {
        return new ReplayGuard(ReactorProtocol::FRESHNESS_SKEW_SECONDS, static fn (): int => $now);
    }

    /**
     * The fixture's own declarations, pinned so a regenerated file that moved a
     * field cannot pass silently — and so §22.1's topology strings are asserted
     * against the server's rendering rather than against a reimplemented format
     * string.
     */
    public function testFixtureShapeAndTopology(): void
    {
        /** @var array{key_version: int, freshness_skew_secs: int, tenant_id: string, reactor_id: string, topology: array<string, string>, field_order: array<string, list<string>>} $v */
        $v = self::vectors();

        self::assertSame(ReactorProtocol::KEY_VERSION, $v['key_version']);
        self::assertSame(ReactorProtocol::FRESHNESS_SKEW_SECONDS, $v['freshness_skew_secs']);
        self::assertSame(ReactorEvents::EXCHANGE, $v['topology']['exchange']);
        self::assertSame(ReactorEvents::EXCHANGE_TYPE, $v['topology']['exchange_type']);
        self::assertSame(
            $v['topology']['queue'],
            ReactorEvents::queueName($v['tenant_id'], $v['reactor_id']),
        );
        self::assertSame(
            $v['topology']['routing_key_token_pre_issue'],
            ReactorEvents::routingKey($v['tenant_id'], ReactorEvents::TOKEN_PRE_ISSUE),
        );
        self::assertSame(
            $v['topology']['routing_key_login_post_auth'],
            ReactorEvents::routingKey($v['tenant_id'], ReactorEvents::LOGIN_POST_AUTH),
        );

        // The field order the fixture names is the order this SDK's canonical
        // bodies are built in. The fixture annotates two entries, hence the prefix
        // comparison.
        $declaredEvent = [
            'tenant_id', 'event', 'correlation_id', 'payload', 'timeout_ms',
            'key_version', 'nonce', 'issued_at', 'hmac_signature',
        ];
        $declaredReply = [
            'correlation_id', 'tenant_id', 'event', 'decision', 'reason', 'patch',
            'require_mfa', 'key_version', 'nonce', 'issued_at', 'hmac_signature',
        ];
        self::assertCount(count($declaredEvent), $v['field_order']['reactor_event']);
        foreach ($declaredEvent as $i => $name) {
            self::assertStringStartsWith($name, $v['field_order']['reactor_event'][$i]);
        }
        self::assertCount(count($declaredReply), $v['field_order']['reactor_reply']);
        foreach ($declaredReply as $i => $name) {
            self::assertStringStartsWith($name, $v['field_order']['reactor_reply'][$i]);
        }
    }

    /**
     * §22.13 verify direction: every committed event vector verifies under the
     * derived subkey, and fails under any other key. The per-tenant subkey is what
     * stops a reactor in one tenant reading another's events.
     */
    public function testVerifyDirection(): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string, server_to_reactor: array<string, array{canonical_signed_json: string, hmac_signature_hex: string, routing_key: string}>} $v */
        $v = self::vectors();
        $now = self::now();
        self::assertNotEmpty($v['server_to_reactor']);

        foreach ($v['server_to_reactor'] as $name => $vector) {
            $body = self::wireBody($vector);

            $event = ReactorProtocol::decodeEvent(self::subkey(), $body, $v['tenant_id'], self::guard($now), $now);
            self::assertSame($v['tenant_id'], $event->tenantId, $name);
            self::assertSame($v['expected_correlation_id'], $event->correlationId, $name);
            self::assertSame($vector['routing_key'], ReactorEvents::routingKey($event->tenantId, $event->event), $name);
            self::assertGreaterThan(0, $event->timeoutMs, $name);
            self::assertNotNull($event->spec(), $name);

            $otherKey = self::subkey();
            $otherKey[0] = chr(ord($otherKey[0]) ^ 0xFF);
            try {
                ReactorProtocol::decodeEvent($otherKey, $body, $v['tenant_id'], self::guard($now), $now);
                self::fail("$name must NOT verify under a different key");
            } catch (ReactorRejection $rejection) {
                self::assertSame(ReactorRejection::BAD_SIGNATURE, $rejection->reason());
            }
        }
    }

    /**
     * §22.13's four named tamper targets. Each edit is applied to the wire bytes
     * AFTER signing.
     *
     * @dataProvider tamperProvider
     */
    public function testTamperingInvalidates(string $from, string $to, string $tenantOverride): void
    {
        /** @var array{tenant_id: string, server_to_reactor: array<string, array{canonical_signed_json: string, hmac_signature_hex: string}>} $v */
        $v = self::vectors();
        $now = self::now();
        $body = self::wireBody($v['server_to_reactor']['token_pre_issue']);

        $from = $from === '@tenant' ? $v['tenant_id'] : $from;
        $tampered = str_replace($from, $to, $body);
        self::assertNotSame($body, $tampered, 'test bug: the tamper target was not found in the vector body');

        // For the tenant_id case the decode is told the TAMPERED tenant, so the
        // failure can only come from the MAC and not from the identity check.
        $tenant = $tenantOverride === '' ? $v['tenant_id'] : $tenantOverride;

        $this->expectException(ReactorRejection::class);
        ReactorProtocol::decodeEvent(self::subkey(), $tampered, $tenant, self::guard($now), $now);
    }

    /** @return array<string, array{string, string, string}> */
    public static function tamperProvider(): array
    {
        return [
            'payload' => ['"sub":"alice"', '"sub":"root"', ''],
            'timeout_ms' => ['"timeout_ms":500', '"timeout_ms":5000', ''],
            'tenant_id' => ['@tenant', '99999999-9999-9999-9999-999999999999', '99999999-9999-9999-9999-999999999999'],
            'nonce' => ['"nonce":"aaaaaaaa', '"nonce":"abaaaaaa', ''],
        ];
    }

    /**
     * §22.2's ordering: a body carrying less than `key_version` 2 is refused
     * before anything else about it is considered — including its signature, which
     * in the fixture's downgraded vector no longer matches at all. The fixture
     * downgrades AFTER signing precisely so an implementation that checks the MAC
     * first fails here.
     */
    public function testKeyVersionRefusedBeforeSignature(): void
    {
        /** @var array{tenant_id: string, rejected_replies: array<string, array{canonical_signed_json: string, hmac_signature_hex: string, expected_rejection: string}>, server_to_reactor: array<string, array{canonical_signed_json: string, hmac_signature_hex: string}>} $v */
        $v = self::vectors();
        $now = self::now();

        self::assertSame('key_version_too_old', $v['rejected_replies']['key_version_too_old']['expected_rejection']);

        $downgraded = str_replace(
            '"key_version":2',
            '"key_version":1',
            self::wireBody($v['server_to_reactor']['token_pre_issue']),
        );

        try {
            ReactorProtocol::decodeEvent(self::subkey(), $downgraded, $v['tenant_id'], self::guard($now), $now);
            self::fail('key_version 1 must be refused');
        } catch (ReactorRejection $rejection) {
            self::assertSame(
                ReactorRejection::KEY_VERSION_TOO_OLD,
                $rejection->reason(),
                'the refusal must name the key_version gate, not the signature',
            );
        }
    }

    /**
     * §22.13's "in BOTH directions": a timestamp ahead of the verifier's clock is
     * not extra fresh, it is the shape of a captured message held for later.
     *
     * @dataProvider freshnessProvider
     */
    public function testFreshnessBothDirections(int $offsetSeconds, bool $accepted): void
    {
        /** @var array{tenant_id: string, server_to_reactor: array<string, array{canonical_signed_json: string, hmac_signature_hex: string}>} $v */
        $v = self::vectors();
        $issued = self::now();
        $body = self::wireBody($v['server_to_reactor']['token_pre_issue']);
        $now = $issued + $offsetSeconds;

        if ($accepted) {
            $event = ReactorProtocol::decodeEvent(self::subkey(), $body, $v['tenant_id'], self::guard($now), $now);
            self::assertSame(ReactorEvents::TOKEN_PRE_ISSUE, $event->event);

            return;
        }

        try {
            ReactorProtocol::decodeEvent(self::subkey(), $body, $v['tenant_id'], self::guard($now), $now);
            self::fail('an issued_at outside ±300 s must be refused');
        } catch (ReactorRejection $rejection) {
            self::assertSame(ReactorRejection::STALE, $rejection->reason());
        }
    }

    /** @return array<string, array{int, bool}> */
    public static function freshnessProvider(): array
    {
        $skew = ReactorProtocol::FRESHNESS_SKEW_SECONDS;

        return [
            'at the edge, stale side' => [$skew, true],
            'one second past the edge, stale side' => [$skew + 1, false],
            'at the edge, future side' => [-$skew, true],
            'one second past the edge, future side' => [-$skew - 1, false],
        ];
    }

    /**
     * The seen-set: the same event delivered twice inside the window is refused
     * the second time. ONE guard must serve every delivery, which is why the
     * runtime builds it once per process.
     */
    public function testNonceReplayRefused(): void
    {
        /** @var array{tenant_id: string, server_to_reactor: array<string, array{canonical_signed_json: string, hmac_signature_hex: string}>} $v */
        $v = self::vectors();
        $now = self::now();
        $body = self::wireBody($v['server_to_reactor']['token_pre_issue']);
        $guard = self::guard($now);

        $first = ReactorProtocol::decodeEvent(self::subkey(), $body, $v['tenant_id'], $guard, $now);
        self::assertSame(ReactorEvents::TOKEN_PRE_ISSUE, $first->event);

        try {
            ReactorProtocol::decodeEvent(self::subkey(), $body, $v['tenant_id'], $guard, $now);
            self::fail('a redelivered nonce must be refused as a replay');
        } catch (ReactorRejection $rejection) {
            self::assertSame(ReactorRejection::REPLAY, $rejection->reason());
        }
    }

    /**
     * A reactor never acts on another tenant's event, even when the signature is
     * perfectly valid for that other tenant.
     */
    public function testTenantMismatchRefused(): void
    {
        /** @var array{server_to_reactor: array<string, array{canonical_signed_json: string, hmac_signature_hex: string}>} $v */
        $v = self::vectors();
        $now = self::now();
        $body = self::wireBody($v['server_to_reactor']['token_pre_issue']);

        try {
            ReactorProtocol::decodeEvent(
                self::subkey(),
                $body,
                '99999999-9999-9999-9999-999999999999',
                self::guard($now),
                $now,
            );
            self::fail("an event for another tenant must be refused");
        } catch (ReactorRejection $rejection) {
            self::assertSame(ReactorRejection::TENANT_MISMATCH, $rejection->reason());
        }
    }

    /**
     * §22.13 sign direction. For each committed reply vector, building the reply
     * from its fields reproduces `canonical_signed_json` byte-for-byte AND
     * recomputes `hmac_signature_hex`.
     *
     * One assertion covers both: the published body is the canonical bytes with
     * the null placeholder replaced by the signature this SDK computed, so
     * equality against that string proves the canonicalization and the MAC
     * together.
     *
     * @dataProvider signProvider
     */
    public function testSignDirection(string $vectorName, string $eventName, string $answerFactory): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string, reactor_to_server: array<string, array{canonical_signed_json: string, hmac_signature_hex: string}>} $v */
        $v = self::vectors();
        $now = self::now();
        $vector = $v['reactor_to_server'][$vectorName];

        $answer = match ($answerFactory) {
            'allow' => ReactorAnswer::allow(),
            'step_up' => ReactorAnswer::allowWithStepUp(),
            'deny' => ReactorAnswer::deny('embargoed region'),
            // Deliberately built in NON-sorted order: the server's BTreeMap emits
            // sorted keys, so the SDK must sort rather than echo insertion order.
            default => ReactorAnswer::mutate(['ext.department' => 'eng', 'ext.cost_center' => '42']),
        };

        $body = ReactorProtocol::buildReply(
            self::subkey(),
            self::eventFor($v['tenant_id'], $eventName, $v['expected_correlation_id'], $now),
            $answer,
            self::REPLY_NONCE,
            $now,
        );

        self::assertSame(self::wireBody($vector), $body);
    }

    /** @return array<string, array{string, string, string}> */
    public static function signProvider(): array
    {
        return [
            'allow' => ['allow', ReactorEvents::LOGIN_POST_AUTH, 'allow'],
            'deny' => ['deny', ReactorEvents::LOGIN_POST_AUTH, 'deny'],
            'mutate' => ['mutate', ReactorEvents::TOKEN_PRE_ISSUE, 'mutate'],
            'require_mfa' => ['require_mfa', ReactorEvents::LOGIN_POST_AUTH, 'step_up'],
        ];
    }

    /**
     * §22.2's three conditional omissions, asserted DIRECTLY rather than only as a
     * side effect of the vectors matching. A reply that serializes
     * `"require_mfa": false` rather than omitting it produces different canonical
     * bytes and therefore a different MAC.
     */
    public function testReplyOmissionRules(): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string} $v */
        $v = self::vectors();
        $now = self::now();
        $event = self::eventFor($v['tenant_id'], ReactorEvents::LOGIN_POST_AUTH, $v['expected_correlation_id'], $now);

        $allow = ReactorProtocol::buildReply(self::subkey(), $event, ReactorAnswer::allow(), self::REPLY_NONCE, $now);
        foreach (['require_mfa', 'reason', 'patch'] as $absent) {
            self::assertStringNotContainsString($absent, $allow, "an allow reply MUST omit $absent entirely");
        }

        // A deny with no reason still denies: the server substitutes its own
        // string, so the SDK omits the field rather than sending an empty one.
        $deny = ReactorProtocol::buildReply(self::subkey(), $event, ReactorAnswer::deny(), self::REPLY_NONCE, $now);
        self::assertStringNotContainsString('reason', $deny);
        self::assertStringContainsString('"decision":"deny"', $deny);

        // hmac_signature is present-and-null while signing and present-and-set on
        // the wire; it is never omitted in either state.
        self::assertStringContainsString('"hmac_signature":"', $allow);
    }

    /**
     * §22.13's `nonce_binding` pair: two replies differing in nothing but the
     * nonce carry different MACs, because the nonce is inside the signed bytes.
     *
     * The server keeps no durable nonce-dedup store for replies, so this is the
     * property that keeps two replies from being byte-identical — which is what
     * makes a captured reply distinguishable from a fresh one.
     */
    public function testReplyNonceBinding(): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string, nonce_binding: array{nonce_a: string, nonce_b: string, hmac_a_hex: string, hmac_b_hex: string}} $v */
        $v = self::vectors();
        $now = self::now();
        $event = self::eventFor($v['tenant_id'], ReactorEvents::LOGIN_POST_AUTH, $v['expected_correlation_id'], $now);
        $binding = $v['nonce_binding'];

        self::assertNotSame($binding['hmac_a_hex'], $binding['hmac_b_hex'], 'fixture bug: the pair must differ');

        $a = ReactorProtocol::buildReply(self::subkey(), $event, ReactorAnswer::allow(), $binding['nonce_a'], $now);
        $b = ReactorProtocol::buildReply(self::subkey(), $event, ReactorAnswer::allow(), $binding['nonce_b'], $now);

        self::assertStringContainsString($binding['hmac_a_hex'], $a);
        self::assertStringContainsString($binding['hmac_b_hex'], $b);
    }

    /**
     * §22.13's replay vector, from the side an SDK actually owns.
     *
     * The server refuses `correlation_replay` as `wrong_correlation`: identical
     * bytes, valid signature, inside the freshness window, presented against a
     * different in-flight event. What an SDK must guarantee for that check to mean
     * anything is that it copies `correlation_id` from the EVENT BODY into the
     * REPLY BODY — copying it only into the AMQP property produces a reply the
     * server discards (§22.1).
     */
    public function testCorrelationIsCopiedFromTheEventBody(): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string, rejected_replies: array{correlation_replay: array{canonical_signed_json: string, hmac_signature_hex: string, verify_against_correlation_id: string, expected_rejection: string}}} $v */
        $v = self::vectors();
        $now = self::now();
        $vector = $v['rejected_replies']['correlation_replay'];

        self::assertSame('wrong_correlation', $vector['expected_rejection']);
        self::assertNotSame($v['expected_correlation_id'], $vector['verify_against_correlation_id']);
        self::assertStringNotContainsString(
            $vector['verify_against_correlation_id'],
            $vector['canonical_signed_json'],
            'fixture bug: the replayed reply must not already name the correlation it is presented against',
        );

        $other = self::eventFor(
            $v['tenant_id'],
            ReactorEvents::LOGIN_POST_AUTH,
            $vector['verify_against_correlation_id'],
            $now,
        );
        $body = ReactorProtocol::buildReply(self::subkey(), $other, ReactorAnswer::allow(), self::REPLY_NONCE, $now);

        self::assertStringContainsString(
            '"correlation_id":"' . $vector['verify_against_correlation_id'] . '"',
            $body,
        );
        self::assertStringNotContainsString($v['expected_correlation_id'], $body);
    }

    /**
     * The two answers this SDK refuses to put on the wire, and the one it
     * deliberately does not.
     */
    public function testReplyConstructionRules(): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string} $v */
        $v = self::vectors();
        $now = self::now();

        // require_mfa is login.post_auth only (§22.4 row 7) — refused here rather
        // than sent, because rejecting names the author's mistake where it was made.
        $tokenEvent = self::eventFor($v['tenant_id'], ReactorEvents::TOKEN_PRE_ISSUE, $v['expected_correlation_id'], $now);
        try {
            ReactorProtocol::buildReply(self::subkey(), $tokenEvent, ReactorAnswer::allowWithStepUp(), self::REPLY_NONCE, $now);
            self::fail('require_mfa on a non-login event must be refused');
        } catch (ReactorRejection $rejection) {
            self::assertSame(ReactorRejection::REQUIRE_MFA_NOT_SUPPORTED, $rejection->reason());
        }

        // mutate with an empty patch is malformed_mutation server-side; there is
        // nothing to gain by putting it on the wire.
        try {
            ReactorProtocol::buildReply(self::subkey(), $tokenEvent, ReactorAnswer::mutate([]), self::REPLY_NONCE, $now);
            self::fail('a mutate answer with no patch must be refused');
        } catch (ReactorRejection $rejection) {
            self::assertSame(ReactorRejection::MALFORMED_MUTATION, $rejection->reason());
        }

        // A mutation containing a FORBIDDEN key is sent UNFILTERED (§22.4 rule 1).
        // The SDK must not silently drop `sub` from a token.pre_issue patch: doing
        // so would leave the author believing a field was set when it was dropped.
        $body = ReactorProtocol::buildReply(
            self::subkey(),
            $tokenEvent,
            ReactorAnswer::mutate(['ext.department' => 'eng', 'sub' => 'root']),
            self::REPLY_NONCE,
            $now,
        );
        self::assertStringContainsString('"sub":"root"', $body);
        self::assertStringContainsString('"decision":"mutate"', $body);

        // And a mutation is never spelled as allow + patch: the allow constructors
        // take no patch at all, so the illegal reply has no representation.
        self::assertNull(ReactorAnswer::allow()->patch());
        self::assertNull(ReactorAnswer::allowWithStepUp()->patch());
        self::assertSame(ReactorAnswer::ALLOW, ReactorAnswer::allowWithStepUp()->decision());
        self::assertTrue(ReactorAnswer::allowWithStepUp()->requireMfa());
        self::assertSame('denied by reactor', ReactorAnswer::DEFAULT_DENY_REASON);
    }

    /**
     * The forbidden-patch and veto-only reply vectors are the server's rejections,
     * not the SDK's: this SDK signs them exactly as committed, which is what makes
     * the server's audit record name the offending key.
     */
    public function testForbiddenAndVetoOnlyVectorsAreReproducedByteForByte(): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string, rejected_replies: array<string, array{canonical_signed_json: string, hmac_signature_hex: string, expected_rejection: string}>} $v */
        $v = self::vectors();
        $now = self::now();

        $forbidden = $v['rejected_replies']['forbidden_patch_field'];
        self::assertSame('forbidden_patch_field:sub', $forbidden['expected_rejection']);
        self::assertSame(
            self::wireBody($forbidden),
            ReactorProtocol::buildReply(
                self::subkey(),
                self::eventFor($v['tenant_id'], ReactorEvents::TOKEN_PRE_ISSUE, $v['expected_correlation_id'], $now),
                ReactorAnswer::mutate(['ext.department' => 'eng', 'sub' => 'root']),
                self::REPLY_NONCE,
                $now,
            ),
        );

        $vetoOnly = $v['rejected_replies']['mutation_on_veto_only_event'];
        self::assertSame('not_mutable', $vetoOnly['expected_rejection']);
        self::assertSame(
            self::wireBody($vetoOnly),
            ReactorProtocol::buildReply(
                self::subkey(),
                self::eventFor($v['tenant_id'], ReactorEvents::GRANT_PRE_ASSIGN, $v['expected_correlation_id'], $now),
                ReactorAnswer::mutate(['role' => 'admin']),
                self::REPLY_NONCE,
                $now,
            ),
        );
    }

    /**
     * The `stale` and `stale_future` reply vectors are reproduced byte-for-byte
     * too — the same body, signed at a timestamp outside the window, is what the
     * server refuses in either direction.
     */
    public function testStaleReplyVectorsAreReproduced(): void
    {
        /** @var array{tenant_id: string, expected_correlation_id: string, rejected_replies: array<string, array{canonical_signed_json: string, hmac_signature_hex: string, expected_rejection: string}>} $v */
        $v = self::vectors();

        foreach (['stale', 'stale_future'] as $name) {
            $vector = $v['rejected_replies'][$name];
            self::assertSame('stale', $vector['expected_rejection']);

            // The signed issued_at is inside the vector itself; re-sign at exactly
            // that instant to reproduce the committed bytes.
            preg_match('/"issued_at":"([^"]+)"/', $vector['canonical_signed_json'], $matches);
            $signedAt = strtotime($matches[1]);
            self::assertIsInt($signedAt);

            self::assertSame(
                self::wireBody($vector),
                ReactorProtocol::buildReply(
                    self::subkey(),
                    self::eventFor($v['tenant_id'], ReactorEvents::LOGIN_POST_AUTH, $v['expected_correlation_id'], $signedAt),
                    ReactorAnswer::allow(),
                    self::REPLY_NONCE,
                    $signedAt,
                ),
                $name,
            );
        }
    }

    private static function eventFor(string $tenantId, string $eventName, string $correlationId, int $now): ReactorEvent
    {
        return new ReactorEvent(
            tenantId: $tenantId,
            event: $eventName,
            correlationId: $correlationId,
            payload: [],
            timeoutMs: ReactorEvents::DEFAULT_TIMEOUT_MS,
            nonce: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
            issuedAt: $now,
            deadline: $now + 1.0,
        );
    }
}
