<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * One `AssertionConsumerService` endpoint of a service provider. The list of these is an
 * **allow-list**, checked the way OAuth2 redirect URIs are: an `AuthnRequest` naming an ACS
 * URL is honoured only when the URL equals one registered here, byte for byte. No globs, no
 * prefix match.
 */
final class AcsEndpoint implements \JsonSerializable
{
    /**
     * Constructs a AcsEndpoint.
     * @param SamlBinding $binding The binding the endpoint accepts.
     * @param int $index The `index` an `AuthnRequest` may use instead of a URL. Unique per SP.
     * @param string $url The endpoint URL.
     * @param bool|null $isDefault Whether this is the SP's default endpoint. At most one is;
     *     when none is marked, the first listed is the default (SAML Metadata §2.4.4.1).
     *     (optional)
     */
    public function __construct(
        public readonly SamlBinding $binding,
        public readonly int $index,
        public readonly string $url,
        public readonly ?bool $isDefault = null,
    ) {
    }

    /**
     * Rebuilds a AcsEndpoint from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            SamlBinding::fromWire((string) ModelDecode::need($data, 'binding', self::class)),
            (int) ModelDecode::need($data, 'index', self::class),
            (string) ModelDecode::need($data, 'url', self::class),
            isset($data['is_default']) ? (bool) $data['is_default'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['binding'] = $this->binding->value;
        $out['index'] = $this->index;
        $out['url'] = $this->url;
        if ($this->isDefault !== null) {
            $out['is_default'] = $this->isDefault;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
