<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `AssignRoleToServiceAccountRequest` schema from the server's OpenAPI document.
 */
final class AssignRoleToServiceAccountRequest implements \JsonSerializable
{
    /**
     * Constructs a AssignRoleToServiceAccountRequest.
     * @param string $serviceAccountId the server's `service_account_id` field
     * @param string|null $resourceId the server's `resource_id` field (optional)
     * @param list<string>|null $tenantScope The tenants this assignment reaches. Only
     *     meaningful for an assignment made in an organization's scope, whose global roles
     *     otherwise reach every tenant of the organization; naming tenants here confines the
     *     assignment to those and to nothing else, the organization's own scope included. Omitted
     *     — the default — reaches wherever the role does. Refused with 400 outside an organization
     *     scope, when empty, and when it names a tenant of another organization or the
     *     organization's own scope tenant. (optional)
     */
    public function __construct(
        public readonly string $serviceAccountId,
        public readonly ?string $resourceId = null,
        public readonly ?array $tenantScope = null,
    ) {
    }

    /**
     * Rebuilds a AssignRoleToServiceAccountRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'service_account_id', self::class),
            isset($data['resource_id']) ? (string) $data['resource_id'] : null,
            isset($data['tenant_scope']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['tenant_scope'])) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['service_account_id'] = $this->serviceAccountId;
        if ($this->resourceId !== null) {
            $out['resource_id'] = $this->resourceId;
        }
        if ($this->tenantScope !== null && $this->tenantScope !== []) {
            $out['tenant_scope'] = $this->tenantScope;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
