<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * One entry of an SP's attribute mapping table.
 */
final class AttributeMapping implements \JsonSerializable
{
    /**
     * Constructs a AttributeMapping.
     * @param string $samlName The `Name` of the emitted `<saml:Attribute>`. Unique within one
     *     SP, compared exactly (SAML attribute names are case-sensitive).
     * @param AttributeSource $source Where the value comes from.
     * @param string|null $nameFormat The `NameFormat`, one of [`ATTRIBUTE_NAME_FORMATS`].
     *     `None` leaves the attribute unqualified (`unspecified`). (optional)
     */
    public function __construct(
        public readonly string $samlName,
        public readonly AttributeSource $source,
        public readonly ?string $nameFormat = null,
    ) {
    }

    /**
     * Rebuilds a AttributeMapping from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'saml_name', self::class),
            AttributeSource::fromWire((string) ModelDecode::need($data, 'source', self::class)),
            isset($data['name_format']) ? (string) $data['name_format'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['saml_name'] = $this->samlName;
        $out['source'] = $this->source->value;
        if ($this->nameFormat !== null) {
            $out['name_format'] = $this->nameFormat;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
