<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A CA (Certificate Authority) certificate at the organization level. CA certificates are the
 * root of trust for all tenant certificates within the organization. Private keys for signing
 * CAs are encrypted with AES-256-GCM and stored separately; non-signing CAs only store the
 * public certificate.
 */
final class CaCertificate implements \JsonSerializable
{
    /**
     * Constructs a CaCertificate.
     * @param string $createdAt the server's `created_at` field
     * @param string $fingerprint SHA-256 fingerprint of the certificate.
     * @param string $id the server's `id` field
     * @param KeyAlgorithm $keyAlgorithm the server's `key_algorithm` field
     * @param string $notAfter Validity end.
     * @param string $notBefore Validity start.
     * @param string $organizationId The organization this CA belongs to.
     * @param string $publicCertPem PEM-encoded public certificate. The certificate that
     *     *signs*, which under `vault_pki` custody is the intermediate rather than the root
     *     beneath which it was created.
     * @param CertificateStatus $status the server's `status` field
     * @param string $subject The certificate subject (e.g., `CN=ACME Corp Root CA`).
     * @param string|null $chainPem The issuers above [`Self::public_cert_pem`], concatenated
     *     PEM, nearest issuer first and the root last. `None` for a CA that is its own root, which
     *     is every CA AXIAM generated before Vault's PKI engine was an option. Present for a
     *     `vault_pki` CA, where it is the only copy of the root certificate anything outside Vault
     *     will ever see — a relying party cannot validate an AXIAM-issued leaf without it, and
     *     `root/generate/internal` returns it exactly once. (optional)
     * @param string|null $keyCustody Which custodian holds this CA's signing key. Recorded per
     *     CA rather than read from configuration, so adopting a new custodian does not strand the
     *     CAs that already exist. Not secret — an operator needs to see it, and it discloses only
     *     where a key is kept. (optional)
     * @param string|null $keyLocator Where the custodian put the key. A Vault path under its
     *     mount; `None` for database custody, whose locator is the row itself. (optional)
     * @param bool|null $mtlsTrustAnchor Whether this CA is offered as a trust anchor for
     *     mutual TLS. When set, the server exports this CA's **public** certificate to the bundle
     *     named by `AXIAM__SERVER__TLS__CLIENT_CA_BUNDLE_PATH` at startup and turns
     *     client-certificate authentication on (`optional`) if the operator has not configured it
     *     explicitly. A client presenting a certificate that chains to this CA is then verified by
     *     the TLS layer itself, which is what `axiam_pki::mtls` needs to authenticate an IoT
     *     device or a service account by certificate rather than by secret. # What is and is not
     *     copied Only `public_cert_pem` — the certificate. The **private key stays where its
     *     custodian put it** (Vault, or sealed into the row) and is never written to the server
     *     volume. A trust anchor is public by construction: it is what the server hands every
     *     client during the TLS handshake, and every device that has to validate the chain already
     *     holds a copy. # Why a restart rustls builds its `RootCertStore` once, when the listener
     *     is constructed, and actix-web binds that config for the process's life. Toggling this
     *     changes what the *next* boot trusts, and the API says so in its response rather than
     *     pretending the change took effect. Defaults to `false`, so a deployment that never
     *     touches this keeps exactly the TLS posture it has today. (optional)
     * @param string|null $parentCaId The CA in this organization that signed this one. `None`
     *     for an organization-level CA, which is either self-signed or imported and has no parent
     *     inside AXIAM. (optional)
     * @param string|null $tenantId The tenant this CA signs for, when it is a tenant signing
     *     CA. `None` for an organization-level CA — the trust anchor, and the only kind that
     *     existed before tenant signing CAs. `Some` for an intermediate created under one, which
     *     exists so a tenant's user, service and device certificates chain through a CA that can
     *     be revoked and replaced without touching the anchor the rest of the estate trusts.
     *     (optional)
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $fingerprint,
        public readonly string $id,
        public readonly KeyAlgorithm $keyAlgorithm,
        public readonly string $notAfter,
        public readonly string $notBefore,
        public readonly string $organizationId,
        public readonly string $publicCertPem,
        public readonly CertificateStatus $status,
        public readonly string $subject,
        public readonly ?string $chainPem = null,
        public readonly ?string $keyCustody = null,
        public readonly ?string $keyLocator = null,
        public readonly ?bool $mtlsTrustAnchor = null,
        public readonly ?string $parentCaId = null,
        public readonly ?string $tenantId = null,
    ) {
    }

    /**
     * Rebuilds a CaCertificate from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['created_at'],
            (string) $data['fingerprint'],
            (string) $data['id'],
            KeyAlgorithm::fromWire((string) $data['key_algorithm']),
            (string) $data['not_after'],
            (string) $data['not_before'],
            (string) $data['organization_id'],
            (string) $data['public_cert_pem'],
            CertificateStatus::fromWire((string) $data['status']),
            (string) $data['subject'],
            isset($data['chain_pem']) ? (string) $data['chain_pem'] : null,
            isset($data['key_custody']) ? (string) $data['key_custody'] : null,
            isset($data['key_locator']) ? (string) $data['key_locator'] : null,
            isset($data['mtls_trust_anchor']) ? (bool) $data['mtls_trust_anchor'] : null,
            isset($data['parent_ca_id']) ? (string) $data['parent_ca_id'] : null,
            isset($data['tenant_id']) ? (string) $data['tenant_id'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['fingerprint'] = $this->fingerprint;
        $out['id'] = $this->id;
        $out['key_algorithm'] = $this->keyAlgorithm->value;
        $out['not_after'] = $this->notAfter;
        $out['not_before'] = $this->notBefore;
        $out['organization_id'] = $this->organizationId;
        $out['public_cert_pem'] = $this->publicCertPem;
        $out['status'] = $this->status->value;
        $out['subject'] = $this->subject;
        if ($this->chainPem !== null) {
            $out['chain_pem'] = $this->chainPem;
        }
        if ($this->keyCustody !== null) {
            $out['key_custody'] = $this->keyCustody;
        }
        if ($this->keyLocator !== null) {
            $out['key_locator'] = $this->keyLocator;
        }
        if ($this->mtlsTrustAnchor !== null) {
            $out['mtls_trust_anchor'] = $this->mtlsTrustAnchor;
        }
        if ($this->parentCaId !== null) {
            $out['parent_ca_id'] = $this->parentCaId;
        }
        if ($this->tenantId !== null) {
            $out['tenant_id'] = $this->tenantId;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
