<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A tenant-level certificate for users, services, or IoT devices. Certificates are signed by
 * the organization's CA. The private key is returned once on generation and never stored by
 * AXIAM.
 */
final class Certificate implements \JsonSerializable
{
    /**
     * Constructs a Certificate.
     * @param CertificateType $certType the server's `cert_type` field
     * @param string $createdAt the server's `created_at` field
     * @param string $fingerprint SHA-256 fingerprint of the certificate.
     * @param string $id the server's `id` field
     * @param string $issuerCaId The CA certificate that signed this certificate.
     * @param KeyAlgorithm $keyAlgorithm the server's `key_algorithm` field
     * @param mixed $metadata Arbitrary key-value metadata (e.g., device serial, user ID
     *     binding).
     * @param string $notAfter Validity end.
     * @param string $notBefore Validity start.
     * @param string $publicCertPem PEM-encoded public certificate.
     * @param CertificateStatus $status the server's `status` field
     * @param string $subject The certificate subject (e.g., `CN=device-001`).
     * @param string $tenantId The tenant this certificate belongs to.
     * @param string|null $boundServiceAccountId Resolved by the list projection only. The
     *     server resolves this for a whole page in one query, so it is populated by `list` and is
     *     `null` on `get` (CONTRACT.md §27.11 rule 4). `null` there means "this read does not
     *     carry it", not "there is nothing bound" — this SDK does not issue a second request to
     *     fill it in. (optional)
     */
    public function __construct(
        public readonly CertificateType $certType,
        public readonly string $createdAt,
        public readonly string $fingerprint,
        public readonly string $id,
        public readonly string $issuerCaId,
        public readonly KeyAlgorithm $keyAlgorithm,
        public readonly mixed $metadata,
        public readonly string $notAfter,
        public readonly string $notBefore,
        public readonly string $publicCertPem,
        public readonly CertificateStatus $status,
        public readonly string $subject,
        public readonly string $tenantId,
        public readonly ?string $boundServiceAccountId = null,
    ) {
    }

    /**
     * Rebuilds a Certificate from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            CertificateType::fromWire((string) ModelDecode::need($data, 'cert_type', self::class)),
            (string) ModelDecode::need($data, 'created_at', self::class),
            (string) ModelDecode::need($data, 'fingerprint', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            (string) ModelDecode::need($data, 'issuer_ca_id', self::class),
            KeyAlgorithm::fromWire((string) ModelDecode::need($data, 'key_algorithm', self::class)),
            ModelDecode::need($data, 'metadata', self::class),
            (string) ModelDecode::need($data, 'not_after', self::class),
            (string) ModelDecode::need($data, 'not_before', self::class),
            (string) ModelDecode::need($data, 'public_cert_pem', self::class),
            CertificateStatus::fromWire((string) ModelDecode::need($data, 'status', self::class)),
            (string) ModelDecode::need($data, 'subject', self::class),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            isset($data['bound_service_account_id']) ? (string) $data['bound_service_account_id'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['cert_type'] = $this->certType->value;
        $out['created_at'] = $this->createdAt;
        $out['fingerprint'] = $this->fingerprint;
        $out['id'] = $this->id;
        $out['issuer_ca_id'] = $this->issuerCaId;
        $out['key_algorithm'] = $this->keyAlgorithm->value;
        $out['metadata'] = $this->metadata;
        $out['not_after'] = $this->notAfter;
        $out['not_before'] = $this->notBefore;
        $out['public_cert_pem'] = $this->publicCertPem;
        $out['status'] = $this->status->value;
        $out['subject'] = $this->subject;
        $out['tenant_id'] = $this->tenantId;
        if ($this->boundServiceAccountId !== null) {
            $out['bound_service_account_id'] = $this->boundServiceAccountId;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
