<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Certificate issuance constraints.
 */
final class CertificatePolicy implements \JsonSerializable
{
    /**
     * Constructs a CertificatePolicy.
     * @param int $defaultCertValidityDays the server's `default_cert_validity_days` field
     * @param int $maxCertValidityDays the server's `max_cert_validity_days` field
     * @param list<string>|null $serverCertAllowedNames The names a `Server` certificate may be
     *     issued for (S-7, DF-001): DNS suffixes (`.lakeside.internal`, strictly below), exact
     *     hosts (`lakeside.internal`) and IP prefixes (`10.0.0.0/8`, `fd00::/8`). See
     *     [`crate::models::server_names`] for the matching rules. **Empty by default, and empty
     *     refuses every `Server` request** (I1). A certificate for a name, signed under the
     *     organization root, is trusted by every relying party that trusts that root, so the list
     *     is written where the root is owned. A tenant override may only remove an entry or narrow
     *     one; when the baseline later shrinks, the tenant's effective list is the intersection of
     *     the two. (optional)
     */
    public function __construct(
        public readonly int $defaultCertValidityDays,
        public readonly int $maxCertValidityDays,
        public readonly ?array $serverCertAllowedNames = null,
    ) {
    }

    /**
     * Rebuilds a CertificatePolicy from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (int) ModelDecode::need($data, 'default_cert_validity_days', self::class),
            (int) ModelDecode::need($data, 'max_cert_validity_days', self::class),
            isset($data['server_cert_allowed_names']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['server_cert_allowed_names'])) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['default_cert_validity_days'] = $this->defaultCertValidityDays;
        $out['max_cert_validity_days'] = $this->maxCertValidityDays;
        if ($this->serverCertAllowedNames !== null) {
            $out['server_cert_allowed_names'] = $this->serverCertAllowedNames;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
