<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * How a client proves its identity at the token endpoint (RFC 8705 §2, OIDC Core §9 naming).
 * Only the methods AXIAM actually implements are representable. `None` — the public-client
 * value — was deliberately absent until T21.2: adding it before the rest of the server
 * understood one would have let an operator register a client whose authentication is silently
 * skipped. The server understands one now (`token.rs`'s `authenticate_client_credential` has
 * an arm that accepts *no* credential and refuses a presented one, the authorization endpoint
 * derives its PKCE requirement from this enum, and the admin API refuses the method alongside
 * any grant or binding that contradicts it), so the variant exists — and only that arm may
 * ever treat a missing credential as success.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * `self::Unknown` rather than failing the response it arrived in (CONTRACT.md §27.11 rule 1).
 * Its own wire spelling is the empty string, which no server value is, so carrying an
 * unrecognised value back into an update is refused by the server rather than written as a
 * spelling it never used. A `match` over these cases needs an `Unknown` arm.
 */
enum ClientAuthMethod: string
{
    /** The wire value `client_secret_post`. */
    case ClientSecretPost = 'client_secret_post';

    /** The wire value `client_secret_basic`. */
    case ClientSecretBasic = 'client_secret_basic';

    /** The wire value `tls_client_auth`. */
    case TlsClientAuth = 'tls_client_auth';

    /** The wire value `self_signed_tls_client_auth`. */
    case SelfSignedTlsClientAuth = 'self_signed_tls_client_auth';

    /** The wire value `private_key_jwt`. */
    case PrivateKeyJwt = 'private_key_jwt';

    /** The wire value `none`. */
    case None = 'none';

    /** A value this SDK's copy of the spec does not list; see the type's summary. */
    case Unknown = '';

    /**
     * Parses a wire value into a ClientAuthMethod, mapping an unrecognised one to {@see
     * self::Unknown}.
     *
     * Never throws. A parse error here would fail the whole response the value arrived in, so
     * one unrecognised field of one record would take down the page it was on (§27.11 rule 1).
     * A `match` over this enum needs an `Unknown` arm.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? self::Unknown;
    }
}
