<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Which security posture a client is registered under (X5.1). This is the FAPI "one switch".
 * FAPI 2.0 is not a single feature but a bundle of constraints — mandatory PAR, mandatory PKCE
 * with `S256`, mandatory strong client authentication, mandatory sender-constrained tokens,
 * and a refusal of every relaxation the base specs permit. Encoding them as one profile rather
 * than a dozen independent booleans means an operator cannot register a client that is
 * *nearly* FAPI, and a reviewer can answer "is this client financial-grade?" by reading one
 * field. The same philosophy as the rate-limit postures: ordinary clients see no behaviour
 * change at all, because [`Standard`](Self::Standard) is the serde default and every row
 * written before schema v38 decodes to it.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * `self::Unknown` rather than failing the response it arrived in (CONTRACT.md §27.11 rule 1).
 * Its own wire spelling is the empty string, which no server value is, so carrying an
 * unrecognised value back into an update is refused by the server rather than written as a
 * spelling it never used. A `match` over these cases needs an `Unknown` arm.
 */
enum ClientProfile: string
{
    /** The wire value `standard`. */
    case Standard = 'standard';

    /** The wire value `fapi2`. */
    case Fapi2 = 'fapi2';

    /** A value this SDK's copy of the spec does not list; see the type's summary. */
    case Unknown = '';

    /**
     * Parses a wire value into a ClientProfile, mapping an unrecognised one to {@see
     * self::Unknown}.
     *
     * Never throws. A parse error here would fail the whole response the value arrived in, so
     * one unrecognised field of one record would take down the page it was on (§27.11 rule 1).
     * A `match` over this enum needs an `Unknown` arm.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? self::Unknown;
    }
}
