<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Which security posture a client is registered under (X5.1). This is the FAPI "one switch".
 * FAPI 2.0 is not a single feature but a bundle of constraints — mandatory PAR, mandatory PKCE
 * with `S256`, mandatory strong client authentication, mandatory sender-constrained tokens,
 * and a refusal of every relaxation the base specs permit. Encoding them as one profile rather
 * than a dozen independent booleans means an operator cannot register a client that is
 * *nearly* FAPI, and a reviewer can answer "is this client financial-grade?" by reading one
 * field. The same philosophy as the rate-limit postures: ordinary clients see no behaviour
 * change at all, because [`Standard`](Self::Standard) is the serde default and every row
 * written before schema v38 decodes to it.
 */
enum ClientProfile: string
{
    /** The wire value `standard`. */
    case Standard = 'standard';

    /** The wire value `fapi2`. */
    case Fapi2 = 'fapi2';

    /**
     * Parses a wire value into a ClientProfile.
     *
     * Throws on an unrecognised value rather than defaulting to a case: a server that has
     * learned a new state should surface as a loud error, not as whichever case was declared
     * first.
     * @throws \Axiam\Sdk\Core\AxiamException when `$value` is not a known case.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? throw new \Axiam\Sdk\Core\AxiamException(
            sprintf('unknown ClientProfile value "%s" — the server may be newer than this SDK', $value),
        );
    }
}
