<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `CreateFederationConfigRequest` schema from the server's OpenAPI document.
 */
final class CreateFederationConfigRequest implements \JsonSerializable
{
    /**
     * Constructs a CreateFederationConfigRequest.
     * @param string $clientId OAuth2 client ID registered with the external IdP.
     * @param \Axiam\Sdk\Core\Sensitive $clientSecret OAuth2 client secret registered with the
     *     external IdP.
     * @param string $protocol Federation protocol: "OidcConnect" or "Saml".
     * @param string $provider Display name for the identity provider (e.g., "Google", "Okta").
     * @param list<string>|null $allowedAlgorithms Accepted JWT signing algorithms (OIDC) or
     *     signature algorithms (SAML). Defaults to `["RS256"]` when not provided (CQ-B40/REQ-14
     *     AC-5). (optional)
     * @param mixed $attributeMap Maps external IdP attributes to AXIAM user fields. (optional)
     * @param string|null $idpSigningCertPem PEM-encoded X.509 certificate for verifying SAML
     *     assertions or OIDC signatures (CQ-B40/REQ-14 AC-5). Required for SAML configs.
     *     (optional)
     * @param string|null $metadataUrl OIDC discovery URL or SAML metadata URL. (optional)
     * @param TokenExchangeTrustRequest|null $tokenExchange the server's `token_exchange` field
     *     (optional)
     */
    public function __construct(
        public readonly string $clientId,
        public readonly \Axiam\Sdk\Core\Sensitive $clientSecret,
        public readonly string $protocol,
        public readonly string $provider,
        public readonly ?array $allowedAlgorithms = null,
        public readonly mixed $attributeMap = null,
        public readonly ?string $idpSigningCertPem = null,
        public readonly ?string $metadataUrl = null,
        public readonly ?TokenExchangeTrustRequest $tokenExchange = null,
    ) {
    }

    /**
     * Rebuilds a CreateFederationConfigRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['client_id'],
            new \Axiam\Sdk\Core\Sensitive((string) $data['client_secret']),
            (string) $data['protocol'],
            (string) $data['provider'],
            isset($data['allowed_algorithms']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['allowed_algorithms'])) : null,
            isset($data['attribute_map']) ? $data['attribute_map'] : null,
            isset($data['idp_signing_cert_pem']) ? (string) $data['idp_signing_cert_pem'] : null,
            isset($data['metadata_url']) ? (string) $data['metadata_url'] : null,
            isset($data['token_exchange']) ? TokenExchangeTrustRequest::fromArray((array) $data['token_exchange']) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['client_id'] = $this->clientId;
        $out['client_secret'] = $this->clientSecret;
        $out['protocol'] = $this->protocol;
        $out['provider'] = $this->provider;
        if ($this->allowedAlgorithms !== null) {
            $out['allowed_algorithms'] = $this->allowedAlgorithms;
        }
        if ($this->attributeMap !== null) {
            $out['attribute_map'] = $this->attributeMap;
        }
        if ($this->idpSigningCertPem !== null) {
            $out['idp_signing_cert_pem'] = $this->idpSigningCertPem;
        }
        if ($this->metadataUrl !== null) {
            $out['metadata_url'] = $this->metadataUrl;
        }
        if ($this->tokenExchange !== null) {
            $out['token_exchange'] = $this->tokenExchange->toArray();
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
