<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `CreateReactorRequest` schema from the server's OpenAPI document.
 */
final class CreateReactorRequest implements \JsonSerializable
{
    /**
     * Constructs a CreateReactorRequest.
     * @param list<string> $events Event names from the registry (`GET
     *     /api/v1/reactors/events`).
     * @param ReactorMode $mode the server's `mode` field
     * @param string $name the server's `name` field
     * @param string|null $description the server's `description` field (optional)
     * @param bool|null $enabled the server's `enabled` field (optional)
     * @param FailurePolicy|null $failurePolicy the server's `failure_policy` field (optional)
     * @param int|null $priority the server's `priority` field (optional)
     * @param int|null $timeoutMs Omit to take the 500 ms default. Capped at 5 000 ms.
     *     (optional)
     */
    public function __construct(
        public readonly array $events,
        public readonly ReactorMode $mode,
        public readonly string $name,
        public readonly ?string $description = null,
        public readonly ?bool $enabled = null,
        public readonly ?FailurePolicy $failurePolicy = null,
        public readonly ?int $priority = null,
        public readonly ?int $timeoutMs = null,
    ) {
    }

    /**
     * Rebuilds a CreateReactorRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) ModelDecode::need($data, 'events', self::class))),
            ReactorMode::fromWire((string) ModelDecode::need($data, 'mode', self::class)),
            (string) ModelDecode::need($data, 'name', self::class),
            isset($data['description']) ? (string) $data['description'] : null,
            isset($data['enabled']) ? (bool) $data['enabled'] : null,
            isset($data['failure_policy']) ? FailurePolicy::fromWire((string) $data['failure_policy']) : null,
            isset($data['priority']) ? (int) $data['priority'] : null,
            isset($data['timeout_ms']) ? (int) $data['timeout_ms'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['events'] = $this->events;
        $out['mode'] = $this->mode->value;
        $out['name'] = $this->name;
        if ($this->description !== null) {
            $out['description'] = $this->description;
        }
        if ($this->enabled !== null) {
            $out['enabled'] = $this->enabled;
        }
        if ($this->failurePolicy !== null) {
            $out['failure_policy'] = $this->failurePolicy->value;
        }
        if ($this->priority !== null) {
            $out['priority'] = $this->priority;
        }
        if ($this->timeoutMs !== null) {
            $out['timeout_ms'] = $this->timeoutMs;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
