<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The one-time reveal. Same shape as service-account creation: the secret is returned once and
 * only its hash is kept.
 */
final class CreateScimTokenResponse implements \JsonSerializable
{
    /**
     * Constructs a CreateScimTokenResponse.
     * @param string $createdAt the server's `created_at` field
     * @param string $createdBy the server's `created_by` field
     * @param string $expiresAt the server's `expires_at` field
     * @param string $id the server's `id` field
     * @param string $name the server's `name` field
     * @param ScimTokenStatus $status the server's `status` field
     * @param string $tenantId the server's `tenant_id` field
     * @param string $userId the server's `user_id` field
     * @param \Axiam\Sdk\Core\Sensitive $provisioningToken The plaintext handle — shown once,
     *     never retrievable again.
     * @param string|null $lastUsedAt the server's `last_used_at` field (optional)
     * @param string|null $revokedAt the server's `revoked_at` field (optional)
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $createdBy,
        public readonly string $expiresAt,
        public readonly string $id,
        public readonly string $name,
        public readonly ScimTokenStatus $status,
        public readonly string $tenantId,
        public readonly string $userId,
        public readonly \Axiam\Sdk\Core\Sensitive $provisioningToken,
        public readonly ?string $lastUsedAt = null,
        public readonly ?string $revokedAt = null,
    ) {
    }

    /**
     * Rebuilds a CreateScimTokenResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'created_at', self::class),
            (string) ModelDecode::need($data, 'created_by', self::class),
            (string) ModelDecode::need($data, 'expires_at', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            (string) ModelDecode::need($data, 'name', self::class),
            ScimTokenStatus::fromWire((string) ModelDecode::need($data, 'status', self::class)),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            (string) ModelDecode::need($data, 'user_id', self::class),
            new \Axiam\Sdk\Core\Sensitive((string) ModelDecode::need($data, 'provisioning_token', self::class)),
            isset($data['last_used_at']) ? (string) $data['last_used_at'] : null,
            isset($data['revoked_at']) ? (string) $data['revoked_at'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['created_by'] = $this->createdBy;
        $out['expires_at'] = $this->expiresAt;
        $out['id'] = $this->id;
        $out['name'] = $this->name;
        $out['status'] = $this->status->value;
        $out['tenant_id'] = $this->tenantId;
        $out['user_id'] = $this->userId;
        $out['provisioning_token'] = $this->provisioningToken;
        if ($this->lastUsedAt !== null) {
            $out['last_used_at'] = $this->lastUsedAt;
        }
        if ($this->revokedAt !== null) {
            $out['revoked_at'] = $this->revokedAt;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
