<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `CreateCertificateRequest` schema from the server's OpenAPI document.
 */
final class CreateCertificateRequest implements \JsonSerializable
{
    /**
     * Constructs a CreateCertificateRequest.
     * @param CertificateType $certType the server's `cert_type` field
     * @param string $issuerCaId the server's `issuer_ca_id` field
     * @param KeyAlgorithm $keyAlgorithm the server's `key_algorithm` field
     * @param string $subject the server's `subject` field
     * @param int $validityDays Validity duration in days.
     * @param mixed $metadata the server's `metadata` field (optional)
     */
    public function __construct(
        public readonly CertificateType $certType,
        public readonly string $issuerCaId,
        public readonly KeyAlgorithm $keyAlgorithm,
        public readonly string $subject,
        public readonly int $validityDays,
        public readonly mixed $metadata = null,
    ) {
    }

    /**
     * Rebuilds a CreateCertificateRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            CertificateType::fromWire((string) $data['cert_type']),
            (string) $data['issuer_ca_id'],
            KeyAlgorithm::fromWire((string) $data['key_algorithm']),
            (string) $data['subject'],
            (int) $data['validity_days'],
            isset($data['metadata']) ? $data['metadata'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['cert_type'] = $this->certType->value;
        $out['issuer_ca_id'] = $this->issuerCaId;
        $out['key_algorithm'] = $this->keyAlgorithm->value;
        $out['subject'] = $this->subject;
        $out['validity_days'] = $this->validityDays;
        if ($this->metadata !== null) {
            $out['metadata'] = $this->metadata;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
