<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A read-only view of the sync job's state for one tenant. Counts of what a run did are in its
 * audit rows, and no account id is here.
 */
final class DirectorySyncStatus implements \JsonSerializable
{
    /**
     * Constructs a DirectorySyncStatus.
     * @param bool $fullRequired The next run must be a full reconciliation.
     * @param bool $hasWatermark An incremental run has a starting point.
     * @param string|null $lastAttemptAt When the last attempt started, or null before the
     *     first run. (optional)
     * @param string|null $lastFullRunAt When the last complete full run finished, or null.
     *     (optional)
     * @param string|null $lastResult `ok`, `partial`, `failed` or `safety_valve` (an open set:
     *     decode another value without failing), or null before the first run. (optional)
     */
    public function __construct(
        public readonly bool $fullRequired,
        public readonly bool $hasWatermark,
        public readonly ?string $lastAttemptAt = null,
        public readonly ?string $lastFullRunAt = null,
        public readonly ?string $lastResult = null,
    ) {
    }

    /**
     * Rebuilds a DirectorySyncStatus from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (bool) ModelDecode::need($data, 'full_required', self::class),
            (bool) ModelDecode::need($data, 'has_watermark', self::class),
            isset($data['last_attempt_at']) ? (string) $data['last_attempt_at'] : null,
            isset($data['last_full_run_at']) ? (string) $data['last_full_run_at'] : null,
            isset($data['last_result']) ? (string) $data['last_result'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['full_required'] = $this->fullRequired;
        $out['has_watermark'] = $this->hasWatermark;
        if ($this->lastAttemptAt !== null) {
            $out['last_attempt_at'] = $this->lastAttemptAt;
        }
        if ($this->lastFullRunAt !== null) {
            $out['last_full_run_at'] = $this->lastFullRunAt;
        }
        if ($this->lastResult !== null) {
            $out['last_result'] = $this->lastResult;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
