<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A tenant's directory configuration, as stored and as read back. Carries no secret: see the
 * module documentation.
 */
final class DirectoryConfig implements \JsonSerializable
{
    /**
     * Constructs a DirectoryConfig.
     * @param string $baseDn Where users are searched for.
     * @param string $bindDn The service account AXIAM binds as to search. It should hold
     *     read-only rights: AXIAM never writes to a directory.
     * @param string $createdAt When the row was created.
     * @param bool $enabled Whether the directory is used for sign-in and sync.
     * @param list<GroupMapping> $groupMappings The group-mapping table (D-30): which directory
     *     groups put a user into which AXIAM groups. Empty means no directory group maps to
     *     anything, and a sign-in then removes every directory-sourced membership the user held.
     * @param string $groupMemberAttribute `memberOf` (user-side, AD) or `member` (group-side,
     *     OpenLDAP).
     * @param int $groupNestingDepth How many levels of nested groups are followed, `0..=10`.
     * @param string $id Row identifier.
     * @param bool $jitProvisioning Provision an AXIAM user on first successful directory
     *     sign-in.
     * @param DirectoryKind $kind The kind of directory, which selects defaults.
     * @param bool $startTls Upgrade an `ldap://` connection with StartTLS before any bind.
     * @param int $syncIntervalSecs Seconds between incremental sync runs.
     * @param string $tenantId The owning tenant. At most one configuration exists per tenant.
     * @param list<string> $trustAnchorsPem PEM CA certificates that anchor trust in the
     *     directory's server certificate. Empty means the platform roots used by the rest of the
     *     workspace's outbound TLS. An organisation CA's PEM can be pasted here.
     * @param string $updatedAt When the row was last written.
     * @param string $url `ldaps://host[:port]` or `ldap://host[:port]` together with
     *     [`Self::start_tls`]. A plaintext URL is refused at configuration time.
     * @param UserAttributeMap $userAttributeMap Which attribute feeds which user field.
     * @param string $userFilter The user-lookup filter template. It contains exactly one
     *     `{username}` placeholder, which the bind path replaces with the RFC 4515-escaped login
     *     name; the template itself is never formatted with raw input.
     * @param string|null $groupBaseDn Where groups are searched for (reverse-`member` lookups,
     *     group sync). (optional)
     * @param string|null $groupFilter Restricts which entries under [`Self::group_base_dn`]
     *     are groups. (optional)
     */
    public function __construct(
        public readonly string $baseDn,
        public readonly string $bindDn,
        public readonly string $createdAt,
        public readonly bool $enabled,
        public readonly array $groupMappings,
        public readonly string $groupMemberAttribute,
        public readonly int $groupNestingDepth,
        public readonly string $id,
        public readonly bool $jitProvisioning,
        public readonly DirectoryKind $kind,
        public readonly bool $startTls,
        public readonly int $syncIntervalSecs,
        public readonly string $tenantId,
        public readonly array $trustAnchorsPem,
        public readonly string $updatedAt,
        public readonly string $url,
        public readonly UserAttributeMap $userAttributeMap,
        public readonly string $userFilter,
        public readonly ?string $groupBaseDn = null,
        public readonly ?string $groupFilter = null,
    ) {
    }

    /**
     * Rebuilds a DirectoryConfig from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'base_dn', self::class),
            (string) ModelDecode::need($data, 'bind_dn', self::class),
            (string) ModelDecode::need($data, 'created_at', self::class),
            (bool) ModelDecode::need($data, 'enabled', self::class),
            array_values(array_map(static fn (mixed $v): GroupMapping => GroupMapping::fromArray((array) $v), (array) ModelDecode::need($data, 'group_mappings', self::class))),
            (string) ModelDecode::need($data, 'group_member_attribute', self::class),
            (int) ModelDecode::need($data, 'group_nesting_depth', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            (bool) ModelDecode::need($data, 'jit_provisioning', self::class),
            DirectoryKind::fromWire((string) ModelDecode::need($data, 'kind', self::class)),
            (bool) ModelDecode::need($data, 'start_tls', self::class),
            (int) ModelDecode::need($data, 'sync_interval_secs', self::class),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) ModelDecode::need($data, 'trust_anchors_pem', self::class))),
            (string) ModelDecode::need($data, 'updated_at', self::class),
            (string) ModelDecode::need($data, 'url', self::class),
            UserAttributeMap::fromArray((array) ModelDecode::need($data, 'user_attribute_map', self::class)),
            (string) ModelDecode::need($data, 'user_filter', self::class),
            isset($data['group_base_dn']) ? (string) $data['group_base_dn'] : null,
            isset($data['group_filter']) ? (string) $data['group_filter'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['base_dn'] = $this->baseDn;
        $out['bind_dn'] = $this->bindDn;
        $out['created_at'] = $this->createdAt;
        $out['enabled'] = $this->enabled;
        $out['group_mappings'] = array_map(static fn (GroupMapping $v): array => $v->toArray(), $this->groupMappings);
        $out['group_member_attribute'] = $this->groupMemberAttribute;
        $out['group_nesting_depth'] = $this->groupNestingDepth;
        $out['id'] = $this->id;
        $out['jit_provisioning'] = $this->jitProvisioning;
        $out['kind'] = $this->kind->value;
        $out['start_tls'] = $this->startTls;
        $out['sync_interval_secs'] = $this->syncIntervalSecs;
        $out['tenant_id'] = $this->tenantId;
        $out['trust_anchors_pem'] = $this->trustAnchorsPem;
        $out['updated_at'] = $this->updatedAt;
        $out['url'] = $this->url;
        $out['user_attribute_map'] = $this->userAttributeMap->toArray();
        $out['user_filter'] = $this->userFilter;
        if ($this->groupBaseDn !== null) {
            $out['group_base_dn'] = $this->groupBaseDn;
        }
        if ($this->groupFilter !== null) {
            $out['group_filter'] = $this->groupFilter;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
