<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Partial tenant overrides for email configuration. `None` = inherit from org baseline.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left
 * unchanged, and is omitted from the wire request entirely rather than sent as null (§27.4
 * rule 5).
 */
final class EmailConfigOverride implements \JsonSerializable
{
    /**
     * Constructs a EmailConfigOverride.
     * @param bool|null $enabled the server's `enabled` field (optional)
     * @param string|null $fromEmail the server's `from_email` field (optional)
     * @param string|null $fromName the server's `from_name` field (optional)
     * @param ProviderConfigVariant|null $provider the server's `provider` field (optional)
     * @param string|null $replyTo `Some(None)` explicitly clears reply-to; `None` inherits.
     *     (optional)
     */
    public function __construct(
        public readonly ?bool $enabled = null,
        public readonly ?string $fromEmail = null,
        public readonly ?string $fromName = null,
        public readonly ?ProviderConfigVariant $provider = null,
        public readonly ?string $replyTo = null,
    ) {
    }

    /**
     * Rebuilds a EmailConfigOverride from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            isset($data['enabled']) ? (bool) $data['enabled'] : null,
            isset($data['from_email']) ? (string) $data['from_email'] : null,
            isset($data['from_name']) ? (string) $data['from_name'] : null,
            isset($data['provider']) ? ProviderConfig::fromArray((array) $data['provider']) : null,
            isset($data['reply_to']) ? (string) $data['reply_to'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->enabled !== null) {
            $out['enabled'] = $this->enabled;
        }
        if ($this->fromEmail !== null) {
            $out['from_email'] = $this->fromEmail;
        }
        if ($this->fromName !== null) {
            $out['from_name'] = $this->fromName;
        }
        if ($this->provider !== null) {
            $out['provider'] = $this->provider->toArray();
        }
        if ($this->replyTo !== null) {
            $out['reply_to'] = $this->replyTo;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
