<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Email verification requirements.
 */
final class EmailVerificationPolicy implements \JsonSerializable
{
    /**
     * Constructs a EmailVerificationPolicy.
     * @param int $emailVerificationGracePeriodHours the server's
     *     `email_verification_grace_period_hours` field
     * @param bool $emailVerificationRequired the server's `email_verification_required` field
     */
    public function __construct(
        public readonly int $emailVerificationGracePeriodHours,
        public readonly bool $emailVerificationRequired,
    ) {
    }

    /**
     * Rebuilds a EmailVerificationPolicy from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (int) $data['email_verification_grace_period_hours'],
            (bool) $data['email_verification_required'],
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['email_verification_grace_period_hours'] = $this->emailVerificationGracePeriodHours;
        $out['email_verification_required'] = $this->emailVerificationRequired;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
