<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * What a test send did.
 */
final class EmailTestResult implements \JsonSerializable
{
    /**
     * Constructs a EmailTestResult.
     * @param string $provider Which provider the effective configuration resolved to.
     * @param string $to Where the message went — always the caller's own address.
     * @param string|null $messageId The provider's message id, when it returns one. (optional)
     */
    public function __construct(
        public readonly string $provider,
        public readonly string $to,
        public readonly ?string $messageId = null,
    ) {
    }

    /**
     * Rebuilds a EmailTestResult from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'provider', self::class),
            (string) ModelDecode::need($data, 'to', self::class),
            isset($data['message_id']) ? (string) $data['message_id'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['provider'] = $this->provider;
        $out['to'] = $this->to;
        if ($this->messageId !== null) {
            $out['message_id'] = $this->messageId;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
