<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Fully resolved email configuration (all fields present).
 */
final class EmailConfig implements \JsonSerializable
{
    /**
     * Constructs a EmailConfig.
     * @param string $createdAt the server's `created_at` field
     * @param bool $enabled the server's `enabled` field
     * @param string $fromEmail the server's `from_email` field
     * @param string $fromName the server's `from_name` field
     * @param string $id the server's `id` field
     * @param ProviderConfigVariant $provider the server's `provider` field
     * @param SettingsScope $scope the server's `scope` field
     * @param string $scopeId The org_id or tenant_id this config belongs to.
     * @param string $updatedAt the server's `updated_at` field
     * @param string|null $replyTo the server's `reply_to` field (optional)
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly bool $enabled,
        public readonly string $fromEmail,
        public readonly string $fromName,
        public readonly string $id,
        public readonly ProviderConfigVariant $provider,
        public readonly SettingsScope $scope,
        public readonly string $scopeId,
        public readonly string $updatedAt,
        public readonly ?string $replyTo = null,
    ) {
    }

    /**
     * Rebuilds a EmailConfig from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'created_at', self::class),
            (bool) ModelDecode::need($data, 'enabled', self::class),
            (string) ModelDecode::need($data, 'from_email', self::class),
            (string) ModelDecode::need($data, 'from_name', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            ProviderConfig::fromArray((array) ModelDecode::need($data, 'provider', self::class)),
            SettingsScope::fromWire((string) ModelDecode::need($data, 'scope', self::class)),
            (string) ModelDecode::need($data, 'scope_id', self::class),
            (string) ModelDecode::need($data, 'updated_at', self::class),
            isset($data['reply_to']) ? (string) $data['reply_to'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['enabled'] = $this->enabled;
        $out['from_email'] = $this->fromEmail;
        $out['from_name'] = $this->fromName;
        $out['id'] = $this->id;
        $out['provider'] = $this->provider->toArray();
        $out['scope'] = $this->scope->value;
        $out['scope_id'] = $this->scopeId;
        $out['updated_at'] = $this->updatedAt;
        if ($this->replyTo !== null) {
            $out['reply_to'] = $this->replyTo;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
