<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * What the server does when an interceptor does not produce a usable reply — timeout,
 * transport failure, bad signature, stale nonce, or a patch the allow-list rejects.
 */
enum FailurePolicy: string
{
    /** The wire value `fail_closed`. */
    case FailClosed = 'fail_closed';

    /** The wire value `fail_open`. */
    case FailOpen = 'fail_open';

    /**
     * Parses a wire value into a FailurePolicy.
     *
     * Throws on an unrecognised value rather than defaulting to a case: a server that has
     * learned a new state should surface as a loud error, not as whichever case was declared
     * first.
     * @throws \Axiam\Sdk\Core\AxiamException when `$value` is not a known case.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? throw new \Axiam\Sdk\Core\AxiamException(
            sprintf('unknown FailurePolicy value "%s" — the server may be newer than this SDK', $value),
        );
    }
}
