<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Federation config response -- omits client_secret.
 */
final class FederationConfigResponse implements \JsonSerializable
{
    /**
     * Constructs a FederationConfigResponse.
     * @param mixed $attributeMap the server's `attribute_map` field
     * @param string $clientId the server's `client_id` field
     * @param string $createdAt the server's `created_at` field
     * @param bool $enabled the server's `enabled` field
     * @param string $id the server's `id` field
     * @param string $protocol the server's `protocol` field
     * @param string $provider the server's `provider` field
     * @param string $tenantId the server's `tenant_id` field
     * @param TokenExchangeTrustResponse $tokenExchange X4 external token-exchange trust.
     * @param string $updatedAt the server's `updated_at` field
     * @param string|null $metadataUrl the server's `metadata_url` field (optional)
     */
    public function __construct(
        public readonly mixed $attributeMap,
        public readonly string $clientId,
        public readonly string $createdAt,
        public readonly bool $enabled,
        public readonly string $id,
        public readonly string $protocol,
        public readonly string $provider,
        public readonly string $tenantId,
        public readonly TokenExchangeTrustResponse $tokenExchange,
        public readonly string $updatedAt,
        public readonly ?string $metadataUrl = null,
    ) {
    }

    /**
     * Rebuilds a FederationConfigResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            ModelDecode::need($data, 'attribute_map', self::class),
            (string) ModelDecode::need($data, 'client_id', self::class),
            (string) ModelDecode::need($data, 'created_at', self::class),
            (bool) ModelDecode::need($data, 'enabled', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            (string) ModelDecode::need($data, 'protocol', self::class),
            (string) ModelDecode::need($data, 'provider', self::class),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            TokenExchangeTrustResponse::fromArray((array) ModelDecode::need($data, 'token_exchange', self::class)),
            (string) ModelDecode::need($data, 'updated_at', self::class),
            isset($data['metadata_url']) ? (string) $data['metadata_url'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['attribute_map'] = $this->attributeMap;
        $out['client_id'] = $this->clientId;
        $out['created_at'] = $this->createdAt;
        $out['enabled'] = $this->enabled;
        $out['id'] = $this->id;
        $out['protocol'] = $this->protocol;
        $out['provider'] = $this->provider;
        $out['tenant_id'] = $this->tenantId;
        $out['token_exchange'] = $this->tokenExchange->toArray();
        $out['updated_at'] = $this->updatedAt;
        if ($this->metadataUrl !== null) {
            $out['metadata_url'] = $this->metadataUrl;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
