<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `GrantPermissionRequest` schema from the server's OpenAPI document.
 */
final class GrantPermissionRequest implements \JsonSerializable
{
    /**
     * Constructs a GrantPermissionRequest.
     * @param string $permissionId the server's `permission_id` field
     * @param PermissionEffect|null $effect B1: `"allow"` (the default) or `"deny"`. A deny
     *     grant **overrides every allow**, at any depth of the resource hierarchy and at equal
     *     specificity — it is not most-specific-wins. See `claude_dev/deny-override-design.md` for
     *     the precedence table and for why that trade was made. Omitting the field means
     *     `"allow"`, so every existing client keeps working unchanged and no migration is
     *     required. (optional)
     * @param list<string>|null $scopeIds the server's `scope_ids` field (optional)
     */
    public function __construct(
        public readonly string $permissionId,
        public readonly ?PermissionEffect $effect = null,
        public readonly ?array $scopeIds = null,
    ) {
    }

    /**
     * Rebuilds a GrantPermissionRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'permission_id', self::class),
            isset($data['effect']) ? PermissionEffect::fromWire((string) $data['effect']) : null,
            isset($data['scope_ids']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['scope_ids'])) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['permission_id'] = $this->permissionId;
        if ($this->effect !== null) {
            $out['effect'] = $this->effect->value;
        }
        if ($this->scopeIds !== null) {
            $out['scope_ids'] = $this->scopeIds;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
