<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Who created a client registration (D5, T21.4). The discriminator that separates a
 * registration an administrator made from one that arrived over an open endpoint. Three things
 * read it and each would otherwise have to infer provenance from something that is not
 * provenance: * `axiam_oauth2::fapi` refuses a FAPI profile on anything but
 * [`Admin`](Self::Admin) (I5) — a client nobody vetted cannot be financial-grade; * the
 * authorization endpoint forces a consent hop for every other value (D4) — an unrelated party
 * gets a question put to the end user, whatever scopes it asked for; * the T21.4 sweeper
 * deletes only [`Dcr`](Self::Dcr) rows, so an administrator's client is never swept however
 * long it sits unused. [`Admin`](Self::Admin) is the serde default and therefore what every
 * row written before T21.4 decodes to, which is the truth: they were all created through `POST
 * /oauth2-clients` by somebody holding `oauth2_clients:create`.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * `self::Unknown` rather than failing the response it arrived in (CONTRACT.md §27.11 rule 1).
 * Its own wire spelling is the empty string, which no server value is, so carrying an
 * unrecognised value back into an update is refused by the server rather than written as a
 * spelling it never used. A `match` over these cases needs an `Unknown` arm.
 */
enum ManagedBy: string
{
    /** The wire value `admin`. */
    case Admin = 'admin';

    /** The wire value `dcr`. */
    case Dcr = 'dcr';

    /** The wire value `cimd`. */
    case Cimd = 'cimd';

    /** A value this SDK's copy of the spec does not list; see the type's summary. */
    case Unknown = '';

    /**
     * Parses a wire value into a ManagedBy, mapping an unrecognised one to {@see
     * self::Unknown}.
     *
     * Never throws. A parse error here would fail the whole response the value arrived in, so
     * one unrecognised field of one record would take down the page it was on (§27.11 rule 1).
     * A `match` over this enum needs an `Unknown` arm.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? self::Unknown;
    }
}
