<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `initial` arm of {@see MdsRefreshOutcome} (`outcome: "initial"`).
 */
final class MdsRefreshOutcomeInitial implements MdsRefreshOutcomeVariant
{
    /**
     * Constructs the `initial` arm.
     * @param int $entryCount the server's `entry_count` field
     * @param int $no the server's `no` field
     */
    public function __construct(
        public readonly int $entryCount,
        public readonly int $no,
    ) {
    }

    /**
     * Rebuilds the `initial` arm from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (int) $data['entry_count'],
            (int) $data['no'],
        );
    }

    /**
     * Renders this arm to its wire form, re-attaching `outcome: "initial"`.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = ['outcome' => 'initial'];
        $out['entry_count'] = $this->entryCount;
        $out['no'] = $this->no;

        return $out;
    }

    /**
     * Renders this arm for `json_encode()`.
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
