<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * `POST /api/v1/mds/refresh` response — the outcome of one ingestion attempt (mirrors
 * `axiam_db::mds_ingest::MdsIngestOutcome`).
 *
 * The decoder for the `outcome`-tagged union. Every arm is a MdsRefreshOutcomeVariant; this
 * class exists only to pick the right one.
 */
final class MdsRefreshOutcome
{
    /**
     * Decodes one `outcome`-tagged MdsRefreshOutcome object into its variant.
     * @param array<string,mixed> $data The raw wire object.
     * @throws \Axiam\Sdk\Core\AxiamException when `outcome` is missing or unknown.
     */
    public static function fromArray(array $data): MdsRefreshOutcomeVariant
    {
        $tag = $data['outcome'] ?? null;

        return match ($tag) {
            'initial' => MdsRefreshOutcomeInitial::fromArray($data),
            'replaced' => MdsRefreshOutcomeReplaced::fromArray($data),
            'no_op_refresh' => MdsRefreshOutcomeNoOpRefresh::fromArray($data),
            'rollback_rejected' => MdsRefreshOutcomeRollbackRejected::fromArray($data),
            default => throw new \Axiam\Sdk\Core\AxiamException(
                sprintf('unknown MdsRefreshOutcome outcome "%s"', is_string($tag) ? $tag : gettype($tag)),
            ),
        };
    }
}
