<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `MfaMethodResponse` schema from the server's OpenAPI document.
 */
final class MfaMethodResponse implements \JsonSerializable
{
    /**
     * Constructs a MfaMethodResponse.
     * @param string $createdAt the server's `created_at` field
     * @param string $methodId the server's `method_id` field
     * @param MfaMethodType $methodType the server's `method_type` field
     * @param string $name the server's `name` field
     * @param string|null $lastUsedAt the server's `last_used_at` field (optional)
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $methodId,
        public readonly MfaMethodType $methodType,
        public readonly string $name,
        public readonly ?string $lastUsedAt = null,
    ) {
    }

    /**
     * Rebuilds a MfaMethodResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['created_at'],
            (string) $data['method_id'],
            MfaMethodType::fromWire((string) $data['method_type']),
            (string) $data['name'],
            isset($data['last_used_at']) ? (string) $data['last_used_at'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['method_id'] = $this->methodId;
        $out['method_type'] = $this->methodType->value;
        $out['name'] = $this->name;
        if ($this->lastUsedAt !== null) {
            $out['last_used_at'] = $this->lastUsedAt;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
