<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The acknowledgement, which is mostly about the restart.
 */
final class MtlsTrustAnchorResponse implements \JsonSerializable
{
    /**
     * Constructs a MtlsTrustAnchorResponse.
     * @param string $caCertificateId The CA this is about.
     * @param string $message A sentence an operator can act on, rather than a bare boolean.
     * @param bool $mtlsTrustAnchor The flag as now stored.
     * @param bool $restartRequired Always `true`: rustls builds its client trust store once,
     *     when the listener is constructed, so this takes effect at the next start.
     */
    public function __construct(
        public readonly string $caCertificateId,
        public readonly string $message,
        public readonly bool $mtlsTrustAnchor,
        public readonly bool $restartRequired,
    ) {
    }

    /**
     * Rebuilds a MtlsTrustAnchorResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['ca_certificate_id'],
            (string) $data['message'],
            (bool) $data['mtls_trust_anchor'],
            (bool) $data['restart_required'],
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['ca_certificate_id'] = $this->caCertificateId;
        $out['message'] = $this->message;
        $out['mtls_trust_anchor'] = $this->mtlsTrustAnchor;
        $out['restart_required'] = $this->restartRequired;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
