<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Events that can trigger an admin notification.
 */
enum NotificationEventType: string
{
    /** The wire value `login_failure`. */
    case LoginFailure = 'login_failure';

    /** The wire value `account_locked`. */
    case AccountLocked = 'account_locked';

    /** The wire value `mfa_enrollment_changed`. */
    case MfaEnrollmentChanged = 'mfa_enrollment_changed';

    /** The wire value `password_changed`. */
    case PasswordChanged = 'password_changed';

    /** The wire value `password_reset_requested`. */
    case PasswordResetRequested = 'password_reset_requested';

    /** The wire value `role_assigned`. */
    case RoleAssigned = 'role_assigned';

    /** The wire value `role_unassigned`. */
    case RoleUnassigned = 'role_unassigned';

    /** The wire value `permission_granted`. */
    case PermissionGranted = 'permission_granted';

    /** The wire value `permission_revoked`. */
    case PermissionRevoked = 'permission_revoked';

    /** The wire value `certificate_issued`. */
    case CertificateIssued = 'certificate_issued';

    /** The wire value `certificate_revoked`. */
    case CertificateRevoked = 'certificate_revoked';

    /** The wire value `ca_certificate_revoked`. */
    case CaCertificateRevoked = 'ca_certificate_revoked';

    /** The wire value `user_created`. */
    case UserCreated = 'user_created';

    /** The wire value `user_deleted`. */
    case UserDeleted = 'user_deleted';

    /** The wire value `user_updated`. */
    case UserUpdated = 'user_updated';

    /** The wire value `service_account_created`. */
    case ServiceAccountCreated = 'service_account_created';

    /** The wire value `service_account_deleted`. */
    case ServiceAccountDeleted = 'service_account_deleted';

    /**
     * Parses a wire value into a NotificationEventType.
     *
     * Throws on an unrecognised value rather than defaulting to a case: a server that has
     * learned a new state should surface as a loud error, not as whichever case was declared
     * first.
     * @throws \Axiam\Sdk\Core\AxiamException when `$value` is not a known case.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? throw new \Axiam\Sdk\Core\AxiamException(
            sprintf('unknown NotificationEventType value "%s" — the server may be newer than this SDK', $value),
        );
    }
}
