<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Notification rule response.
 */
final class NotificationRuleResponse implements \JsonSerializable
{
    /**
     * Constructs a NotificationRuleResponse.
     * @param string $createdAt the server's `created_at` field
     * @param string $description the server's `description` field
     * @param bool $enabled the server's `enabled` field
     * @param list<NotificationEventType> $events the server's `events` field
     * @param string $id the server's `id` field
     * @param string $name the server's `name` field
     * @param list<string> $recipientEmails the server's `recipient_emails` field
     * @param string $tenantId the server's `tenant_id` field
     * @param string $updatedAt the server's `updated_at` field
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $description,
        public readonly bool $enabled,
        public readonly array $events,
        public readonly string $id,
        public readonly string $name,
        public readonly array $recipientEmails,
        public readonly string $tenantId,
        public readonly string $updatedAt,
    ) {
    }

    /**
     * Rebuilds a NotificationRuleResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['created_at'],
            (string) $data['description'],
            (bool) $data['enabled'],
            array_values(array_map(static fn (mixed $v): NotificationEventType => NotificationEventType::fromWire((string) $v), (array) $data['events'])),
            (string) $data['id'],
            (string) $data['name'],
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['recipient_emails'])),
            (string) $data['tenant_id'],
            (string) $data['updated_at'],
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['description'] = $this->description;
        $out['enabled'] = $this->enabled;
        $out['events'] = array_map(static fn (NotificationEventType $v): string => $v->value, $this->events);
        $out['id'] = $this->id;
        $out['name'] = $this->name;
        $out['recipient_emails'] = $this->recipientEmails;
        $out['tenant_id'] = $this->tenantId;
        $out['updated_at'] = $this->updatedAt;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
