<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * OAuth2 client response -- omits client_secret_hash.
 */
final class OAuth2ClientResponse implements \JsonSerializable
{
    /**
     * Constructs a OAuth2ClientResponse.
     * @param string $clientId the server's `client_id` field
     * @param string $createdAt the server's `created_at` field
     * @param bool $dpopBoundAccessTokens the server's `dpop_bound_access_tokens` field
     * @param bool $dpopRequireNonce the server's `dpop_require_nonce` field
     * @param list<string> $grantTypes the server's `grant_types` field
     * @param string $id the server's `id` field
     * @param string $name the server's `name` field
     * @param ClientProfile $profile X5.1 — the registered posture and mTLS credentials.
     *     Read-back matters: an operator auditing which clients are financial-grade should be able
     *     to answer it from this endpoint rather than from the database.
     * @param list<string> $redirectUris the server's `redirect_uris` field
     * @param bool $requirePar the server's `require_par` field
     * @param list<string> $scopes the server's `scopes` field
     * @param list<string> $selfSignedTlsClientAuthThumbprints the server's
     *     `self_signed_tls_client_auth_thumbprints` field
     * @param string $tenantId the server's `tenant_id` field
     * @param bool $tlsClientCertificateBoundAccessTokens the server's
     *     `tls_client_certificate_bound_access_tokens` field
     * @param ClientAuthMethod $tokenEndpointAuthMethod the server's
     *     `token_endpoint_auth_method` field
     * @param string $updatedAt the server's `updated_at` field
     * @param string|null $jwks X5.1 — echoed so an operator can confirm which key source is
     *     registered. The document itself is public key material, so returning it leaks nothing; a
     *     `jwks_uri` is likewise public by construction. (optional)
     * @param string|null $jwksUri the server's `jwks_uri` field (optional)
     * @param string|null $tlsClientAuthSanDns the server's `tls_client_auth_san_dns` field
     *     (optional)
     * @param string|null $tlsClientAuthSanUri the server's `tls_client_auth_san_uri` field
     *     (optional)
     * @param string|null $tlsClientAuthSubjectDn the server's `tls_client_auth_subject_dn`
     *     field (optional)
     */
    public function __construct(
        public readonly string $clientId,
        public readonly string $createdAt,
        public readonly bool $dpopBoundAccessTokens,
        public readonly bool $dpopRequireNonce,
        public readonly array $grantTypes,
        public readonly string $id,
        public readonly string $name,
        public readonly ClientProfile $profile,
        public readonly array $redirectUris,
        public readonly bool $requirePar,
        public readonly array $scopes,
        public readonly array $selfSignedTlsClientAuthThumbprints,
        public readonly string $tenantId,
        public readonly bool $tlsClientCertificateBoundAccessTokens,
        public readonly ClientAuthMethod $tokenEndpointAuthMethod,
        public readonly string $updatedAt,
        public readonly ?string $jwks = null,
        public readonly ?string $jwksUri = null,
        public readonly ?string $tlsClientAuthSanDns = null,
        public readonly ?string $tlsClientAuthSanUri = null,
        public readonly ?string $tlsClientAuthSubjectDn = null,
    ) {
    }

    /**
     * Rebuilds a OAuth2ClientResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['client_id'],
            (string) $data['created_at'],
            (bool) $data['dpop_bound_access_tokens'],
            (bool) $data['dpop_require_nonce'],
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['grant_types'])),
            (string) $data['id'],
            (string) $data['name'],
            ClientProfile::fromWire((string) $data['profile']),
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['redirect_uris'])),
            (bool) $data['require_par'],
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['scopes'])),
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['self_signed_tls_client_auth_thumbprints'])),
            (string) $data['tenant_id'],
            (bool) $data['tls_client_certificate_bound_access_tokens'],
            ClientAuthMethod::fromWire((string) $data['token_endpoint_auth_method']),
            (string) $data['updated_at'],
            isset($data['jwks']) ? (string) $data['jwks'] : null,
            isset($data['jwks_uri']) ? (string) $data['jwks_uri'] : null,
            isset($data['tls_client_auth_san_dns']) ? (string) $data['tls_client_auth_san_dns'] : null,
            isset($data['tls_client_auth_san_uri']) ? (string) $data['tls_client_auth_san_uri'] : null,
            isset($data['tls_client_auth_subject_dn']) ? (string) $data['tls_client_auth_subject_dn'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['client_id'] = $this->clientId;
        $out['created_at'] = $this->createdAt;
        $out['dpop_bound_access_tokens'] = $this->dpopBoundAccessTokens;
        $out['dpop_require_nonce'] = $this->dpopRequireNonce;
        $out['grant_types'] = $this->grantTypes;
        $out['id'] = $this->id;
        $out['name'] = $this->name;
        $out['profile'] = $this->profile->value;
        $out['redirect_uris'] = $this->redirectUris;
        $out['require_par'] = $this->requirePar;
        $out['scopes'] = $this->scopes;
        $out['self_signed_tls_client_auth_thumbprints'] = $this->selfSignedTlsClientAuthThumbprints;
        $out['tenant_id'] = $this->tenantId;
        $out['tls_client_certificate_bound_access_tokens'] = $this->tlsClientCertificateBoundAccessTokens;
        $out['token_endpoint_auth_method'] = $this->tokenEndpointAuthMethod->value;
        $out['updated_at'] = $this->updatedAt;
        if ($this->jwks !== null) {
            $out['jwks'] = $this->jwks;
        }
        if ($this->jwksUri !== null) {
            $out['jwks_uri'] = $this->jwksUri;
        }
        if ($this->tlsClientAuthSanDns !== null) {
            $out['tls_client_auth_san_dns'] = $this->tlsClientAuthSanDns;
        }
        if ($this->tlsClientAuthSanUri !== null) {
            $out['tls_client_auth_san_uri'] = $this->tlsClientAuthSanUri;
        }
        if ($this->tlsClientAuthSubjectDn !== null) {
            $out['tls_client_auth_subject_dn'] = $this->tlsClientAuthSubjectDn;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
