<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `OidcCallbackRequest` schema from the server's OpenAPI document.
 */
final class OidcCallbackRequest implements \JsonSerializable
{
    /**
     * Constructs a OidcCallbackRequest.
     * @param string $code Authorization code returned by the external IdP.
     * @param string $configId ID of the federation config used in the authorization request.
     * @param string $nonce Client-supplied nonce (SECHRD-07/D-04: retained for backward
     *     compatibility with older callers, but IGNORED for verification — `expected_nonce` always
     *     comes from the server-side `FederationLoginState` row looked up via `state`, never from
     *     this field).
     * @param string $redirectUri Redirect URI that was used in the authorization request.
     * @param string $state CSRF state value from the authorization request. Used to look up
     *     the server-side `FederationLoginState` row that holds the real nonce (SECHRD-07/D-04) —
     *     required so the callback can find its login state.
     */
    public function __construct(
        public readonly string $code,
        public readonly string $configId,
        public readonly string $nonce,
        public readonly string $redirectUri,
        public readonly string $state,
    ) {
    }

    /**
     * Rebuilds a OidcCallbackRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'code', self::class),
            (string) ModelDecode::need($data, 'config_id', self::class),
            (string) ModelDecode::need($data, 'nonce', self::class),
            (string) ModelDecode::need($data, 'redirect_uri', self::class),
            (string) ModelDecode::need($data, 'state', self::class),
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['code'] = $this->code;
        $out['config_id'] = $this->configId;
        $out['nonce'] = $this->nonce;
        $out['redirect_uri'] = $this->redirectUri;
        $out['state'] = $this->state;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
