<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The client-supplied half of an OPAQUE enrolment, as it appears inside registration /
 * change-password / reset-completion / bootstrap request bodies. There is no standalone
 * `register/finish` endpoint, deliberately. A record can only be created at a moment when the
 * plaintext password legitimately exists on the client, and every one of those moments is
 * already an endpoint that takes a password. A free-standing finish would be an endpoint whose
 * only job is to attach a credential to an account, which is a thing worth not having. Kept
 * separate from [`CreateOpaqueCredential`] because the tenant, the user and the credential
 * identifier are all decided by the server — a client that could name them could enrol a
 * record against somebody else's account.
 */
final class OpaqueEnrollment implements \JsonSerializable
{
    /**
     * Constructs a OpaqueEnrollment.
     * @param string $opaqueSession The `opaque_session` from the register/start response,
     *     echoed verbatim.
     * @param string $registrationRecord Lowercase-hex serialized RFC 9807
     *     `RegistrationRecord`.
     */
    public function __construct(
        public readonly string $opaqueSession,
        public readonly string $registrationRecord,
    ) {
    }

    /**
     * Rebuilds a OpaqueEnrollment from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['opaque_session'],
            (string) $data['registration_record'],
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['opaque_session'] = $this->opaqueSession;
        $out['registration_record'] = $this->registrationRecord;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
