<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * An organization groups multiple tenants under a single administrative entity. Organizations
 * represent companies, departments, or business units. CA certificates are registered at the
 * organization level, enabling a hierarchical trust model across all tenants.
 */
final class Organization implements \JsonSerializable
{
    /**
     * Constructs a Organization.
     * @param string $createdAt the server's `created_at` field
     * @param string $id the server's `id` field
     * @param mixed $metadata Arbitrary key-value metadata.
     * @param string $name Human-readable name.
     * @param string $slug URL-safe unique identifier (e.g., `acme-corp`).
     * @param string $updatedAt the server's `updated_at` field
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $id,
        public readonly mixed $metadata,
        public readonly string $name,
        public readonly string $slug,
        public readonly string $updatedAt,
    ) {
    }

    /**
     * Rebuilds a Organization from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['created_at'],
            (string) $data['id'],
            $data['metadata'],
            (string) $data['name'],
            (string) $data['slug'],
            (string) $data['updated_at'],
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['id'] = $this->id;
        $out['metadata'] = $this->metadata;
        $out['name'] = $this->name;
        $out['slug'] = $this->slug;
        $out['updated_at'] = $this->updatedAt;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
