<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * `POST …/saml/parse-sp-metadata` body: **exactly one** of the two members.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left
 * unchanged, and is omitted from the wire request entirely rather than sent as null (§27.4
 * rule 5).
 */
final class ParseSamlSpMetadata implements \JsonSerializable
{
    /**
     * Constructs a ParseSamlSpMetadata.
     * @param string|null $metadataUrl An `https` URL the server fetches the document from,
     *     once, through its SSRF guard. (optional)
     * @param string|null $metadataXml A metadata document, at most 512 KiB. (optional)
     */
    public function __construct(
        public readonly ?string $metadataUrl = null,
        public readonly ?string $metadataXml = null,
    ) {
    }

    /**
     * A request for the server to fetch the SP's metadata from `$value` (`https` only, through
     * its SSRF guard). Leaves `metadata_xml` absent.
     * @param string $value the `metadata_url` member
     */
    public static function fromUrl(string $value): self
    {
        return new self(metadataUrl: $value);
    }

    /**
     * A request carrying the SP's metadata document itself (at most 512 KiB). Leaves
     * `metadata_url` absent.
     * @param string $value the `metadata_xml` member
     */
    public static function fromXml(string $value): self
    {
        return new self(metadataXml: $value);
    }

    /**
     * Rebuilds a ParseSamlSpMetadata from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            isset($data['metadata_url']) ? (string) $data['metadata_url'] : null,
            isset($data['metadata_xml']) ? (string) $data['metadata_xml'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->metadataUrl !== null) {
            $out['metadata_url'] = $this->metadataUrl;
        }
        if ($this->metadataXml !== null) {
            $out['metadata_xml'] = $this->metadataXml;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
