<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Key algorithm for OpenPGP keys.
 */
enum PgpKeyAlgorithm: string
{
    /** The wire value `Rsa4096`. */
    case Rsa4096 = 'Rsa4096';

    /** The wire value `Ed25519`. */
    case Ed25519 = 'Ed25519';

    /**
     * Parses a wire value into a PgpKeyAlgorithm.
     *
     * Throws on an unrecognised value rather than defaulting to a case: a server that has
     * learned a new state should surface as a loud error, not as whichever case was declared
     * first.
     * @throws \Axiam\Sdk\Core\AxiamException when `$value` is not a known case.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? throw new \Axiam\Sdk\Core\AxiamException(
            sprintf('unknown PgpKeyAlgorithm value "%s" — the server may be newer than this SDK', $value),
        );
    }
}
