<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Provider-specific connection details.
 *
 * The decoder for the `kind`-tagged union. Every arm is a ProviderConfigVariant; this class
 * exists only to pick the right one.
 */
final class ProviderConfig
{
    /**
     * Decodes one `kind`-tagged ProviderConfig object into its variant.
     * @param array<string,mixed> $data The raw wire object.
     * @throws \Axiam\Sdk\Core\AxiamException when `kind` is missing or unknown.
     */
    public static function fromArray(array $data): ProviderConfigVariant
    {
        $tag = $data['kind'] ?? null;

        return match ($tag) {
            'smtp' => ProviderConfigSmtp::fromArray($data),
            'send_grid' => ProviderConfigSendGrid::fromArray($data),
            'postmark' => ProviderConfigPostmark::fromArray($data),
            'resend' => ProviderConfigResend::fromArray($data),
            'brevo' => ProviderConfigBrevo::fromArray($data),
            default => throw new \Axiam\Sdk\Core\AxiamException(
                sprintf('unknown ProviderConfig kind "%s"', is_string($tag) ? $tag : gettype($tag)),
            ),
        };
    }
}
