<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * One hookable event, as the registry describes it.
 */
final class ReactorEventDescriptor implements \JsonSerializable
{
    /**
     * Constructs a ReactorEventDescriptor.
     * @param FailurePolicy $defaultFailurePolicy the server's `default_failure_policy` field
     * @param string $description the server's `description` field
     * @param bool $interceptable the server's `interceptable` field
     * @param bool $mutable the server's `mutable` field
     * @param list<string> $mutableFields Exact field names, or a namespace prefix ending in
     *     `.` — `ext.` admits `ext.department` and nothing outside the namespace.
     * @param string $name the server's `name` field
     */
    public function __construct(
        public readonly FailurePolicy $defaultFailurePolicy,
        public readonly string $description,
        public readonly bool $interceptable,
        public readonly bool $mutable,
        public readonly array $mutableFields,
        public readonly string $name,
    ) {
    }

    /**
     * Rebuilds a ReactorEventDescriptor from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            FailurePolicy::fromWire((string) $data['default_failure_policy']),
            (string) $data['description'],
            (bool) $data['interceptable'],
            (bool) $data['mutable'],
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['mutable_fields'])),
            (string) $data['name'],
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['default_failure_policy'] = $this->defaultFailurePolicy->value;
        $out['description'] = $this->description;
        $out['interceptable'] = $this->interceptable;
        $out['mutable'] = $this->mutable;
        $out['mutable_fields'] = $this->mutableFields;
        $out['name'] = $this->name;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
