<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Metadata only. The handle exists in plaintext exactly once, in
 * [`CreateRegistrationTokenResponse`].
 */
final class RegistrationTokenResponse implements \JsonSerializable
{
    /**
     * Constructs a RegistrationTokenResponse.
     * @param string $createdAt Row creation time.
     * @param string $createdBy The administrator who minted it.
     * @param string $expiresAt When it stops being usable.
     * @param string $id Row identity.
     * @param string $name The operator-facing label.
     * @param string $tenantId The tenant a registration on this token lands in.
     * @param string|null $usedAt When it was spent, if it was. (optional)
     * @param string|null $usedByClientId Reserved; always absent in this build. See
     *     `axiam_core::models::oauth2_registration_token::OAuth2RegistrationToken::used_by_client_id`
     *     — the registration a token produced is recorded in the audit log, not here. (optional)
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $createdBy,
        public readonly string $expiresAt,
        public readonly string $id,
        public readonly string $name,
        public readonly string $tenantId,
        public readonly ?string $usedAt = null,
        public readonly ?string $usedByClientId = null,
    ) {
    }

    /**
     * Rebuilds a RegistrationTokenResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'created_at', self::class),
            (string) ModelDecode::need($data, 'created_by', self::class),
            (string) ModelDecode::need($data, 'expires_at', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            (string) ModelDecode::need($data, 'name', self::class),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            isset($data['used_at']) ? (string) $data['used_at'] : null,
            isset($data['used_by_client_id']) ? (string) $data['used_by_client_id'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['created_by'] = $this->createdBy;
        $out['expires_at'] = $this->expiresAt;
        $out['id'] = $this->id;
        $out['name'] = $this->name;
        $out['tenant_id'] = $this->tenantId;
        if ($this->usedAt !== null) {
            $out['used_at'] = $this->usedAt;
        }
        if ($this->usedByClientId !== null) {
            $out['used_by_client_id'] = $this->usedByClientId;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
