<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `Resource` schema from the server's OpenAPI document.
 */
final class Resource implements \JsonSerializable
{
    /**
     * Constructs a Resource.
     * @param string $createdAt the server's `created_at` field
     * @param string $id the server's `id` field
     * @param mixed $metadata the server's `metadata` field
     * @param string $name the server's `name` field
     * @param string $resourceType The type of resource (e.g., `project`, `service`,
     *     `endpoint`).
     * @param string $tenantId the server's `tenant_id` field
     * @param string $updatedAt the server's `updated_at` field
     * @param string|null $parentId Parent resource ID for hierarchical organization. `None`
     *     for root resources. (optional)
     * @param string|null $umaRegisteredBy The `client_id` that registered this resource
     *     through the UMA Protection API (X2), or `None` for a resource created any other way.
     *     Read-only from every ordinary path: [`UpdateResource`] cannot set it and
     *     [`CreateResource`] cannot either, so the only writer is the resource-registration
     *     handler. That is deliberate — the field backs a provenance badge in the admin UI, and a
     *     provenance marker anyone can write is decoration that reads like evidence. (optional)
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $id,
        public readonly mixed $metadata,
        public readonly string $name,
        public readonly string $resourceType,
        public readonly string $tenantId,
        public readonly string $updatedAt,
        public readonly ?string $parentId = null,
        public readonly ?string $umaRegisteredBy = null,
    ) {
    }

    /**
     * Rebuilds a Resource from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['created_at'],
            (string) $data['id'],
            $data['metadata'],
            (string) $data['name'],
            (string) $data['resource_type'],
            (string) $data['tenant_id'],
            (string) $data['updated_at'],
            isset($data['parent_id']) ? (string) $data['parent_id'] : null,
            isset($data['uma_registered_by']) ? (string) $data['uma_registered_by'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['id'] = $this->id;
        $out['metadata'] = $this->metadata;
        $out['name'] = $this->name;
        $out['resource_type'] = $this->resourceType;
        $out['tenant_id'] = $this->tenantId;
        $out['updated_at'] = $this->updatedAt;
        if ($this->parentId !== null) {
            $out['parent_id'] = $this->parentId;
        }
        if ($this->umaRegisteredBy !== null) {
            $out['uma_registered_by'] = $this->umaRegisteredBy;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
