<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A role together with its assignment context (the resource it is scoped to).
 */
final class RoleAssignment implements \JsonSerializable
{
    /**
     * Constructs a RoleAssignment.
     * @param Role $role the server's `role` field
     * @param string|null $resourceId `None` means the role was assigned globally (no resource
     *     scope). (optional)
     * @param list<string>|null $tenantScope The tenants this assignment reaches. See
     *     [`TenantScope`]. (optional)
     */
    public function __construct(
        public readonly Role $role,
        public readonly ?string $resourceId = null,
        public readonly ?array $tenantScope = null,
    ) {
    }

    /**
     * Rebuilds a RoleAssignment from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            Role::fromArray((array) ModelDecode::need($data, 'role', self::class)),
            isset($data['resource_id']) ? (string) $data['resource_id'] : null,
            isset($data['tenant_scope']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['tenant_scope'])) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['role'] = $this->role->toArray();
        if ($this->resourceId !== null) {
            $out['resource_id'] = $this->resourceId;
        }
        if ($this->tenantScope !== null && $this->tenantScope !== []) {
            $out['tenant_scope'] = $this->tenantScope;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
