<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The tenant's IdP signing credential, **public facts only**. There is no key on it and no
 * field a key could be put in: the private key is generated by the server, sealed at rest,
 * never returned by any route and destroyed on retirement (D-21).
 */
final class SamlIdpCredential implements \JsonSerializable
{
    /**
     * Constructs a SamlIdpCredential.
     * @param string $certificatePem The leaf certificate, PEM. Public: it is what the metadata
     *     publishes.
     * @param string $createdAt When the credential was issued.
     * @param string $fingerprint Lower-case hex SHA-256 of the certificate's DER — what an SP
     *     administrator compares out of band.
     * @param string $id Credential id.
     * @param string $issuerCaId The signing CA that issued the leaf.
     * @param string $notAfter End of the certificate's validity (at most 730 days after the
     *     start).
     * @param string $notBefore Start of the certificate's validity.
     * @param string $serial The certificate's serial, lower-case hex.
     * @param SamlIdpCredentialStatus $status `active`, `next` or `retired`. At most one
     *     `active` and one `next` per tenant.
     * @param string $tenantId The tenant it signs for.
     * @param string|null $retiredAt When it was retired, or null. (optional)
     */
    public function __construct(
        public readonly string $certificatePem,
        public readonly string $createdAt,
        public readonly string $fingerprint,
        public readonly string $id,
        public readonly string $issuerCaId,
        public readonly string $notAfter,
        public readonly string $notBefore,
        public readonly string $serial,
        public readonly SamlIdpCredentialStatus $status,
        public readonly string $tenantId,
        public readonly ?string $retiredAt = null,
    ) {
    }

    /**
     * Rebuilds a SamlIdpCredential from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'certificate_pem', self::class),
            (string) ModelDecode::need($data, 'created_at', self::class),
            (string) ModelDecode::need($data, 'fingerprint', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            (string) ModelDecode::need($data, 'issuer_ca_id', self::class),
            (string) ModelDecode::need($data, 'not_after', self::class),
            (string) ModelDecode::need($data, 'not_before', self::class),
            (string) ModelDecode::need($data, 'serial', self::class),
            SamlIdpCredentialStatus::fromWire((string) ModelDecode::need($data, 'status', self::class)),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            isset($data['retired_at']) ? (string) $data['retired_at'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['certificate_pem'] = $this->certificatePem;
        $out['created_at'] = $this->createdAt;
        $out['fingerprint'] = $this->fingerprint;
        $out['id'] = $this->id;
        $out['issuer_ca_id'] = $this->issuerCaId;
        $out['not_after'] = $this->notAfter;
        $out['not_before'] = $this->notBefore;
        $out['serial'] = $this->serial;
        $out['status'] = $this->status->value;
        $out['tenant_id'] = $this->tenantId;
        if ($this->retiredAt !== null) {
            $out['retired_at'] = $this->retiredAt;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
