<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Everything an administrator supplies when registering or replacing a service provider
 * (`create` and `update` both take it; `update` is a full replacement). Every field but
 * `entity_id`, `display_name` and `acs_urls` has a default, so a client written against a
 * later revision of this struct keeps working.
 *
 * This is a REPLACEMENT body (§27.4 rule 5): what it omits is not preserved. The required
 * members are constructor parameters, so omitting one is a constructor error; an optional
 * member left unset is omitted from the wire and takes its default server-side.
 */
final class SamlServiceProviderInput implements \JsonSerializable
{
    /**
     * Constructs a SamlServiceProviderInput.
     * @param list<AcsEndpoint> $acsUrls The ACS allow-list. At least one, at most one default.
     * @param string $displayName Human-readable name for the console.
     * @param string $entityId The SP's `entityID`, unique per tenant. At most
     *     [`MAX_ENTITY_ID_BYTES`].
     * @param bool|null $allowIdpInitiated Whether IdP-initiated SSO is allowed for this SP
     *     (D-3). A per-SP opt-in, off by default: an unsolicited assertion has no `InResponseTo`
     *     to bind it to a request the SP made. (optional)
     * @param list<string>|null $allowedGroups Groups whose members may sign in to this SP.
     *     **Empty means every active user of the tenant may.** Evaluated by the SSO endpoint
     *     (T23.2.3). (optional)
     * @param list<AttributeMapping>|null $attributeMappings Attribute mapping table, at most
     *     [`MAX_ATTRIBUTE_MAPPINGS`] entries. (optional)
     * @param bool|null $enabled Whether the SP may sign in at all. A disabled SP stays
     *     registered but every SSO request for it is refused. (optional)
     * @param bool|null $encryptAssertions Encrypt assertions to the SP's encryption
     *     certificate (D-2). Off by default; requires [`Self::sp_encryption_cert_pem`]. (optional)
     * @param NameIdFormat|null $nameIdFormat `NameID` policy. Default: persistent, pairwise.
     *     (optional)
     * @param bool|null $signResponses Sign the `<samlp:Response>` envelope as well as the
     *     assertion (which is signed always). Default **`true`**: it costs nothing and many SPs
     *     require it. (optional)
     * @param SamlBinding|null $sloBinding the server's `slo_binding` field (optional)
     * @param string|null $sloUrl Single-logout endpoint, if the SP supports it. (optional)
     * @param string|null $spEncryptionCertPem PEM certificate assertions are encrypted to.
     *     Required when `encrypt_assertions` is set. (optional)
     * @param string|null $spSigningCertPem PEM certificate the SP signs its `AuthnRequest`s
     *     with. (optional)
     * @param bool|null $wantAuthnRequestsSigned Refuse an `AuthnRequest` that is not signed by
     *     `sp_signing_cert_pem`. Requires that certificate. (optional)
     */
    public function __construct(
        public readonly array $acsUrls,
        public readonly string $displayName,
        public readonly string $entityId,
        public readonly ?bool $allowIdpInitiated = null,
        public readonly ?array $allowedGroups = null,
        public readonly ?array $attributeMappings = null,
        public readonly ?bool $enabled = null,
        public readonly ?bool $encryptAssertions = null,
        public readonly ?NameIdFormat $nameIdFormat = null,
        public readonly ?bool $signResponses = null,
        public readonly ?SamlBinding $sloBinding = null,
        public readonly ?string $sloUrl = null,
        public readonly ?string $spEncryptionCertPem = null,
        public readonly ?string $spSigningCertPem = null,
        public readonly ?bool $wantAuthnRequestsSigned = null,
    ) {
    }

    /**
     * Rebuilds a SamlServiceProviderInput from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            array_values(array_map(static fn (mixed $v): AcsEndpoint => AcsEndpoint::fromArray((array) $v), (array) ModelDecode::need($data, 'acs_urls', self::class))),
            (string) ModelDecode::need($data, 'display_name', self::class),
            (string) ModelDecode::need($data, 'entity_id', self::class),
            isset($data['allow_idp_initiated']) ? (bool) $data['allow_idp_initiated'] : null,
            isset($data['allowed_groups']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['allowed_groups'])) : null,
            isset($data['attribute_mappings']) ? array_values(array_map(static fn (mixed $v): AttributeMapping => AttributeMapping::fromArray((array) $v), (array) $data['attribute_mappings'])) : null,
            isset($data['enabled']) ? (bool) $data['enabled'] : null,
            isset($data['encrypt_assertions']) ? (bool) $data['encrypt_assertions'] : null,
            isset($data['name_id_format']) ? NameIdFormat::fromWire((string) $data['name_id_format']) : null,
            isset($data['sign_responses']) ? (bool) $data['sign_responses'] : null,
            isset($data['slo_binding']) ? SamlBinding::fromWire((string) $data['slo_binding']) : null,
            isset($data['slo_url']) ? (string) $data['slo_url'] : null,
            isset($data['sp_encryption_cert_pem']) ? (string) $data['sp_encryption_cert_pem'] : null,
            isset($data['sp_signing_cert_pem']) ? (string) $data['sp_signing_cert_pem'] : null,
            isset($data['want_authn_requests_signed']) ? (bool) $data['want_authn_requests_signed'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['acs_urls'] = array_map(static fn (AcsEndpoint $v): array => $v->toArray(), $this->acsUrls);
        $out['display_name'] = $this->displayName;
        $out['entity_id'] = $this->entityId;
        if ($this->allowIdpInitiated !== null) {
            $out['allow_idp_initiated'] = $this->allowIdpInitiated;
        }
        if ($this->allowedGroups !== null) {
            $out['allowed_groups'] = $this->allowedGroups;
        }
        if ($this->attributeMappings !== null) {
            $out['attribute_mappings'] = array_map(static fn (AttributeMapping $v): array => $v->toArray(), $this->attributeMappings);
        }
        if ($this->enabled !== null) {
            $out['enabled'] = $this->enabled;
        }
        if ($this->encryptAssertions !== null) {
            $out['encrypt_assertions'] = $this->encryptAssertions;
        }
        if ($this->nameIdFormat !== null) {
            $out['name_id_format'] = $this->nameIdFormat->value;
        }
        if ($this->signResponses !== null) {
            $out['sign_responses'] = $this->signResponses;
        }
        if ($this->sloBinding !== null) {
            $out['slo_binding'] = $this->sloBinding->value;
        }
        if ($this->sloUrl !== null) {
            $out['slo_url'] = $this->sloUrl;
        }
        if ($this->spEncryptionCertPem !== null) {
            $out['sp_encryption_cert_pem'] = $this->spEncryptionCertPem;
        }
        if ($this->spSigningCertPem !== null) {
            $out['sp_signing_cert_pem'] = $this->spSigningCertPem;
        }
        if ($this->wantAuthnRequestsSigned !== null) {
            $out['want_authn_requests_signed'] = $this->wantAuthnRequestsSigned;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
