<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * What promoting the `next` credential did.
 */
final class SamlIdpCredentialPromotion implements \JsonSerializable
{
    /**
     * Constructs a SamlIdpCredentialPromotion.
     * @param SamlIdpCredential $active The credential that is now `active`.
     * @param SamlIdpCredential|null $retired the server's `retired` field (optional)
     */
    public function __construct(
        public readonly SamlIdpCredential $active,
        public readonly ?SamlIdpCredential $retired = null,
    ) {
    }

    /**
     * Rebuilds a SamlIdpCredentialPromotion from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            SamlIdpCredential::fromArray((array) ModelDecode::need($data, 'active', self::class)),
            isset($data['retired']) ? SamlIdpCredential::fromArray((array) $data['retired']) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['active'] = $this->active->toArray();
        if ($this->retired !== null) {
            $out['retired'] = $this->retired->toArray();
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
