<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A parse of SP metadata: **a draft, not a registration**. Nothing is stored until the caller
 * submits `service_provider` to `create_service_provider` or `update_service_provider`, and
 * nothing in it is trusted because it came from a document (D-41).
 */
final class SamlSpMetadataDraft implements \JsonSerializable
{
    /**
     * Constructs a SamlSpMetadataDraft.
     * @param SamlServiceProviderInput $serviceProvider A body `create_service_provider`
     *     accepts unchanged (bar the rules that need the datastore). `encrypt_assertions` is never
     *     set.
     * @param list<string> $warnings What to know before submitting it. Human text; do not
     *     parse it.
     * @param string|null $encryptionCertificateFingerprint Lower-case hex SHA-256 of the
     *     encryption certificate's DER the draft carries, or null. (optional)
     * @param string|null $signingCertificateFingerprint Lower-case hex SHA-256 of the signing
     *     certificate's DER the draft carries, or null. (optional)
     */
    public function __construct(
        public readonly SamlServiceProviderInput $serviceProvider,
        public readonly array $warnings,
        public readonly ?string $encryptionCertificateFingerprint = null,
        public readonly ?string $signingCertificateFingerprint = null,
    ) {
    }

    /**
     * Rebuilds a SamlSpMetadataDraft from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            SamlServiceProviderInput::fromArray((array) ModelDecode::need($data, 'service_provider', self::class)),
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) ModelDecode::need($data, 'warnings', self::class))),
            isset($data['encryption_certificate_fingerprint']) ? (string) $data['encryption_certificate_fingerprint'] : null,
            isset($data['signing_certificate_fingerprint']) ? (string) $data['signing_certificate_fingerprint'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['service_provider'] = $this->serviceProvider->toArray();
        $out['warnings'] = $this->warnings;
        if ($this->encryptionCertificateFingerprint !== null) {
            $out['encryption_certificate_fingerprint'] = $this->encryptionCertificateFingerprint;
        }
        if ($this->signingCertificateFingerprint !== null) {
            $out['signing_certificate_fingerprint'] = $this->signingCertificateFingerprint;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
