<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * `create` and `update` (a **replacement**) body.
 *
 * This is a REPLACEMENT body (§27.4 rule 5): every field is required, so omitting one is a
 * constructor error rather than a silent erasure server-side.
 */
final class ScimTargetInput implements \JsonSerializable
{
    /**
     * Constructs a ScimTargetInput.
     * @param ScimTargetAuthVariant $auth `bearer`, or `oauth2_client_credentials` with
     *     `token_url` (the same URL policy), `client_id` (1–256 bytes) and an optional `scope`.
     * @param string $baseUrl The downstream's SCIM service root: an `https` URL under the
     *     outbound address policy (no credentials or fragment, at most 2 048 bytes, no non-public
     *     address, no local name).
     * @param string $name 1–128 bytes.
     * @param ScimTargetScopeVariant $scope `all_users`, or `groups` with 1–100 `group_ids` of
     *     this tenant: users who are direct members of any listed group.
     * @param \Axiam\Sdk\Core\Sensitive|null $credential **Write-only.** The bearer token or
     *     the OAuth2 client secret, 1–4 096 bytes. Required on create. On update, absent keeps the
     *     stored one — except that moving it to another URL (`base_url` of a bearer target,
     *     `token_url` or `base_url` of a client-credentials one) or switching `auth.type` requires
     *     it again. (optional)
     * @param DeprovisionPolicy|null $deprovision `deactivate` (default: `PATCH active=false`)
     *     or `delete`. (optional)
     * @param bool|null $enabled `true` by default. A disabled target receives nothing.
     *     (optional)
     * @param bool|null $pushGroups Push groups too (every group for `all_users`, the listed
     *     ones for `groups`). `false` by default. (optional)
     * @param UserNameSource|null $userNameFrom `username` (default) or `email`. (optional)
     */
    public function __construct(
        public readonly ScimTargetAuthVariant $auth,
        public readonly string $baseUrl,
        public readonly string $name,
        public readonly ScimTargetScopeVariant $scope,
        public readonly ?\Axiam\Sdk\Core\Sensitive $credential = null,
        public readonly ?DeprovisionPolicy $deprovision = null,
        public readonly ?bool $enabled = null,
        public readonly ?bool $pushGroups = null,
        public readonly ?UserNameSource $userNameFrom = null,
    ) {
    }

    /**
     * Rebuilds a ScimTargetInput from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            ScimTargetAuth::fromArray((array) ModelDecode::need($data, 'auth', self::class)),
            (string) ModelDecode::need($data, 'base_url', self::class),
            (string) ModelDecode::need($data, 'name', self::class),
            ScimTargetScope::fromArray((array) ModelDecode::need($data, 'scope', self::class)),
            isset($data['credential']) ? new \Axiam\Sdk\Core\Sensitive((string) $data['credential']) : null,
            isset($data['deprovision']) ? DeprovisionPolicy::fromWire((string) $data['deprovision']) : null,
            isset($data['enabled']) ? (bool) $data['enabled'] : null,
            isset($data['push_groups']) ? (bool) $data['push_groups'] : null,
            isset($data['user_name_from']) ? UserNameSource::fromWire((string) $data['user_name_from']) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['auth'] = $this->auth->toArray();
        $out['base_url'] = $this->baseUrl;
        $out['name'] = $this->name;
        $out['scope'] = $this->scope->toArray();
        if ($this->credential !== null) {
            $out['credential'] = $this->credential;
        }
        if ($this->deprovision !== null) {
            $out['deprovision'] = $this->deprovision->value;
        }
        if ($this->enabled !== null) {
            $out['enabled'] = $this->enabled;
        }
        if ($this->pushGroups !== null) {
            $out['push_groups'] = $this->pushGroups;
        }
        if ($this->userNameFrom !== null) {
            $out['user_name_from'] = $this->userNameFrom->value;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     *
     * Rendering for a log line never fails: an unknown union arm renders its discriminator
     * here, and only {@see self::toArray()} -- the request path -- refuses to send it
     * (CONTRACT.md §31.2, §34.2 P12.2).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        $out = [];
        $out['auth'] = $this->auth->jsonSerialize();
        $out['base_url'] = $this->baseUrl;
        $out['name'] = $this->name;
        $out['scope'] = $this->scope->jsonSerialize();
        if ($this->credential !== null) {
            $out['credential'] = $this->credential;
        }
        if ($this->deprovision !== null) {
            $out['deprovision'] = $this->deprovision->value;
        }
        if ($this->enabled !== null) {
            $out['enabled'] = $this->enabled;
        }
        if ($this->pushGroups !== null) {
            $out['push_groups'] = $this->pushGroups;
        }
        if ($this->userNameFrom !== null) {
            $out['user_name_from'] = $this->userNameFrom->value;
        }

        return $out;
    }
}
