<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Which users a target provisions.
 *
 * The decoder for the `type`-tagged union. Every arm is a ScimTargetScopeVariant; this class
 * exists only to pick the right one.
 *
 * An **open** union: a `type` this SDK does not know decodes to {@see ScimTargetScopeUnknown}
 * instead of failing, and that arm refuses to be sent.
 */
final class ScimTargetScope
{
    /**
     * Decodes one `type`-tagged ScimTargetScope object into its variant.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): ScimTargetScopeVariant
    {
        $tag = $data['type'] ?? null;

        return match ($tag) {
            'all_users' => ScimTargetScopeAllUsers::fromArray($data),
            'groups' => ScimTargetScopeGroups::fromArray($data),
            default => ScimTargetScopeUnknown::fromArray($data),
        };
    }
}
