<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `groups` arm of {@see ScimTargetScope} (`type: "groups"`).
 */
final class ScimTargetScopeGroups implements ScimTargetScopeVariant
{
    /**
     * Constructs the `groups` arm.
     * @param list<string> $groupIds Users who are direct members of any listed group.
     */
    public function __construct(
        public readonly array $groupIds,
    ) {
    }

    /**
     * Rebuilds the `groups` arm from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) ModelDecode::need($data, 'group_ids', self::class))),
        );
    }

    /**
     * Renders this arm to its wire form, re-attaching `type: "groups"`.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = ['type' => 'groups'];
        $out['group_ids'] = $this->groupIds;

        return $out;
    }

    /**
     * Renders this arm for `json_encode()`.
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
