<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Fully resolved security settings (all fields present).
 */
final class SecuritySettings implements \JsonSerializable
{
    /**
     * Constructs a SecuritySettings.
     * @param CertificatePolicy $certificate the server's `certificate` field
     * @param string $createdAt the server's `created_at` field
     * @param EmailVerificationPolicy $email the server's `email` field
     * @param string $id the server's `id` field
     * @param LockoutPolicy $lockout the server's `lockout` field
     * @param MfaPolicy $mfa the server's `mfa` field
     * @param NotificationPolicy $notification the server's `notification` field
     * @param OpaquePolicy $opaque the server's `opaque` field
     * @param PasswordPolicy $password the server's `password` field
     * @param PrivacyPolicy $privacy the server's `privacy` field
     * @param SettingsScope $scope the server's `scope` field
     * @param string $scopeId the server's `scope_id` field
     * @param TokenPolicy $token the server's `token` field
     * @param string $updatedAt the server's `updated_at` field
     * @param WebauthnPolicy $webauthn the server's `webauthn` field
     */
    public function __construct(
        public readonly CertificatePolicy $certificate,
        public readonly string $createdAt,
        public readonly EmailVerificationPolicy $email,
        public readonly string $id,
        public readonly LockoutPolicy $lockout,
        public readonly MfaPolicy $mfa,
        public readonly NotificationPolicy $notification,
        public readonly OpaquePolicy $opaque,
        public readonly PasswordPolicy $password,
        public readonly PrivacyPolicy $privacy,
        public readonly SettingsScope $scope,
        public readonly string $scopeId,
        public readonly TokenPolicy $token,
        public readonly string $updatedAt,
        public readonly WebauthnPolicy $webauthn,
    ) {
    }

    /**
     * Rebuilds a SecuritySettings from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            CertificatePolicy::fromArray((array) ModelDecode::need($data, 'certificate', self::class)),
            (string) ModelDecode::need($data, 'created_at', self::class),
            EmailVerificationPolicy::fromArray((array) ModelDecode::need($data, 'email', self::class)),
            (string) ModelDecode::need($data, 'id', self::class),
            LockoutPolicy::fromArray((array) ModelDecode::need($data, 'lockout', self::class)),
            MfaPolicy::fromArray((array) ModelDecode::need($data, 'mfa', self::class)),
            NotificationPolicy::fromArray((array) ModelDecode::need($data, 'notification', self::class)),
            OpaquePolicy::fromArray((array) ModelDecode::need($data, 'opaque', self::class)),
            PasswordPolicy::fromArray((array) ModelDecode::need($data, 'password', self::class)),
            PrivacyPolicy::fromArray((array) ModelDecode::need($data, 'privacy', self::class)),
            SettingsScope::fromWire((string) ModelDecode::need($data, 'scope', self::class)),
            (string) ModelDecode::need($data, 'scope_id', self::class),
            TokenPolicy::fromArray((array) ModelDecode::need($data, 'token', self::class)),
            (string) ModelDecode::need($data, 'updated_at', self::class),
            WebauthnPolicy::fromArray((array) ModelDecode::need($data, 'webauthn', self::class)),
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['certificate'] = $this->certificate->toArray();
        $out['created_at'] = $this->createdAt;
        $out['email'] = $this->email->toArray();
        $out['id'] = $this->id;
        $out['lockout'] = $this->lockout->toArray();
        $out['mfa'] = $this->mfa->toArray();
        $out['notification'] = $this->notification->toArray();
        $out['opaque'] = $this->opaque->toArray();
        $out['password'] = $this->password->toArray();
        $out['privacy'] = $this->privacy->toArray();
        $out['scope'] = $this->scope->value;
        $out['scope_id'] = $this->scopeId;
        $out['token'] = $this->token->toArray();
        $out['updated_at'] = $this->updatedAt;
        $out['webauthn'] = $this->webauthn->toArray();

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
