<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Public-safe service account representation.
 */
final class ServiceAccountResponse implements \JsonSerializable
{
    /**
     * Constructs a ServiceAccountResponse.
     * @param string $clientId the server's `client_id` field
     * @param string $createdAt the server's `created_at` field
     * @param string $id the server's `id` field
     * @param string $name the server's `name` field
     * @param UserStatus $status the server's `status` field
     * @param string $tenantId the server's `tenant_id` field
     * @param string $updatedAt the server's `updated_at` field
     * @param string|null $description the server's `description` field (optional)
     */
    public function __construct(
        public readonly string $clientId,
        public readonly string $createdAt,
        public readonly string $id,
        public readonly string $name,
        public readonly UserStatus $status,
        public readonly string $tenantId,
        public readonly string $updatedAt,
        public readonly ?string $description = null,
    ) {
    }

    /**
     * Rebuilds a ServiceAccountResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) $data['client_id'],
            (string) $data['created_at'],
            (string) $data['id'],
            (string) $data['name'],
            UserStatus::fromWire((string) $data['status']),
            (string) $data['tenant_id'],
            (string) $data['updated_at'],
            isset($data['description']) ? (string) $data['description'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['client_id'] = $this->clientId;
        $out['created_at'] = $this->createdAt;
        $out['id'] = $this->id;
        $out['name'] = $this->name;
        $out['status'] = $this->status->value;
        $out['tenant_id'] = $this->tenantId;
        $out['updated_at'] = $this->updatedAt;
        if ($this->description !== null) {
            $out['description'] = $this->description;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
