<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * `PUT /api/v1/tenants/{tenant_id}/directory` — a **replacement**. Every `DirectoryConfig`
 * member except `id`, `tenant_id` and the two timestamps, plus the write-only `bind_secret`.
 * An omitted optional member is **reset to its default**, not kept.
 *
 * This is a REPLACEMENT body (§27.4 rule 5): every field is required, so omitting one is a
 * constructor error rather than a silent erasure server-side.
 */
final class SetDirectoryConfig implements \JsonSerializable
{
    /**
     * Constructs a SetDirectoryConfig.
     * @param string $baseDn Where users are searched for.
     * @param string $bindDn The service account the search runs as.
     * @param bool $enabled A disabled directory serves no sign-in and is not synced.
     * @param DirectoryKind $kind Chooses defaults only.
     * @param bool $startTls Upgrade an `ldap://` connection with StartTLS before any bind.
     * @param string $url `ldaps://host[:port]`, or `ldap://host[:port]` with `start_tls`.
     * @param string $userFilter One `{username}` placeholder in value position.
     * @param \Axiam\Sdk\Core\Sensitive|null $bindSecret The service account's password:
     *     **write-only**, 1 to 4096 octets. Required when the tenant has no configuration yet; on
     *     a replacement, absent means *keep the stored secret* — unless the write moves the
     *     connection (`url`, `start_tls`, `bind_dn` or `trust_anchors_pem`), which then requires
     *     it (`400`, P23W2-01). (optional)
     * @param string|null $groupBaseDn Defaults to null. (optional)
     * @param string|null $groupFilter Defaults to null. (optional)
     * @param list<GroupMapping>|null $groupMappings At most 500; every `group_id` a group of
     *     the tenant. Default empty. (optional)
     * @param string|null $groupMemberAttribute Defaults by `kind`. (optional)
     * @param int|null $groupNestingDepth `0..=10`, default 5. (optional)
     * @param bool|null $jitProvisioning Default false. (optional)
     * @param int|null $syncIntervalSecs `300..=86400`, default 3600. (optional)
     * @param list<string>|null $trustAnchorsPem At most 16 CA certificates in PEM. Default
     *     empty (the public roots). (optional)
     * @param UserAttributeMap|null $userAttributeMap the server's `user_attribute_map` field
     *     (optional)
     */
    public function __construct(
        public readonly string $baseDn,
        public readonly string $bindDn,
        public readonly bool $enabled,
        public readonly DirectoryKind $kind,
        public readonly bool $startTls,
        public readonly string $url,
        public readonly string $userFilter,
        public readonly ?\Axiam\Sdk\Core\Sensitive $bindSecret = null,
        public readonly ?string $groupBaseDn = null,
        public readonly ?string $groupFilter = null,
        public readonly ?array $groupMappings = null,
        public readonly ?string $groupMemberAttribute = null,
        public readonly ?int $groupNestingDepth = null,
        public readonly ?bool $jitProvisioning = null,
        public readonly ?int $syncIntervalSecs = null,
        public readonly ?array $trustAnchorsPem = null,
        public readonly ?UserAttributeMap $userAttributeMap = null,
    ) {
    }

    /**
     * Rebuilds a SetDirectoryConfig from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'base_dn', self::class),
            (string) ModelDecode::need($data, 'bind_dn', self::class),
            (bool) ModelDecode::need($data, 'enabled', self::class),
            DirectoryKind::fromWire((string) ModelDecode::need($data, 'kind', self::class)),
            (bool) ModelDecode::need($data, 'start_tls', self::class),
            (string) ModelDecode::need($data, 'url', self::class),
            (string) ModelDecode::need($data, 'user_filter', self::class),
            isset($data['bind_secret']) ? new \Axiam\Sdk\Core\Sensitive((string) $data['bind_secret']) : null,
            isset($data['group_base_dn']) ? (string) $data['group_base_dn'] : null,
            isset($data['group_filter']) ? (string) $data['group_filter'] : null,
            isset($data['group_mappings']) ? array_values(array_map(static fn (mixed $v): GroupMapping => GroupMapping::fromArray((array) $v), (array) $data['group_mappings'])) : null,
            isset($data['group_member_attribute']) ? (string) $data['group_member_attribute'] : null,
            isset($data['group_nesting_depth']) ? (int) $data['group_nesting_depth'] : null,
            isset($data['jit_provisioning']) ? (bool) $data['jit_provisioning'] : null,
            isset($data['sync_interval_secs']) ? (int) $data['sync_interval_secs'] : null,
            isset($data['trust_anchors_pem']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['trust_anchors_pem'])) : null,
            isset($data['user_attribute_map']) ? UserAttributeMap::fromArray((array) $data['user_attribute_map']) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['base_dn'] = $this->baseDn;
        $out['bind_dn'] = $this->bindDn;
        $out['enabled'] = $this->enabled;
        $out['kind'] = $this->kind->value;
        $out['start_tls'] = $this->startTls;
        $out['url'] = $this->url;
        $out['user_filter'] = $this->userFilter;
        if ($this->bindSecret !== null) {
            $out['bind_secret'] = $this->bindSecret;
        }
        if ($this->groupBaseDn !== null) {
            $out['group_base_dn'] = $this->groupBaseDn;
        }
        if ($this->groupFilter !== null) {
            $out['group_filter'] = $this->groupFilter;
        }
        if ($this->groupMappings !== null) {
            $out['group_mappings'] = array_map(static fn (GroupMapping $v): array => $v->toArray(), $this->groupMappings);
        }
        if ($this->groupMemberAttribute !== null) {
            $out['group_member_attribute'] = $this->groupMemberAttribute;
        }
        if ($this->groupNestingDepth !== null) {
            $out['group_nesting_depth'] = $this->groupNestingDepth;
        }
        if ($this->jitProvisioning !== null) {
            $out['jit_provisioning'] = $this->jitProvisioning;
        }
        if ($this->syncIntervalSecs !== null) {
            $out['sync_interval_secs'] = $this->syncIntervalSecs;
        }
        if ($this->trustAnchorsPem !== null) {
            $out['trust_anchors_pem'] = $this->trustAnchorsPem;
        }
        if ($this->userAttributeMap !== null) {
            $out['user_attribute_map'] = $this->userAttributeMap->toArray();
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
