<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Input for setting organization-level security settings.
 *
 * This is a REPLACEMENT body (§27.4 rule 5): every field is required, so omitting one is a
 * constructor error rather than a silent erasure server-side.
 */
final class SetOrgSettings implements \JsonSerializable
{
    /**
     * Constructs a SetOrgSettings.
     * @param int $accessTokenLifetimeSecs the server's `access_token_lifetime_secs` field
     * @param bool $adminNotificationsEnabled the server's `admin_notifications_enabled` field
     * @param int $defaultCertValidityDays the server's `default_cert_validity_days` field
     * @param int $emailVerificationGracePeriodHours the server's
     *     `email_verification_grace_period_hours` field
     * @param bool $emailVerificationRequired the server's `email_verification_required` field
     * @param bool $hibpCheckEnabled the server's `hibp_check_enabled` field
     * @param float $lockoutBackoffMultiplier the server's `lockout_backoff_multiplier` field
     * @param int $lockoutDurationSecs the server's `lockout_duration_secs` field
     * @param int $maxCertValidityDays the server's `max_cert_validity_days` field
     * @param int $maxFailedLoginAttempts the server's `max_failed_login_attempts` field
     * @param int $maxLockoutDurationSecs the server's `max_lockout_duration_secs` field
     * @param int $mfaChallengeLifetimeSecs the server's `mfa_challenge_lifetime_secs` field
     * @param bool $mfaEnforced the server's `mfa_enforced` field
     * @param int $minLength the server's `min_length` field
     * @param int $passwordHistoryCount the server's `password_history_count` field
     * @param int $refreshTokenLifetimeSecs the server's `refresh_token_lifetime_secs` field
     * @param bool $requireDigits the server's `require_digits` field
     * @param bool $requireLowercase the server's `require_lowercase` field
     * @param bool $requireSymbols the server's `require_symbols` field
     * @param bool $requireUppercase the server's `require_uppercase` field
     * @param CimdPolicy|null $cimd T21.5 — defaulted, so an API client written before this
     *     task lands on `enabled: false`, which is what every deployment did before client ID
     *     metadata documents existed (I1). (optional)
     * @param list<string>|null $dcrAllowedRedirectHosts the server's
     *     `dcr_allowed_redirect_hosts` field (optional)
     * @param list<string>|null $dcrAllowedScopes the server's `dcr_allowed_scopes` field
     *     (optional)
     * @param int|null $dcrMaxClients the server's `dcr_max_clients` field (optional)
     * @param int|null $dcrUnusedClientTtlDays the server's `dcr_unused_client_ttl_days` field
     *     (optional)
     * @param string|null $defaultLocale the server's `default_locale` field (optional)
     * @param int|null $deletionGracePeriodDays the server's `deletion_grace_period_days` field
     *     (optional)
     * @param string|null $dynamicRegistration the server's `dynamic_registration` field
     *     (optional)
     * @param list<string>|null $externalClientAllowedResources the server's
     *     `external_client_allowed_resources` field (optional)
     * @param string|null $opaqueKsf the server's `opaque_ksf` field (optional)
     * @param string|null $opaqueMode the server's `opaque_mode` field (optional)
     * @param string|null $opaqueSuite the server's `opaque_suite` field (optional)
     * @param bool|null $sensitiveScopesEnabled the server's `sensitive_scopes_enabled` field
     *     (optional)
     * @param string|null $webauthnUserVerification the server's `webauthn_user_verification`
     *     field (optional)
     */
    public function __construct(
        public readonly int $accessTokenLifetimeSecs,
        public readonly bool $adminNotificationsEnabled,
        public readonly int $defaultCertValidityDays,
        public readonly int $emailVerificationGracePeriodHours,
        public readonly bool $emailVerificationRequired,
        public readonly bool $hibpCheckEnabled,
        public readonly float $lockoutBackoffMultiplier,
        public readonly int $lockoutDurationSecs,
        public readonly int $maxCertValidityDays,
        public readonly int $maxFailedLoginAttempts,
        public readonly int $maxLockoutDurationSecs,
        public readonly int $mfaChallengeLifetimeSecs,
        public readonly bool $mfaEnforced,
        public readonly int $minLength,
        public readonly int $passwordHistoryCount,
        public readonly int $refreshTokenLifetimeSecs,
        public readonly bool $requireDigits,
        public readonly bool $requireLowercase,
        public readonly bool $requireSymbols,
        public readonly bool $requireUppercase,
        public readonly ?CimdPolicy $cimd = null,
        public readonly ?array $dcrAllowedRedirectHosts = null,
        public readonly ?array $dcrAllowedScopes = null,
        public readonly ?int $dcrMaxClients = null,
        public readonly ?int $dcrUnusedClientTtlDays = null,
        public readonly ?string $defaultLocale = null,
        public readonly ?int $deletionGracePeriodDays = null,
        public readonly ?string $dynamicRegistration = null,
        public readonly ?array $externalClientAllowedResources = null,
        public readonly ?string $opaqueKsf = null,
        public readonly ?string $opaqueMode = null,
        public readonly ?string $opaqueSuite = null,
        public readonly ?bool $sensitiveScopesEnabled = null,
        public readonly ?string $webauthnUserVerification = null,
    ) {
    }

    /**
     * Rebuilds a SetOrgSettings from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (int) ModelDecode::need($data, 'access_token_lifetime_secs', self::class),
            (bool) ModelDecode::need($data, 'admin_notifications_enabled', self::class),
            (int) ModelDecode::need($data, 'default_cert_validity_days', self::class),
            (int) ModelDecode::need($data, 'email_verification_grace_period_hours', self::class),
            (bool) ModelDecode::need($data, 'email_verification_required', self::class),
            (bool) ModelDecode::need($data, 'hibp_check_enabled', self::class),
            (float) ModelDecode::need($data, 'lockout_backoff_multiplier', self::class),
            (int) ModelDecode::need($data, 'lockout_duration_secs', self::class),
            (int) ModelDecode::need($data, 'max_cert_validity_days', self::class),
            (int) ModelDecode::need($data, 'max_failed_login_attempts', self::class),
            (int) ModelDecode::need($data, 'max_lockout_duration_secs', self::class),
            (int) ModelDecode::need($data, 'mfa_challenge_lifetime_secs', self::class),
            (bool) ModelDecode::need($data, 'mfa_enforced', self::class),
            (int) ModelDecode::need($data, 'min_length', self::class),
            (int) ModelDecode::need($data, 'password_history_count', self::class),
            (int) ModelDecode::need($data, 'refresh_token_lifetime_secs', self::class),
            (bool) ModelDecode::need($data, 'require_digits', self::class),
            (bool) ModelDecode::need($data, 'require_lowercase', self::class),
            (bool) ModelDecode::need($data, 'require_symbols', self::class),
            (bool) ModelDecode::need($data, 'require_uppercase', self::class),
            isset($data['cimd']) ? CimdPolicy::fromArray((array) $data['cimd']) : null,
            isset($data['dcr_allowed_redirect_hosts']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['dcr_allowed_redirect_hosts'])) : null,
            isset($data['dcr_allowed_scopes']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['dcr_allowed_scopes'])) : null,
            isset($data['dcr_max_clients']) ? (int) $data['dcr_max_clients'] : null,
            isset($data['dcr_unused_client_ttl_days']) ? (int) $data['dcr_unused_client_ttl_days'] : null,
            isset($data['default_locale']) ? (string) $data['default_locale'] : null,
            isset($data['deletion_grace_period_days']) ? (int) $data['deletion_grace_period_days'] : null,
            isset($data['dynamic_registration']) ? (string) $data['dynamic_registration'] : null,
            isset($data['external_client_allowed_resources']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['external_client_allowed_resources'])) : null,
            isset($data['opaque_ksf']) ? (string) $data['opaque_ksf'] : null,
            isset($data['opaque_mode']) ? (string) $data['opaque_mode'] : null,
            isset($data['opaque_suite']) ? (string) $data['opaque_suite'] : null,
            isset($data['sensitive_scopes_enabled']) ? (bool) $data['sensitive_scopes_enabled'] : null,
            isset($data['webauthn_user_verification']) ? (string) $data['webauthn_user_verification'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['access_token_lifetime_secs'] = $this->accessTokenLifetimeSecs;
        $out['admin_notifications_enabled'] = $this->adminNotificationsEnabled;
        $out['default_cert_validity_days'] = $this->defaultCertValidityDays;
        $out['email_verification_grace_period_hours'] = $this->emailVerificationGracePeriodHours;
        $out['email_verification_required'] = $this->emailVerificationRequired;
        $out['hibp_check_enabled'] = $this->hibpCheckEnabled;
        $out['lockout_backoff_multiplier'] = $this->lockoutBackoffMultiplier;
        $out['lockout_duration_secs'] = $this->lockoutDurationSecs;
        $out['max_cert_validity_days'] = $this->maxCertValidityDays;
        $out['max_failed_login_attempts'] = $this->maxFailedLoginAttempts;
        $out['max_lockout_duration_secs'] = $this->maxLockoutDurationSecs;
        $out['mfa_challenge_lifetime_secs'] = $this->mfaChallengeLifetimeSecs;
        $out['mfa_enforced'] = $this->mfaEnforced;
        $out['min_length'] = $this->minLength;
        $out['password_history_count'] = $this->passwordHistoryCount;
        $out['refresh_token_lifetime_secs'] = $this->refreshTokenLifetimeSecs;
        $out['require_digits'] = $this->requireDigits;
        $out['require_lowercase'] = $this->requireLowercase;
        $out['require_symbols'] = $this->requireSymbols;
        $out['require_uppercase'] = $this->requireUppercase;
        if ($this->cimd !== null) {
            $out['cimd'] = $this->cimd->toArray();
        }
        if ($this->dcrAllowedRedirectHosts !== null) {
            $out['dcr_allowed_redirect_hosts'] = $this->dcrAllowedRedirectHosts;
        }
        if ($this->dcrAllowedScopes !== null) {
            $out['dcr_allowed_scopes'] = $this->dcrAllowedScopes;
        }
        if ($this->dcrMaxClients !== null) {
            $out['dcr_max_clients'] = $this->dcrMaxClients;
        }
        if ($this->dcrUnusedClientTtlDays !== null) {
            $out['dcr_unused_client_ttl_days'] = $this->dcrUnusedClientTtlDays;
        }
        if ($this->defaultLocale !== null) {
            $out['default_locale'] = $this->defaultLocale;
        }
        if ($this->deletionGracePeriodDays !== null) {
            $out['deletion_grace_period_days'] = $this->deletionGracePeriodDays;
        }
        if ($this->dynamicRegistration !== null) {
            $out['dynamic_registration'] = $this->dynamicRegistration;
        }
        if ($this->externalClientAllowedResources !== null) {
            $out['external_client_allowed_resources'] = $this->externalClientAllowedResources;
        }
        if ($this->opaqueKsf !== null) {
            $out['opaque_ksf'] = $this->opaqueKsf;
        }
        if ($this->opaqueMode !== null) {
            $out['opaque_mode'] = $this->opaqueMode;
        }
        if ($this->opaqueSuite !== null) {
            $out['opaque_suite'] = $this->opaqueSuite;
        }
        if ($this->sensitiveScopesEnabled !== null) {
            $out['sensitive_scopes_enabled'] = $this->sensitiveScopesEnabled;
        }
        if ($this->webauthnUserVerification !== null) {
            $out['webauthn_user_verification'] = $this->webauthnUserVerification;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
