<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Whether a settings row belongs to an organization or a tenant.
 *
 * An **open** enum. A value this SDK's copy of the spec does not list decodes to
 * `self::Unknown` rather than failing the response it arrived in (CONTRACT.md §27.11 rule 1).
 * Its own wire spelling is the empty string, which no server value is, so carrying an
 * unrecognised value back into an update is refused by the server rather than written as a
 * spelling it never used. A `match` over these cases needs an `Unknown` arm.
 */
enum SettingsScope: string
{
    /** The wire value `Org`. */
    case Org = 'Org';

    /** The wire value `Tenant`. */
    case Tenant = 'Tenant';

    /** A value this SDK's copy of the spec does not list; see the type's summary. */
    case Unknown = '';

    /**
     * Parses a wire value into a SettingsScope, mapping an unrecognised one to {@see
     * self::Unknown}.
     *
     * Never throws. A parse error here would fail the whole response the value arrived in, so
     * one unrecognised field of one record would take down the page it was on (§27.11 rule 1).
     * A `match` over this enum needs an `Unknown` arm.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? self::Unknown;
    }
}
