<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Body of `POST /api/v1/certificates/sign-csr`. No `subject` and no `key_algorithm`: both are
 * read out of the CSR, which is the only place they can be stated without the row and the
 * certificate being able to disagree. No key is returned, so there is no key field anywhere on
 * this exchange.
 */
final class SignCertificateCsrRequest implements \JsonSerializable
{
    /**
     * Constructs a SignCertificateCsrRequest.
     * @param CertificateType $certType the server's `cert_type` field
     * @param string $csrPem PEM-encoded PKCS#10 request — a `BEGIN CERTIFICATE REQUEST` block.
     *     The legacy OpenSSL `BEGIN NEW CERTIFICATE REQUEST` header is not accepted.
     * @param string $issuerCaId the server's `issuer_ca_id` field
     * @param int $validityDays Validity duration in days.
     * @param mixed $metadata the server's `metadata` field (optional)
     * @param list<SubjectAltNameVariant>|null $subjectAltNames See
     *     [`CreateCertificateRequest::subject_alt_names`]. Stated here and never in the CSR, which
     *     is still refused if it requests a `subjectAltName`. Under a CA whose key is held by
     *     `vault_pki` a `Server` request on this path is refused; use `POST /api/v1/certificates`.
     *     (optional)
     */
    public function __construct(
        public readonly CertificateType $certType,
        public readonly string $csrPem,
        public readonly string $issuerCaId,
        public readonly int $validityDays,
        public readonly mixed $metadata = null,
        public readonly ?array $subjectAltNames = null,
    ) {
    }

    /**
     * Rebuilds a SignCertificateCsrRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            CertificateType::fromWire((string) ModelDecode::need($data, 'cert_type', self::class)),
            (string) ModelDecode::need($data, 'csr_pem', self::class),
            (string) ModelDecode::need($data, 'issuer_ca_id', self::class),
            (int) ModelDecode::need($data, 'validity_days', self::class),
            isset($data['metadata']) ? $data['metadata'] : null,
            isset($data['subject_alt_names']) ? array_values(array_map(static fn (mixed $v): SubjectAltNameVariant => SubjectAltName::fromArray((array) $v), (array) $data['subject_alt_names'])) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['cert_type'] = $this->certType->value;
        $out['csr_pem'] = $this->csrPem;
        $out['issuer_ca_id'] = $this->issuerCaId;
        $out['validity_days'] = $this->validityDays;
        if ($this->metadata !== null) {
            $out['metadata'] = $this->metadata;
        }
        if ($this->subjectAltNames !== null) {
            $out['subject_alt_names'] = array_map(static fn (SubjectAltNameVariant $v): array => $v->toArray(), $this->subjectAltNames);
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
