<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A signed batch of audit log entries.
 */
final class SignedAuditBatch implements \JsonSerializable
{
    /**
     * Constructs a SignedAuditBatch.
     * @param string $batchId the server's `batch_id` field
     * @param list<string> $entryIds the server's `entry_ids` field
     * @param string $signatureArmored ASCII-armored PGP signed message containing the audit
     *     batch payload.
     * @param string $signedAt the server's `signed_at` field
     * @param string $signingKeyId the server's `signing_key_id` field
     * @param string $tenantId the server's `tenant_id` field
     */
    public function __construct(
        public readonly string $batchId,
        public readonly array $entryIds,
        public readonly string $signatureArmored,
        public readonly string $signedAt,
        public readonly string $signingKeyId,
        public readonly string $tenantId,
    ) {
    }

    /**
     * Rebuilds a SignedAuditBatch from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'batch_id', self::class),
            array_values(array_map(static fn (mixed $v): string => (string) $v, (array) ModelDecode::need($data, 'entry_ids', self::class))),
            (string) ModelDecode::need($data, 'signature_armored', self::class),
            (string) ModelDecode::need($data, 'signed_at', self::class),
            (string) ModelDecode::need($data, 'signing_key_id', self::class),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['batch_id'] = $this->batchId;
        $out['entry_ids'] = $this->entryIds;
        $out['signature_armored'] = $this->signatureArmored;
        $out['signed_at'] = $this->signedAt;
        $out['signing_key_id'] = $this->signingKeyId;
        $out['tenant_id'] = $this->tenantId;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
