<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A registered SSF stream, as the management API returns it. **The push `Authorization` header
 * is never returned**; `authorization_header_set` says whether one is stored.
 */
final class SsfStream implements \JsonSerializable
{
    /**
     * Constructs a SsfStream.
     * @param string $audience The SET `aud`. Unique across the deployment.
     * @param bool $authorizationHeaderSet Whether a push `Authorization` header is stored.
     * @param string $createdAt When the stream was registered.
     * @param SsfDeliveryMethod $deliveryMethod `push` (RFC 8935) or `poll` (RFC 8936).
     * @param list<SsfEventType> $eventsAllowed The event types the receiver may have.
     * @param list<SsfEventType> $eventsDelivered What the stream carries: the intersection of
     *     the two.
     * @param list<SsfEventType> $eventsRequested The event types the receiver asked for (a
     *     subset of `events_allowed`).
     * @param string $id The stream id, also the SSF `stream_id`.
     * @param string $receiverClientId The OAuth2 `client_id` whose client-credentials token
     *     (scope `ssf.manage`) is this stream's receiver on the stream management API.
     * @param SsfStreamStatus $status `enabled`, `paused` or `disabled`.
     * @param SsfStatusActor $statusActor Who set the status: `admin` or `receiver`.
     * @param SsfSubjectFormat $subjectFormat `iss_sub` (default) or `email`.
     * @param string $tenantId The owning tenant.
     * @param bool $transmitterActive Whether the tenant's transmitter is active: its
     *     `ssf_enabled` is on and the deployment does not make every tenant share one issuer
     *     (D-55). A stream of an inactive transmitter is kept, and carries nothing.
     * @param string $updatedAt When it was last written.
     * @param string|null $description A description. (optional)
     * @param string|null $endpointUrl The push endpoint, or null for a poll stream. (optional)
     * @param string|null $lastVerificationAt When the receiver last asked for a verification
     *     event, or null. (optional)
     * @param string|null $statusReason Why, if anyone said. (optional)
     * @param string|null $transmitterInactiveReason Why the transmitter is inactive, when it
     *     is. (optional)
     */
    public function __construct(
        public readonly string $audience,
        public readonly bool $authorizationHeaderSet,
        public readonly string $createdAt,
        public readonly SsfDeliveryMethod $deliveryMethod,
        public readonly array $eventsAllowed,
        public readonly array $eventsDelivered,
        public readonly array $eventsRequested,
        public readonly string $id,
        public readonly string $receiverClientId,
        public readonly SsfStreamStatus $status,
        public readonly SsfStatusActor $statusActor,
        public readonly SsfSubjectFormat $subjectFormat,
        public readonly string $tenantId,
        public readonly bool $transmitterActive,
        public readonly string $updatedAt,
        public readonly ?string $description = null,
        public readonly ?string $endpointUrl = null,
        public readonly ?string $lastVerificationAt = null,
        public readonly ?string $statusReason = null,
        public readonly ?string $transmitterInactiveReason = null,
    ) {
    }

    /**
     * Rebuilds a SsfStream from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'audience', self::class),
            (bool) ModelDecode::need($data, 'authorization_header_set', self::class),
            (string) ModelDecode::need($data, 'created_at', self::class),
            SsfDeliveryMethod::fromWire((string) ModelDecode::need($data, 'delivery_method', self::class)),
            array_values(array_map(static fn (mixed $v): SsfEventType => SsfEventType::fromWire((string) $v), (array) ModelDecode::need($data, 'events_allowed', self::class))),
            array_values(array_map(static fn (mixed $v): SsfEventType => SsfEventType::fromWire((string) $v), (array) ModelDecode::need($data, 'events_delivered', self::class))),
            array_values(array_map(static fn (mixed $v): SsfEventType => SsfEventType::fromWire((string) $v), (array) ModelDecode::need($data, 'events_requested', self::class))),
            (string) ModelDecode::need($data, 'id', self::class),
            (string) ModelDecode::need($data, 'receiver_client_id', self::class),
            SsfStreamStatus::fromWire((string) ModelDecode::need($data, 'status', self::class)),
            SsfStatusActor::fromWire((string) ModelDecode::need($data, 'status_actor', self::class)),
            SsfSubjectFormat::fromWire((string) ModelDecode::need($data, 'subject_format', self::class)),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            (bool) ModelDecode::need($data, 'transmitter_active', self::class),
            (string) ModelDecode::need($data, 'updated_at', self::class),
            isset($data['description']) ? (string) $data['description'] : null,
            isset($data['endpoint_url']) ? (string) $data['endpoint_url'] : null,
            isset($data['last_verification_at']) ? (string) $data['last_verification_at'] : null,
            isset($data['status_reason']) ? (string) $data['status_reason'] : null,
            isset($data['transmitter_inactive_reason']) ? (string) $data['transmitter_inactive_reason'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['audience'] = $this->audience;
        $out['authorization_header_set'] = $this->authorizationHeaderSet;
        $out['created_at'] = $this->createdAt;
        $out['delivery_method'] = $this->deliveryMethod->value;
        $out['events_allowed'] = array_map(static fn (SsfEventType $v): string => $v->value, $this->eventsAllowed);
        $out['events_delivered'] = array_map(static fn (SsfEventType $v): string => $v->value, $this->eventsDelivered);
        $out['events_requested'] = array_map(static fn (SsfEventType $v): string => $v->value, $this->eventsRequested);
        $out['id'] = $this->id;
        $out['receiver_client_id'] = $this->receiverClientId;
        $out['status'] = $this->status->value;
        $out['status_actor'] = $this->statusActor->value;
        $out['subject_format'] = $this->subjectFormat->value;
        $out['tenant_id'] = $this->tenantId;
        $out['transmitter_active'] = $this->transmitterActive;
        $out['updated_at'] = $this->updatedAt;
        if ($this->description !== null) {
            $out['description'] = $this->description;
        }
        if ($this->endpointUrl !== null) {
            $out['endpoint_url'] = $this->endpointUrl;
        }
        if ($this->lastVerificationAt !== null) {
            $out['last_verification_at'] = $this->lastVerificationAt;
        }
        if ($this->statusReason !== null) {
            $out['status_reason'] = $this->statusReason;
        }
        if ($this->transmitterInactiveReason !== null) {
            $out['transmitter_inactive_reason'] = $this->transmitterInactiveReason;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
