<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * `create_stream` and `update_stream` (a **replacement**) body.
 *
 * This is a REPLACEMENT body (§27.4 rule 5): what it omits is not preserved. The required
 * members are constructor parameters, so omitting one is a constructor error; an optional
 * member left unset is omitted from the wire and takes its default server-side. Left unset,
 * the write-only secret (`authorization_header`) is not reset but kept -- see the operation's
 * documentation for when a write must carry it.
 */
final class SsfStreamInput implements \JsonSerializable
{
    /**
     * Constructs a SsfStreamInput.
     * @param string $audience 1–512 bytes; unique across the deployment.
     * @param SsfDeliveryMethod $deliveryMethod `push` or `poll`.
     * @param list<SsfEventType> $eventsAllowed 1–6 event types.
     * @param string $receiverClientId An OAuth2 client of the tenant with the
     *     `client_credentials` grant and the `ssf.manage` scope.
     * @param \Axiam\Sdk\Core\Sensitive|null $authorizationHeader **Write-only.** The
     *     `Authorization` header value AXIAM sends to a push endpoint. On update, absent keeps the
     *     stored one — except that moving the endpoint to another origin requires it again.
     *     (optional)
     * @param bool|null $clearAuthorizationHeader On update: remove the stored header. Refused
     *     together with `authorization_header`. (optional)
     * @param string|null $description At most 256 bytes. (optional)
     * @param string|null $endpointUrl Required for `push` (an `https` URL under the outbound
     *     address policy), refused for `poll`. (optional)
     * @param list<SsfEventType>|null $eventsRequested A subset of `events_allowed`; absent
     *     means all of them. The receiver may narrow it later, never widen it. (optional)
     * @param SsfStreamStatus|null $status `enabled` by default. (optional)
     * @param string|null $statusReason At most 256 bytes. (optional)
     * @param SsfSubjectFormat|null $subjectFormat `iss_sub` by default. (optional)
     */
    public function __construct(
        public readonly string $audience,
        public readonly SsfDeliveryMethod $deliveryMethod,
        public readonly array $eventsAllowed,
        public readonly string $receiverClientId,
        public readonly ?\Axiam\Sdk\Core\Sensitive $authorizationHeader = null,
        public readonly ?bool $clearAuthorizationHeader = null,
        public readonly ?string $description = null,
        public readonly ?string $endpointUrl = null,
        public readonly ?array $eventsRequested = null,
        public readonly ?SsfStreamStatus $status = null,
        public readonly ?string $statusReason = null,
        public readonly ?SsfSubjectFormat $subjectFormat = null,
    ) {
    }

    /**
     * Rebuilds a SsfStreamInput from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'audience', self::class),
            SsfDeliveryMethod::fromWire((string) ModelDecode::need($data, 'delivery_method', self::class)),
            array_values(array_map(static fn (mixed $v): SsfEventType => SsfEventType::fromWire((string) $v), (array) ModelDecode::need($data, 'events_allowed', self::class))),
            (string) ModelDecode::need($data, 'receiver_client_id', self::class),
            isset($data['authorization_header']) ? new \Axiam\Sdk\Core\Sensitive((string) $data['authorization_header']) : null,
            isset($data['clear_authorization_header']) ? (bool) $data['clear_authorization_header'] : null,
            isset($data['description']) ? (string) $data['description'] : null,
            isset($data['endpoint_url']) ? (string) $data['endpoint_url'] : null,
            isset($data['events_requested']) ? array_values(array_map(static fn (mixed $v): SsfEventType => SsfEventType::fromWire((string) $v), (array) $data['events_requested'])) : null,
            isset($data['status']) ? SsfStreamStatus::fromWire((string) $data['status']) : null,
            isset($data['status_reason']) ? (string) $data['status_reason'] : null,
            isset($data['subject_format']) ? SsfSubjectFormat::fromWire((string) $data['subject_format']) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['audience'] = $this->audience;
        $out['delivery_method'] = $this->deliveryMethod->value;
        $out['events_allowed'] = array_map(static fn (SsfEventType $v): string => $v->value, $this->eventsAllowed);
        $out['receiver_client_id'] = $this->receiverClientId;
        if ($this->authorizationHeader !== null) {
            $out['authorization_header'] = $this->authorizationHeader;
        }
        if ($this->clearAuthorizationHeader !== null) {
            $out['clear_authorization_header'] = $this->clearAuthorizationHeader;
        }
        if ($this->description !== null) {
            $out['description'] = $this->description;
        }
        if ($this->endpointUrl !== null) {
            $out['endpoint_url'] = $this->endpointUrl;
        }
        if ($this->eventsRequested !== null) {
            $out['events_requested'] = array_map(static fn (SsfEventType $v): string => $v->value, $this->eventsRequested);
        }
        if ($this->status !== null) {
            $out['status'] = $this->status->value;
        }
        if ($this->statusReason !== null) {
            $out['status_reason'] = $this->statusReason;
        }
        if ($this->subjectFormat !== null) {
            $out['subject_format'] = $this->subjectFormat->value;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
