<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * A name to put in a `Server` certificate's `subjectAltName`. Stated explicitly in the
 * request, never read from a CSR: a CSR asking for a `subjectAltName` extension is still
 * refused. URI and e-mail names are not offered — nothing in AXIAM consumes them yet.
 *
 * The decoder for the externally-tagged union. Every arm is a SubjectAltNameVariant; this
 * class exists only to pick the right one, by which of `dns`, `ip` the wire object carries.
 */
final class SubjectAltName
{
    /**
     * Decodes one externally-tagged SubjectAltName object into its variant.
     * @param array<string,mixed> $data The raw wire object.
     * @throws \Axiam\Sdk\Core\AxiamException when none of `dns`, `ip` is present.
     */
    public static function fromArray(array $data): SubjectAltNameVariant
    {
        if (array_key_exists('dns', $data)) {
            return SubjectAltNameDns::fromArray($data);
        }
        if (array_key_exists('ip', $data)) {
            return SubjectAltNameIp::fromArray($data);
        }

        throw new \Axiam\Sdk\Core\AxiamException(sprintf(
            'unknown SubjectAltName: none of %s is present',
            implode(', ', ['dns', 'ip']),
        ));
    }
}
