<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Partial tenant overrides. `None` = inherit from org baseline.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left
 * unchanged, and is omitted from the wire request entirely rather than sent as null (§27.4
 * rule 5).
 */
final class TenantSettingsOverride implements \JsonSerializable
{
    /**
     * Constructs a TenantSettingsOverride.
     * @param int|null $accessTokenLifetimeSecs the server's `access_token_lifetime_secs` field
     *     (optional)
     * @param bool|null $adminNotificationsEnabled the server's `admin_notifications_enabled`
     *     field (optional)
     * @param int|null $defaultCertValidityDays the server's `default_cert_validity_days` field
     *     (optional)
     * @param int|null $deletionGracePeriodDays the server's `deletion_grace_period_days` field
     *     (optional)
     * @param int|null $emailVerificationGracePeriodHours the server's
     *     `email_verification_grace_period_hours` field (optional)
     * @param bool|null $emailVerificationRequired the server's `email_verification_required`
     *     field (optional)
     * @param bool|null $hibpCheckEnabled the server's `hibp_check_enabled` field (optional)
     * @param float|null $lockoutBackoffMultiplier the server's `lockout_backoff_multiplier`
     *     field (optional)
     * @param int|null $lockoutDurationSecs the server's `lockout_duration_secs` field
     *     (optional)
     * @param int|null $maxCertValidityDays the server's `max_cert_validity_days` field
     *     (optional)
     * @param int|null $maxFailedLoginAttempts the server's `max_failed_login_attempts` field
     *     (optional)
     * @param int|null $maxLockoutDurationSecs the server's `max_lockout_duration_secs` field
     *     (optional)
     * @param int|null $mfaChallengeLifetimeSecs the server's `mfa_challenge_lifetime_secs`
     *     field (optional)
     * @param bool|null $mfaEnforced the server's `mfa_enforced` field (optional)
     * @param int|null $minLength the server's `min_length` field (optional)
     * @param string|null $opaqueKsf the server's `opaque_ksf` field (optional)
     * @param string|null $opaqueMode the server's `opaque_mode` field (optional)
     * @param string|null $opaqueSuite the server's `opaque_suite` field (optional)
     * @param int|null $passwordHistoryCount the server's `password_history_count` field
     *     (optional)
     * @param int|null $refreshTokenLifetimeSecs the server's `refresh_token_lifetime_secs`
     *     field (optional)
     * @param bool|null $requireDigits the server's `require_digits` field (optional)
     * @param bool|null $requireLowercase the server's `require_lowercase` field (optional)
     * @param bool|null $requireSymbols the server's `require_symbols` field (optional)
     * @param bool|null $requireUppercase the server's `require_uppercase` field (optional)
     */
    public function __construct(
        public readonly ?int $accessTokenLifetimeSecs = null,
        public readonly ?bool $adminNotificationsEnabled = null,
        public readonly ?int $defaultCertValidityDays = null,
        public readonly ?int $deletionGracePeriodDays = null,
        public readonly ?int $emailVerificationGracePeriodHours = null,
        public readonly ?bool $emailVerificationRequired = null,
        public readonly ?bool $hibpCheckEnabled = null,
        public readonly ?float $lockoutBackoffMultiplier = null,
        public readonly ?int $lockoutDurationSecs = null,
        public readonly ?int $maxCertValidityDays = null,
        public readonly ?int $maxFailedLoginAttempts = null,
        public readonly ?int $maxLockoutDurationSecs = null,
        public readonly ?int $mfaChallengeLifetimeSecs = null,
        public readonly ?bool $mfaEnforced = null,
        public readonly ?int $minLength = null,
        public readonly ?string $opaqueKsf = null,
        public readonly ?string $opaqueMode = null,
        public readonly ?string $opaqueSuite = null,
        public readonly ?int $passwordHistoryCount = null,
        public readonly ?int $refreshTokenLifetimeSecs = null,
        public readonly ?bool $requireDigits = null,
        public readonly ?bool $requireLowercase = null,
        public readonly ?bool $requireSymbols = null,
        public readonly ?bool $requireUppercase = null,
    ) {
    }

    /**
     * Rebuilds a TenantSettingsOverride from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            isset($data['access_token_lifetime_secs']) ? (int) $data['access_token_lifetime_secs'] : null,
            isset($data['admin_notifications_enabled']) ? (bool) $data['admin_notifications_enabled'] : null,
            isset($data['default_cert_validity_days']) ? (int) $data['default_cert_validity_days'] : null,
            isset($data['deletion_grace_period_days']) ? (int) $data['deletion_grace_period_days'] : null,
            isset($data['email_verification_grace_period_hours']) ? (int) $data['email_verification_grace_period_hours'] : null,
            isset($data['email_verification_required']) ? (bool) $data['email_verification_required'] : null,
            isset($data['hibp_check_enabled']) ? (bool) $data['hibp_check_enabled'] : null,
            isset($data['lockout_backoff_multiplier']) ? (float) $data['lockout_backoff_multiplier'] : null,
            isset($data['lockout_duration_secs']) ? (int) $data['lockout_duration_secs'] : null,
            isset($data['max_cert_validity_days']) ? (int) $data['max_cert_validity_days'] : null,
            isset($data['max_failed_login_attempts']) ? (int) $data['max_failed_login_attempts'] : null,
            isset($data['max_lockout_duration_secs']) ? (int) $data['max_lockout_duration_secs'] : null,
            isset($data['mfa_challenge_lifetime_secs']) ? (int) $data['mfa_challenge_lifetime_secs'] : null,
            isset($data['mfa_enforced']) ? (bool) $data['mfa_enforced'] : null,
            isset($data['min_length']) ? (int) $data['min_length'] : null,
            isset($data['opaque_ksf']) ? (string) $data['opaque_ksf'] : null,
            isset($data['opaque_mode']) ? (string) $data['opaque_mode'] : null,
            isset($data['opaque_suite']) ? (string) $data['opaque_suite'] : null,
            isset($data['password_history_count']) ? (int) $data['password_history_count'] : null,
            isset($data['refresh_token_lifetime_secs']) ? (int) $data['refresh_token_lifetime_secs'] : null,
            isset($data['require_digits']) ? (bool) $data['require_digits'] : null,
            isset($data['require_lowercase']) ? (bool) $data['require_lowercase'] : null,
            isset($data['require_symbols']) ? (bool) $data['require_symbols'] : null,
            isset($data['require_uppercase']) ? (bool) $data['require_uppercase'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->accessTokenLifetimeSecs !== null) {
            $out['access_token_lifetime_secs'] = $this->accessTokenLifetimeSecs;
        }
        if ($this->adminNotificationsEnabled !== null) {
            $out['admin_notifications_enabled'] = $this->adminNotificationsEnabled;
        }
        if ($this->defaultCertValidityDays !== null) {
            $out['default_cert_validity_days'] = $this->defaultCertValidityDays;
        }
        if ($this->deletionGracePeriodDays !== null) {
            $out['deletion_grace_period_days'] = $this->deletionGracePeriodDays;
        }
        if ($this->emailVerificationGracePeriodHours !== null) {
            $out['email_verification_grace_period_hours'] = $this->emailVerificationGracePeriodHours;
        }
        if ($this->emailVerificationRequired !== null) {
            $out['email_verification_required'] = $this->emailVerificationRequired;
        }
        if ($this->hibpCheckEnabled !== null) {
            $out['hibp_check_enabled'] = $this->hibpCheckEnabled;
        }
        if ($this->lockoutBackoffMultiplier !== null) {
            $out['lockout_backoff_multiplier'] = $this->lockoutBackoffMultiplier;
        }
        if ($this->lockoutDurationSecs !== null) {
            $out['lockout_duration_secs'] = $this->lockoutDurationSecs;
        }
        if ($this->maxCertValidityDays !== null) {
            $out['max_cert_validity_days'] = $this->maxCertValidityDays;
        }
        if ($this->maxFailedLoginAttempts !== null) {
            $out['max_failed_login_attempts'] = $this->maxFailedLoginAttempts;
        }
        if ($this->maxLockoutDurationSecs !== null) {
            $out['max_lockout_duration_secs'] = $this->maxLockoutDurationSecs;
        }
        if ($this->mfaChallengeLifetimeSecs !== null) {
            $out['mfa_challenge_lifetime_secs'] = $this->mfaChallengeLifetimeSecs;
        }
        if ($this->mfaEnforced !== null) {
            $out['mfa_enforced'] = $this->mfaEnforced;
        }
        if ($this->minLength !== null) {
            $out['min_length'] = $this->minLength;
        }
        if ($this->opaqueKsf !== null) {
            $out['opaque_ksf'] = $this->opaqueKsf;
        }
        if ($this->opaqueMode !== null) {
            $out['opaque_mode'] = $this->opaqueMode;
        }
        if ($this->opaqueSuite !== null) {
            $out['opaque_suite'] = $this->opaqueSuite;
        }
        if ($this->passwordHistoryCount !== null) {
            $out['password_history_count'] = $this->passwordHistoryCount;
        }
        if ($this->refreshTokenLifetimeSecs !== null) {
            $out['refresh_token_lifetime_secs'] = $this->refreshTokenLifetimeSecs;
        }
        if ($this->requireDigits !== null) {
            $out['require_digits'] = $this->requireDigits;
        }
        if ($this->requireLowercase !== null) {
            $out['require_lowercase'] = $this->requireLowercase;
        }
        if ($this->requireSymbols !== null) {
            $out['require_symbols'] = $this->requireSymbols;
        }
        if ($this->requireUppercase !== null) {
            $out['require_uppercase'] = $this->requireUppercase;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
