<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Lifecycle status of a tenant. A `Suspended` tenant remains stored and its data isolated, but
 * is treated as administratively disabled. New tenants are `Active` by default.
 */
enum TenantStatus: string
{
    /** The wire value `Active`. */
    case Active = 'Active';

    /** The wire value `Suspended`. */
    case Suspended = 'Suspended';

    /**
     * Parses a wire value into a TenantStatus.
     *
     * Throws on an unrecognised value rather than defaulting to a case: a server that has
     * learned a new state should surface as a loud error, not as whichever case was declared
     * first.
     * @throws \Axiam\Sdk\Core\AxiamException when `$value` is not a known case.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? throw new \Axiam\Sdk\Core\AxiamException(
            sprintf('unknown TenantStatus value "%s" — the server may be newer than this SDK', $value),
        );
    }
}
