<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * X4 trust for exchanging this provider's tokens (RFC 8693, external issuer). Mirrors
 * [`TokenExchangeTrust`] on the wire rather than reusing it directly so the API surface can
 * carry its own defaults: an admin PUTting a partial block gets the documented default for
 * anything they omitted, instead of a deserialization error listing fields they have never
 * heard of.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left
 * unchanged, and is omitted from the wire request entirely rather than sent as null (§27.4
 * rule 5).
 */
final class TokenExchangeTrustRequest implements \JsonSerializable
{
    /**
     * Constructs a TokenExchangeTrustRequest.
     * @param list<string>|null $acceptedAudiences Audiences an incoming subject token may
     *     name. Required (non-empty) when `enabled`; there is deliberately no accept-all value.
     *     (optional)
     * @param bool|null $enabled Off unless explicitly enabled. Configuring a provider for
     *     *login* is not agreement to accept its tokens as API credentials. (optional)
     * @param int|null $maxLifetimeSecs Per-provider ceiling on the issued AXIAM token's
     *     lifetime. (optional)
     * @param int|null $maxTokenAgeSecs Bound on `now - iat`, independent of the token's own
     *     `exp`. (optional)
     * @param array<string,mixed>|null $scopeMap External asserted value -> AXIAM scopes.
     *     Deny-by-default: an external value with no entry contributes nothing. (optional)
     * @param string|null $subjectMapping `linked_only` (default) or `jit_provision`.
     *     (optional)
     */
    public function __construct(
        public readonly ?array $acceptedAudiences = null,
        public readonly ?bool $enabled = null,
        public readonly ?int $maxLifetimeSecs = null,
        public readonly ?int $maxTokenAgeSecs = null,
        public readonly ?array $scopeMap = null,
        public readonly ?string $subjectMapping = null,
    ) {
    }

    /**
     * Rebuilds a TokenExchangeTrustRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            isset($data['accepted_audiences']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['accepted_audiences'])) : null,
            isset($data['enabled']) ? (bool) $data['enabled'] : null,
            isset($data['max_lifetime_secs']) ? (int) $data['max_lifetime_secs'] : null,
            isset($data['max_token_age_secs']) ? (int) $data['max_token_age_secs'] : null,
            isset($data['scope_map']) ? (array) $data['scope_map'] : null,
            isset($data['subject_mapping']) ? (string) $data['subject_mapping'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->acceptedAudiences !== null) {
            $out['accepted_audiences'] = $this->acceptedAudiences;
        }
        if ($this->enabled !== null) {
            $out['enabled'] = $this->enabled;
        }
        if ($this->maxLifetimeSecs !== null) {
            $out['max_lifetime_secs'] = $this->maxLifetimeSecs;
        }
        if ($this->maxTokenAgeSecs !== null) {
            $out['max_token_age_secs'] = $this->maxTokenAgeSecs;
        }
        if ($this->scopeMap !== null) {
            $out['scope_map'] = $this->scopeMap;
        }
        if ($this->subjectMapping !== null) {
            $out['subject_mapping'] = $this->subjectMapping;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
