<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * What to do with an AAGUID that has no MDS entry (i.e. FIDO Alliance has no metadata for it —
 * not necessarily malicious, MDS coverage is incomplete for some legitimate authenticators).
 */
enum UnknownAaguidAction: string
{
    /** The wire value `allow`. */
    case Allow = 'allow';

    /** The wire value `deny`. */
    case Deny = 'deny';

    /**
     * Parses a wire value into a UnknownAaguidAction.
     *
     * Throws on an unrecognised value rather than defaulting to a case: a server that has
     * learned a new state should surface as a loud error, not as whichever case was declared
     * first.
     * @throws \Axiam\Sdk\Core\AxiamException when `$value` is not a known case.
     */
    public static function fromWire(string $value): self
    {
        return self::tryFrom($value) ?? throw new \Axiam\Sdk\Core\AxiamException(
            sprintf('unknown UnknownAaguidAction value "%s" — the server may be newer than this SDK', $value),
        );
    }
}
