<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `UpdateGroup` schema from the server's OpenAPI document.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left
 * unchanged, and is omitted from the wire request entirely rather than sent as null (§27.4
 * rule 5).
 */
final class UpdateGroup implements \JsonSerializable
{
    /**
     * Constructs a UpdateGroup.
     * @param string|null $description the server's `description` field (optional)
     * @param mixed $metadata the server's `metadata` field (optional)
     * @param string|null $name the server's `name` field (optional)
     */
    public function __construct(
        public readonly ?string $description = null,
        public readonly mixed $metadata = null,
        public readonly ?string $name = null,
    ) {
    }

    /**
     * Rebuilds a UpdateGroup from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            isset($data['description']) ? (string) $data['description'] : null,
            isset($data['metadata']) ? $data['metadata'] : null,
            isset($data['name']) ? (string) $data['name'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->description !== null) {
            $out['description'] = $this->description;
        }
        if ($this->metadata !== null) {
            $out['metadata'] = $this->metadata;
        }
        if ($this->name !== null) {
            $out['name'] = $this->name;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
