<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * The `UpdateFederationConfigRequest` schema from the server's OpenAPI document.
 *
 * Every property is optional, so this is a SPARSE body: what you leave unset is left
 * unchanged, and is omitted from the wire request entirely rather than sent as null (§27.4
 * rule 5).
 */
final class UpdateFederationConfigRequest implements \JsonSerializable
{
    /**
     * Constructs a UpdateFederationConfigRequest.
     * @param list<string>|null $allowedAlgorithms Accepted signature algorithms (CQ-B40/REQ-14
     *     AC-5). (optional)
     * @param mixed $attributeMap the server's `attribute_map` field (optional)
     * @param string|null $clientId the server's `client_id` field (optional)
     * @param \Axiam\Sdk\Core\Sensitive|null $clientSecret the server's `client_secret` field —
     *     a one-time secret (§27.5) (optional)
     * @param bool|null $enabled the server's `enabled` field (optional)
     * @param string|null $idpSigningCertPem PEM-encoded X.509 certificate for verifying SAML
     *     assertions (CQ-B40/REQ-14 AC-5). `Some(None)` clears the stored cert. (optional)
     * @param string|null $metadataUrl the server's `metadata_url` field (optional)
     * @param string|null $provider the server's `provider` field (optional)
     * @param TokenExchangeTrustRequest|null $tokenExchange the server's `token_exchange` field
     *     (optional)
     */
    public function __construct(
        public readonly ?array $allowedAlgorithms = null,
        public readonly mixed $attributeMap = null,
        public readonly ?string $clientId = null,
        public readonly ?\Axiam\Sdk\Core\Sensitive $clientSecret = null,
        public readonly ?bool $enabled = null,
        public readonly ?string $idpSigningCertPem = null,
        public readonly ?string $metadataUrl = null,
        public readonly ?string $provider = null,
        public readonly ?TokenExchangeTrustRequest $tokenExchange = null,
    ) {
    }

    /**
     * Rebuilds a UpdateFederationConfigRequest from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            isset($data['allowed_algorithms']) ? array_values(array_map(static fn (mixed $v): string => (string) $v, (array) $data['allowed_algorithms'])) : null,
            isset($data['attribute_map']) ? $data['attribute_map'] : null,
            isset($data['client_id']) ? (string) $data['client_id'] : null,
            isset($data['client_secret']) ? new \Axiam\Sdk\Core\Sensitive((string) $data['client_secret']) : null,
            isset($data['enabled']) ? (bool) $data['enabled'] : null,
            isset($data['idp_signing_cert_pem']) ? (string) $data['idp_signing_cert_pem'] : null,
            isset($data['metadata_url']) ? (string) $data['metadata_url'] : null,
            isset($data['provider']) ? (string) $data['provider'] : null,
            isset($data['token_exchange']) ? TokenExchangeTrustRequest::fromArray((array) $data['token_exchange']) : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        if ($this->allowedAlgorithms !== null) {
            $out['allowed_algorithms'] = $this->allowedAlgorithms;
        }
        if ($this->attributeMap !== null) {
            $out['attribute_map'] = $this->attributeMap;
        }
        if ($this->clientId !== null) {
            $out['client_id'] = $this->clientId;
        }
        if ($this->clientSecret !== null) {
            $out['client_secret'] = $this->clientSecret;
        }
        if ($this->enabled !== null) {
            $out['enabled'] = $this->enabled;
        }
        if ($this->idpSigningCertPem !== null) {
            $out['idp_signing_cert_pem'] = $this->idpSigningCertPem;
        }
        if ($this->metadataUrl !== null) {
            $out['metadata_url'] = $this->metadataUrl;
        }
        if ($this->provider !== null) {
            $out['provider'] = $this->provider;
        }
        if ($this->tokenExchange !== null) {
            $out['token_exchange'] = $this->tokenExchange->toArray();
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
