<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Public-safe user representation (no password_hash, no mfa_secret).
 */
final class UserResponse implements \JsonSerializable
{
    /**
     * Constructs a UserResponse.
     * @param string $createdAt the server's `created_at` field
     * @param string $email the server's `email` field
     * @param bool $emailVerified True when the user's email address has been verified
     *     (`email_verified_at` is set). Exposed for the admin UI / profile.
     * @param int $failedLoginAttempts Number of consecutive failed login attempts.
     * @param string $id the server's `id` field
     * @param bool $isLocked Whether the account is currently locked (locked_until is in the
     *     future).
     * @param mixed $metadata the server's `metadata` field
     * @param bool $mfaEnabled the server's `mfa_enabled` field
     * @param UserStatus $status the server's `status` field
     * @param string $tenantId the server's `tenant_id` field
     * @param string $updatedAt the server's `updated_at` field
     * @param string $username the server's `username` field
     * @param string|null $lockedUntil Timestamp until which the account is locked, if any.
     *     (optional)
     */
    public function __construct(
        public readonly string $createdAt,
        public readonly string $email,
        public readonly bool $emailVerified,
        public readonly int $failedLoginAttempts,
        public readonly string $id,
        public readonly bool $isLocked,
        public readonly mixed $metadata,
        public readonly bool $mfaEnabled,
        public readonly UserStatus $status,
        public readonly string $tenantId,
        public readonly string $updatedAt,
        public readonly string $username,
        public readonly ?string $lockedUntil = null,
    ) {
    }

    /**
     * Rebuilds a UserResponse from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'created_at', self::class),
            (string) ModelDecode::need($data, 'email', self::class),
            (bool) ModelDecode::need($data, 'email_verified', self::class),
            (int) ModelDecode::need($data, 'failed_login_attempts', self::class),
            (string) ModelDecode::need($data, 'id', self::class),
            (bool) ModelDecode::need($data, 'is_locked', self::class),
            ModelDecode::need($data, 'metadata', self::class),
            (bool) ModelDecode::need($data, 'mfa_enabled', self::class),
            UserStatus::fromWire((string) ModelDecode::need($data, 'status', self::class)),
            (string) ModelDecode::need($data, 'tenant_id', self::class),
            (string) ModelDecode::need($data, 'updated_at', self::class),
            (string) ModelDecode::need($data, 'username', self::class),
            isset($data['locked_until']) ? (string) $data['locked_until'] : null,
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['created_at'] = $this->createdAt;
        $out['email'] = $this->email;
        $out['email_verified'] = $this->emailVerified;
        $out['failed_login_attempts'] = $this->failedLoginAttempts;
        $out['id'] = $this->id;
        $out['is_locked'] = $this->isLocked;
        $out['metadata'] = $this->metadata;
        $out['mfa_enabled'] = $this->mfaEnabled;
        $out['status'] = $this->status->value;
        $out['tenant_id'] = $this->tenantId;
        $out['updated_at'] = $this->updatedAt;
        $out['username'] = $this->username;
        if ($this->lockedUntil !== null) {
            $out['locked_until'] = $this->lockedUntil;
        }

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
