<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * Which directory attribute feeds each AXIAM user field.
 */
final class UserAttributeMap implements \JsonSerializable
{
    /**
     * Constructs a UserAttributeMap.
     * @param string $displayName The attribute holding the human-readable name.
     * @param string $email The attribute holding the e-mail address.
     * @param string $externalId The attribute holding the immutable entry identifier
     *     (`entryUUID`, `objectGUID`).
     * @param string $username The attribute holding the login name (`uid`, `sAMAccountName`).
     */
    public function __construct(
        public readonly string $displayName,
        public readonly string $email,
        public readonly string $externalId,
        public readonly string $username,
    ) {
    }

    /**
     * Rebuilds a UserAttributeMap from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'display_name', self::class),
            (string) ModelDecode::need($data, 'email', self::class),
            (string) ModelDecode::need($data, 'external_id', self::class),
            (string) ModelDecode::need($data, 'username', self::class),
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['display_name'] = $this->displayName;
        $out['email'] = $this->email;
        $out['external_id'] = $this->externalId;
        $out['username'] = $this->username;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
