<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

namespace Axiam\Sdk\Management\Models;

/**
 * WebAuthn ceremony policy. One field today. It is a struct rather than a bare field on
 * [`SecuritySettings`] so that the next WebAuthn control has an obvious home, and so the admin
 * UI can group them. The *attestation* policy is deliberately not here: it lives in
 * [`crate::models::webauthn_policy::WebauthnAttestationPolicy`], is tenant-only, and cannot
 * join this model because AAGUID allow/block lists have no "more restrictive than" ordering to
 * validate an override against. User verification does, so it can.
 */
final class WebauthnPolicy implements \JsonSerializable
{
    /**
     * Constructs a WebauthnPolicy.
     * @param string $webauthnUserVerification How hard the authenticator must prove *who* is
     *     present. Applies to enrolment and to second-factor authentication. Usernameless sign-in
     *     is held to `required` whatever this says — see [`WebauthnUserVerification`].
     */
    public function __construct(
        public readonly string $webauthnUserVerification,
    ) {
    }

    /**
     * Rebuilds a WebauthnPolicy from one decoded JSON object.
     * @param array<string,mixed> $data The raw wire object.
     */
    public static function fromArray(array $data): self
    {
        return new self(
            (string) ModelDecode::need($data, 'webauthn_user_verification', self::class),
        );
    }

    /**
     * Renders this object back to its wire form.
     *
     * §27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse update those
     * two say opposite things — "leave this alone" versus "set this to nothing" — and only
     * omission means the first.
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        $out = [];
        $out['webauthn_user_verification'] = $this->webauthnUserVerification;

        return $out;
    }

    /**
     * Renders this object for `json_encode()`.
     *
     * Any {@see \Axiam\Sdk\Core\Sensitive} it carries stays WRAPPED here, so a log line or a
     * `json_encode($model)` in application code prints `[SENSITIVE]`. The one place a secret
     * is revealed is {@see \Axiam\Sdk\Management\ManagementTransport}, on the way to the wire
     * and nowhere else (§27.5).
     * @return array<string,mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
