#!/usr/bin/env python3
"""Generate the CONTRACT §27 management surface for the PHP SDK.

Reads ``management-registry.json`` (the 146 operations across 24 namespaces,
maintained in ``ilpanich/axiam`` and vendored here) plus ``openapi.json`` for the
schemas those operations carry, and writes:

- ``src/Management/Models/*.php`` — one ``final class``, ``enum`` or polymorphic base
  per request and response type, one class per file so PSR-4 can autoload it;
- ``src/Management/<Namespace>Api.php`` — one namespace handle per namespace (§27.2);
- ``src/Management/ManagementApi.php`` — the 24 accessors;
- ``tests/Management/ManagementSurfaceGeneratedTest.php``
- ``tests/Management/ManagementSparseBodiesGeneratedTest.php``
  — one conformance case per operation, plus the §27.9 assertion that all 146 are
  reached.

Run with ``--check`` to verify the committed output is current; that is what CI runs,
so a registry change that is not regenerated fails the build rather than shipping a
surface that disagrees with the contract.

Everything this emits must satisfy two gates this repo runs and most siblings do not:
``tools/docblock-coverage.php`` requires a docblock on EVERY public class and method
under ``src/``, and PHPStan runs at level 6, which wants the value type of every array
spelled out. Both are why the emitters below carry so much ``@param``/``@return``
plumbing: a generated file is held to the same bar as a hand-written one.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY: dict[str, Any] = json.loads((ROOT / "management-registry.json").read_text())
SPEC: dict[str, Any] = json.loads((ROOT / "openapi.json").read_text())
SCHEMAS: dict[str, Any] = SPEC["components"]["schemas"]

BANNER = """<?php

declare(strict_types=1);

// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
"""

# §27.4 rule 3: `{org_id}` always defaults from the client. `{tenant_id}`
# defaults from the client only where it names the *context*; in `tenants` and
# the signing-CA routes it names the object being acted on.
IMPLICIT_TENANT_NAMESPACES = {"email_config", "settings", "webauthn_policy"}

# Schema names that would collide with a type this SDK already exports. The models
# live in their own PHP namespace (Axiam\Sdk\Management\Models), so a collision can
# only happen against another MODEL -- which the spec itself prevents.
RENAMED_SCHEMAS: dict[str, str] = {}

EXAMPLE_UUID = "11111111-1111-4111-8111-111111111111"
EXAMPLE_TIME = "2026-08-26T00:00:00Z"


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------


def pascal(text: str) -> str:
    """``service_accounts`` -> ``ServiceAccounts``; already-Pascal input is kept.

    Deliberately does NOT normalise initialisms, so every generated type name can be
    grepped straight out of ``openapi.json``.
    """
    if "_" not in text and "-" not in text and text[:1].isupper():
        return RENAMED_SCHEMAS.get(text, text)
    parts = [p for p in text.replace("-", "_").replace(" ", "_").split("_") if p]
    joined = "".join(p[0].upper() + p[1:] for p in parts)
    return RENAMED_SCHEMAS.get(joined, joined)


def camel(text: str) -> str:
    """``service_accounts`` -> ``serviceAccounts``; the PHP property spelling."""
    out = pascal(text)
    return out[0].lower() + out[1:] if out else out


# PHP reserved words that cannot be used bare as a method name on a class.
# (Property names are far less restricted, but methods share the keyword space.)
PHP_KEYWORDS = {
    "abstract", "and", "array", "as", "break", "callable", "case", "catch",
    "class", "clone", "const", "continue", "declare", "default", "do", "echo",
    "else", "elseif", "empty", "enddeclare", "endfor", "endforeach", "endif",
    "endswitch", "endwhile", "enum", "eval", "exit", "extends", "final",
    "finally", "fn", "for", "foreach", "function", "global", "goto", "if",
    "implements", "include", "instanceof", "insteadof", "interface", "isset",
    "list", "match", "namespace", "new", "or", "print", "private", "protected",
    "public", "readonly", "require", "return", "static", "switch", "throw",
    "trait", "try", "unset", "use", "var", "while", "xor", "yield",
}


def prop(name: str) -> str:
    """A PHP property name for a wire field. Properties may be keywords; methods may not."""
    return camel(name)


def method(name: str) -> str:
    """A PHP-legal method name for ``name``.

    ``list`` is a language construct and cannot be a bare method name in the PHP
    versions this SDK supports, and it is also the single most common §27 operation
    name -- so the suffix rule earns its keep on the very first namespace.
    """
    ident = camel(name)
    return f"{ident}Items" if ident.lower() in PHP_KEYWORDS else ident


def snake(text: str) -> str:
    """``ServiceAccounts`` -> ``service_accounts``; already-snake input is kept."""
    out: list[str] = []
    for i, ch in enumerate(text):
        boundary = not text[i - 1].isupper() or (i + 1 < len(text) and text[i + 1].islower())
        if ch.isupper() and i and boundary:
            out.append("_")
        out.append(ch.lower())
    return "".join(out).replace("-", "_").replace("__", "_")


def wrap(text: str, width: int = 76) -> list[str]:
    """Reflow ``text`` into paragraph-preserving lines."""
    out: list[str] = []
    for para in str(text).strip().split("\n\n"):
        words = para.split()
        if not words:
            continue
        line = ""
        for word in words:
            if line and len(line) + 1 + len(word) > width:
                out.append(line)
                line = word
            else:
                line = f"{line} {word}" if line else word
        if line:
            out.append(line)
        out.append("")
    while out and out[-1] == "":
        out.pop()
    return out


def escape(text: str) -> str:
    """Make an ``openapi.json`` description safe to paste into a PHP docblock.

    A docblock is delimited by ``*/``, so a description containing one would close the
    comment early and spill the rest into code -- the PHP analogue of the nested-KDoc
    bug the Kotlin port hit. Both ``*/`` and ``/*`` are neutralised.
    """
    out = " ".join(str(text).split())
    return out.replace("*/", "* /").replace("/*", "/ *")


def docblock(text: str, indent: str = "", tags: list[str] | None = None) -> list[str]:
    """A wrapped docblock at ``indent``, with optional trailing ``@``-tag lines."""
    paragraphs = [p for p in str(text).split("\n\n") if p.strip()]
    width = 92 - len(indent)
    out = [f"{indent}/**"]
    first = True
    for para in paragraphs or [""]:
        if not first:
            out.append(f"{indent} *")
        for line in wrap(para, width):
            out.append(f"{indent} * {line}".rstrip())
        first = False
    for tag in tags or []:
        lines = wrap(tag, width)
        out.append(f"{indent} * {lines[0]}")
        out.extend(f"{indent} *     {more}" for more in lines[1:])
    out.append(f"{indent} */")
    return out


def inline_doc(text: str, indent: str = "") -> list[str]:
    """A one-line docblock, or a wrapped block when it will not fit."""
    single = f"{indent}/** {text} */"
    if len(single) <= 100 and "\n" not in text:
        return [single]
    return docblock(text, indent)


def resolve_ref(schema: Any) -> Any:
    """Follow ``$ref`` chains to the schema they name."""
    node = schema
    while isinstance(node, dict) and "$ref" in node:
        node = SCHEMAS.get(node["$ref"].split("/")[-1], {})
    return node


def nullable_ref(schema: Any) -> str | None:
    """``{oneOf: [{type: null}, {$ref: X}]}`` -- utoipa's optional-enum shape."""
    variants = schema.get("oneOf") if isinstance(schema, dict) else None
    if not isinstance(variants, list) or len(variants) != 2:
        return None
    nulls = [v for v in variants if v.get("type") == "null"]
    refs = [v for v in variants if "$ref" in v]
    return refs[0]["$ref"].split("/")[-1] if len(nulls) == 1 and len(refs) == 1 else None


def flatten(name: str) -> tuple[dict[str, Any], set[str], str | None]:
    """Properties, required set and description of ``name``, ``allOf`` resolved."""
    props: dict[str, Any] = {}
    required: set[str] = set()

    def absorb(node: Any) -> None:
        """Merge one ``allOf`` member's properties into the accumulator."""
        resolved = resolve_ref(node) if "$ref" in node else node
        props.update(resolved.get("properties") or {})
        required.update(resolved.get("required") or [])
        for sub in resolved.get("allOf") or []:
            absorb(sub)

    schema = SCHEMAS.get(name, {})
    absorb(schema)
    return props, required, schema.get("description")


def discriminated(schema: Any) -> tuple[str, list[tuple[str, Any]]] | None:
    """Detect an internally-tagged union and return ``(tag, [(value, payload)])``."""
    variants = schema.get("oneOf")
    if not isinstance(variants, list) or len(variants) < 2:
        return None
    tag: str | None = None
    arms: list[tuple[str, Any]] = []
    for variant in variants:
        parts = variant.get("allOf") or [variant]
        value: str | None = None
        payload: Any = None
        leftovers: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
        for part in parts:
            if "$ref" in part:
                payload = part
                continue
            for pname, pschema in (part.get("properties") or {}).items():
                enum = pschema.get("enum")
                if pschema.get("type") == "string" and isinstance(enum, list) and len(enum) == 1:
                    if tag and tag != pname:
                        return None
                    tag = pname
                    value = enum[0]
                else:
                    leftovers["properties"][pname] = pschema
                    if pname in (part.get("required") or []):
                        leftovers["required"].append(pname)
        if value is None:
            return None
        arms.append((value, payload if payload is not None else leftovers))
    return (tag or "", arms)


def sensitive_map() -> dict[str, set[str]]:
    """Which fields of which schemas carry a secret, per the registry."""
    out: dict[str, set[str]] = {}
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"] and op["sensitive_request_fields"]:
                key = op["request_schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_request_fields"])
            if op["response"]["schema"] and op["sensitive_response_fields"]:
                key = op["response"]["schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_response_fields"])
    return out


def schema_closure() -> list[str]:
    """Every schema reachable from an operation, transitively, sorted."""
    seeds: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"]:
                seeds.add(op["request_schema"].lstrip("[]"))
            if op["response"]["schema"]:
                seeds.add(op["response"]["schema"].lstrip("[]"))

    def refs_in(node: Any, found: set[str]) -> None:
        """Collect every ``$ref`` target name appearing anywhere under ``node``."""
        if isinstance(node, list):
            for item in node:
                refs_in(item, found)
        elif isinstance(node, dict):
            if "$ref" in node:
                found.add(node["$ref"].split("/")[-1])
            for value in node.values():
                refs_in(value, found)

    seen: set[str] = set()
    frontier = list(seeds)
    while frontier:
        name = frontier.pop()
        if name in seen or name not in SCHEMAS:
            continue
        seen.add(name)
        found: set[str] = set()
        refs_in(SCHEMAS[name], found)
        frontier.extend(f for f in found if f not in seen)
    return sorted(seen)


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

MODELS_NS = "Axiam\\Sdk\\Management\\Models"
MODELS_DIR = "src/Management/Models"
API_NS = "Axiam\\Sdk\\Management"
API_DIR = "src/Management"
TEST_DIR = "tests/Management"

SENSITIVE = "\\Axiam\\Sdk\\Core\\Sensitive"


def _classify() -> tuple[set[str], set[str]]:
    """Split the spec's schemas into (enums, discriminated unions), by RENDERED name.

    Computed once, up front, because the alternative -- asking "is this an enum?" from
    inside an emitter by re-looking-up a name -- is what shipped the first round of this
    port with `NotificationEventType::fromArray()` on a backed enum and
    `ProviderConfig` declared where a `ProviderConfigVariant` is returned. A name is not
    enough to know a schema's KIND; this table is.
    """
    enums: set[str] = set()
    unions: set[str] = set()
    for name, schema in SCHEMAS.items():
        if not isinstance(schema, dict):
            continue
        if isinstance(schema.get("enum"), list):
            enums.add(pascal(name))
        elif discriminated(schema):
            unions.add(pascal(name))
    return enums, unions


ENUMS, UNIONS = _classify()


def type_name(name: str) -> str:
    """The PHP type a `$ref` to ``name`` denotes.

    A union's decoder returns the INTERFACE its arms implement, not the dispatcher class
    that picks between them, so the two names differ and only one of them is a valid
    type declaration.
    """
    rendered = pascal(name)
    return f"{rendered}Variant" if rendered in UNIONS else rendered


def php_type(schema: Any, secret: bool = False) -> tuple[str, str]:
    """Map an ``openapi.json`` schema to ``(declared type, docblock type)``.

    Two types rather than one because PHP's type declarations cannot express what
    PHPStan level 6 requires: ``array`` is a legal declaration but an unusable one, so
    every array carries a ``list<T>``/``array<string,mixed>`` docblock beside it. Where
    the two agree the caller simply emits the declaration.
    """
    if secret:
        return (SENSITIVE, SENSITIVE)

    if not isinstance(schema, dict):
        return ("mixed", "mixed")

    if "$ref" in schema:
        name = type_name(schema["$ref"].split("/")[-1])
        return (name, name)

    inner = nullable_ref(schema)
    if inner:
        name = type_name(inner)
        return (f"?{name}", f"{name}|null")

    if isinstance(schema.get("allOf"), list) and len(schema["allOf"]) == 1:
        return php_type(schema["allOf"][0])

    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)

    if kind == "array":
        item_decl, item_doc = php_type(schema.get("items") or {})
        return ("array", f"list<{item_doc.lstrip('?')}>")
    if kind == "integer":
        return ("int", "int")
    if kind == "number":
        return ("float", "float")
    if kind == "boolean":
        return ("bool", "bool")
    if kind == "string":
        return ("string", "string")
    if kind == "object" or "properties" in schema or "additionalProperties" in schema:
        return ("array", "array<string,mixed>")

    return ("mixed", "mixed")


def nullable(decl: str) -> str:
    """``decl`` made nullable, respecting the two types that refuse the ``?`` prefix.

    ``?mixed`` is a fatal error -- ``mixed`` already includes null -- and re-prefixing an
    already-nullable ``?T`` is one too.
    """
    if decl == "mixed" or decl.startswith("?"):
        return decl
    return f"?{decl}"


def enum_case(value: str) -> str:
    """A PHP enum case name for a wire value (``pending_review`` -> ``PendingReview``)."""
    name = pascal(value)
    if not name or not name[0].isalpha():
        name = f"Value{name}"
    return name


def header(namespace: str, uses: list[str] | None = None) -> str:
    """The file preamble: banner, namespace, and sorted ``use`` statements."""
    out = BANNER + f"\nnamespace {namespace};\n"
    unique = sorted(set(uses or []))
    if unique:
        out += "\n" + "".join(f"use {u};\n" for u in unique)
    return out


def replacement_schemas() -> set[str]:
    """Request schemas the registry marks as full replacements, not sparse updates.

    §27.4 rule 5 makes the difference load-bearing: a replacement body requires every
    field, so omitting one is a constructor error you cannot ship, while a sparse body
    omits what you did not name.
    """
    out: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"] and op.get("update_style") == "replace":
                out.add(op["request_schema"].lstrip("[]"))
    return out


def field_list(schema_name: str, secrets: set[str]) -> tuple[list[dict[str, Any]], str | None]:
    """Every field of ``schema_name``, required first (PHP ordering), plus its description."""
    props, required, description = flatten(schema_name)
    fields: list[dict[str, Any]] = []
    for wire, schema in props.items():
        decl, doc = php_type(schema, secret=wire in secrets)
        is_required = wire in required
        fields.append({
            "wire": wire,
            "name": prop(wire),
            "decl": decl,
            "doc": doc,
            "required": is_required,
            "schema": schema,
            "secret": wire in secrets,
            "description": schema.get("description") if isinstance(schema, dict) else None,
        })
    # PHP forbids a required parameter after an optional one, so required fields must
    # be emitted first. Within each group the spec's own order is preserved so the
    # generated class still reads like the schema it came from.
    return ([f for f in fields if f["required"]] + [f for f in fields if not f["required"]],
            description)


def field_doc(field: dict[str, Any]) -> str:
    """The one-line description for a field, falling back to naming the wire key."""
    if field["description"]:
        return escape(field["description"])
    if field["secret"]:
        return f"the server's `{field['wire']}` field — a one-time secret (§27.5)"
    return f"the server's `{field['wire']}` field"


def decode_one(type_decl: str, source: str) -> str:
    """PHP that turns one raw wire value of declared type ``type_decl`` into that type."""
    if type_decl in {"int", "float", "string", "bool"}:
        return f"({type_decl}) {source}"
    if type_decl == "mixed":
        return source
    if type_decl in ENUMS:
        return f"{type_decl}::fromWire((string) {source})"
    if type_decl.endswith("Variant") and type_decl[:-len("Variant")] in UNIONS:
        # The dispatcher picks the arm; the interface is what the arm satisfies.
        return f"{type_decl[:-len('Variant')]}::fromArray((array) {source})"
    return f"{type_decl}::fromArray((array) {source})"


def decode_expr(field: dict[str, Any], source: str) -> str:
    """PHP source that turns one raw wire value into the field's declared type."""
    decl = field["decl"].lstrip("?")
    doc = field["doc"]

    if field["secret"]:
        return f"new \\Axiam\\Sdk\\Core\\Sensitive((string) {source})"
    if decl == "array" and doc.startswith("list<"):
        item = doc[5:-1]
        if item == "mixed" or item.startswith("array<"):
            return f"array_values((array) {source})"
        return (f"array_values(array_map(static fn (mixed $v): {item} => "
                f"{decode_one(item, '$v')}, (array) {source}))")
    if decl == "array":
        return f"(array) {source}"
    return decode_one(decl, source)


def encode_one(type_decl: str, ref: str) -> str:
    """PHP that turns one value of declared type ``type_decl`` back into its wire form.

    Always ``->``, never ``?->``: an optional field is only ever encoded INSIDE its own
    ``!== null`` guard, so the nullsafe operator would be dead syntax -- and PHPStan says
    so at level 6 rather than letting it sit there implying a null that cannot occur.
    """
    if type_decl in {"int", "float", "string", "bool", "mixed"}:
        return ref
    if type_decl in ENUMS:
        return f"{ref}->value"
    return f"{ref}->toArray()"


def encode_expr(field: dict[str, Any]) -> str:
    """PHP source that turns one field back into its wire value."""
    decl = field["decl"].lstrip("?")
    doc = field["doc"]
    ref = f"$this->{field['name']}"

    if field["secret"]:
        # Left wrapped on purpose: ManagementTransport::encodeBody() is the ONLY place a
        # Sensitive is revealed, so a body rendered anywhere else stays redacted.
        return ref
    if decl == "array" and doc.startswith("list<"):
        item = doc[5:-1]
        if item in {"int", "float", "string", "bool", "mixed"} or item.startswith("array<"):
            return ref
        inner = encode_one(item, "$v")
        cast = "string" if item in ENUMS else "array"
        return f"array_map(static fn ({item} $v): {cast} => {inner}, {ref})"
    if decl == "array":
        return ref
    return encode_one(decl, ref)



def emit_enum(name: str, schema: Any) -> str:
    """A backed enum whose case values are the wire spellings.

    ``fromWire()`` rather than the built-in ``from()`` because an unknown value must
    fail as an SDK error a caller can catch, not a bare ``\\ValueError``. It throws
    rather than falling back to a default case: on this surface these values gate
    access, and silently reading an unrecognised ``"suspended"`` as whichever case
    happens to be declared first turns a new server state into a wrong one.
    """
    values = [str(v) for v in schema.get("enum") or []]
    description = schema.get("description") or f"The `{name}` enumeration from the server's OpenAPI document."

    out = [header(MODELS_NS)]
    out.extend(docblock(escape(description)))
    out.append(f"enum {name}: string")
    out.append("{")
    for value in values:
        out.extend(inline_doc(f"The wire value `{escape(value)}`.", "    "))
        out.append(f"    case {enum_case(value)} = '{value}';")
        out.append("")
    out.extend(docblock(
        f"Parses a wire value into a {name}.\n\n"
        "Throws on an unrecognised value rather than defaulting to a case: a server "
        "that has learned a new state should surface as a loud error, not as whichever "
        "case was declared first.",
        "    ",
        ["@throws \\Axiam\\Sdk\\Core\\AxiamException when `$value` is not a known case."],
    ))
    out.append("    public static function fromWire(string $value): self")
    out.append("    {")
    out.append("        return self::tryFrom($value) ?? throw new \\Axiam\\Sdk\\Core\\AxiamException(")
    out.append(f"            sprintf('unknown {name} value \"%s\" — the server may be newer than this SDK', $value),")
    out.append("        );")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_class(name: str, secrets: set[str], replacement: bool) -> str:
    """A model class: promoted readonly properties, plus ``fromArray``/``toArray``.

    §27.4 rule 5 lives in the shape of the constructor. A SPARSE body's optional
    properties default to ``null`` and ``toArray()`` omits them, so an unset field is
    ABSENT from the wire request rather than sent as null. A REPLACEMENT body declares
    every field required, so omitting one is a ``TypeError`` at construction — the
    earliest a language can report it.
    """
    fields, description = field_list(name, secrets)
    sparse = not replacement and all(not f["required"] for f in fields) and bool(fields)

    summary = escape(description) if description else \
        f"The `{name}` schema from the server's OpenAPI document."
    if sparse:
        summary += (
            "\n\nEvery property is optional, so this is a SPARSE body: what you leave unset "
            "is left unchanged, and is omitted from the wire request entirely rather than "
            "sent as null (§27.4 rule 5)."
        )
    elif replacement:
        summary += (
            "\n\nThis is a REPLACEMENT body (§27.4 rule 5): every field is required, so "
            "omitting one is a constructor error rather than a silent erasure server-side."
        )

    uses = []
    out = [header(MODELS_NS, uses)]
    out.extend(docblock(summary))
    out.append(f"final class {name} implements \\JsonSerializable")
    out.append("{")

    # --- constructor ---
    tags = []
    for f in fields:
        optional = "" if f["required"] else " (optional)"
        suffix = "" if f["required"] or f["doc"] == "mixed" or f["doc"].endswith("|null") else "|null"
        tags.append(f"@param {f['doc']}{suffix} ${f['name']} {field_doc(f)}{optional}")
    out.extend(docblock(f"Constructs a {name}.", "    ", tags) if fields
               else docblock(f"Constructs a {name}. The schema declares no fields.", "    "))
    if not fields:
        out.append("    public function __construct()")
        out.append("    {")
        out.append("    }")
    else:
        out.append("    public function __construct(")
        for f in fields:
            decl = f["decl"] if f["required"] else nullable(f["decl"])
            default = "" if f["required"] else " = null"
            out.append(f"        public readonly {decl} ${f['name']}{default},")
        out.append("    ) {")
        out.append("    }")
    out.append("")

    # --- fromArray ---
    out.extend(docblock(
        f"Rebuilds a {name} from one decoded JSON object.",
        "    ",
        ["@param array<string,mixed> $data The raw wire object."],
    ))
    out.append("    public static function fromArray(array $data): self")
    out.append("    {")
    if not fields:
        out.append("        return new self();")
    else:
        out.append("        return new self(")
        for f in fields:
            src = f"$data['{f['wire']}']"
            if f["required"]:
                need = f"ModelDecode::need($data, '{f['wire']}', self::class)"
                out.append(f"            {decode_expr(f, need)},")
            else:
                out.append(f"            isset({src}) ? {decode_expr(f, src)} : null,")
        out.append("        );")
    out.append("    }")
    out.append("")

    # --- toArray ---
    out.extend(docblock(
        "Renders this object back to its wire form.\n\n"
        "§27.4 rule 5: a null property is OMITTED, not emitted as null. On a sparse "
        "update those two say opposite things — \"leave this alone\" versus \"set this to "
        "nothing\" — and only omission means the first.",
        "    ",
        ["@return array<string,mixed>"],
    ))
    out.append("    public function toArray(): array")
    out.append("    {")
    if not fields:
        out.append("        return [];")
    else:
        out.append("        $out = [];")
        for f in fields:
            expr = encode_expr(f)
            if f["required"]:
                out.append(f"        $out['{f['wire']}'] = {expr};")
            else:
                out.append(f"        if ($this->{f['name']} !== null) {{")
                out.append(f"            $out['{f['wire']}'] = {expr};")
                out.append("        }")
        out.append("")
        out.append("        return $out;")
    out.append("    }")
    out.append("")

    # --- jsonSerialize ---
    out.extend(docblock(
        "Renders this object for `json_encode()`.\n\n"
        "Any {@see " + SENSITIVE + "} it carries stays WRAPPED here, so a log line or a "
        "`json_encode($model)` in application code prints `[SENSITIVE]`. The one place a "
        "secret is revealed is {@see \\Axiam\\Sdk\\Management\\ManagementTransport}, on the "
        "way to the wire and nowhere else (§27.5).",
        "    ",
        ["@return array<string,mixed>"],
    ))
    out.append("    public function jsonSerialize(): array")
    out.append("    {")
    out.append("        return $this->toArray();")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_union(name: str, schema: Any, tag: str, arms: list[tuple[str, Any]]) -> dict[str, str]:
    """An internally-tagged union: one interface plus one class per arm.

    PHP has no sealed hierarchy, so the base is an interface and `fromArray` on a small
    dispatcher class picks the arm by its tag value. An unknown tag throws for the same
    reason an unknown enum value does.
    """
    files: dict[str, str] = {}
    description = schema.get("description") or f"The `{name}` union from the server's OpenAPI document."

    iface = [header(MODELS_NS)]
    iface.extend(docblock(
        escape(description) + f"\n\nDiscriminated on the wire by `{tag}`. Use "
        f"{{@see {name}::fromArray()}} to decode one; each arm is a separate class "
        "implementing this interface.",
    ))
    iface.append(f"interface {name}Variant extends \\JsonSerializable")
    iface.append("{")
    iface.extend(docblock(
        "Renders this variant to its wire form, including its discriminator.",
        "    ",
        ["@return array<string,mixed>"],
    ))
    iface.append("    public function toArray(): array;")
    iface.append("}")
    files[f"{MODELS_DIR}/{name}Variant.php"] = "\n".join(iface) + "\n"

    dispatch = [header(MODELS_NS)]
    dispatch.extend(docblock(
        escape(description) + f"\n\nThe decoder for the `{tag}`-tagged union. Every arm is a "
        f"{name}Variant; this class exists only to pick the right one.",
    ))
    dispatch.append(f"final class {name}")
    dispatch.append("{")
    dispatch.extend(docblock(
        f"Decodes one `{tag}`-tagged {name} object into its variant.",
        "    ",
        [
            "@param array<string,mixed> $data The raw wire object.",
            f"@throws \\Axiam\\Sdk\\Core\\AxiamException when `{tag}` is missing or unknown.",
        ],
    ))
    dispatch.append(f"    public static function fromArray(array $data): {name}Variant")
    dispatch.append("    {")
    dispatch.append(f"        $tag = $data['{tag}'] ?? null;")
    dispatch.append("")
    dispatch.append("        return match ($tag) {")
    for value, payload in arms:
        arm = f"{name}{pascal(value)}"
        dispatch.append(f"            '{value}' => {arm}::fromArray($data),")
    dispatch.append("            default => throw new \\Axiam\\Sdk\\Core\\AxiamException(")
    dispatch.append(f"                sprintf('unknown {name} {tag} \"%s\"', is_string($tag) ? $tag : gettype($tag)),")
    dispatch.append("            ),")
    dispatch.append("        };")
    dispatch.append("    }")
    dispatch.append("}")
    files[f"{MODELS_DIR}/{name}.php"] = "\n".join(dispatch) + "\n"

    for value, payload in arms:
        arm = f"{name}{pascal(value)}"
        resolved = resolve_ref(payload) if "$ref" in payload else payload
        props = resolved.get("properties") or {}
        required = set(resolved.get("required") or [])
        fields = []
        for wire, pschema in props.items():
            decl, doc = php_type(pschema)
            fields.append({
                "wire": wire, "name": prop(wire), "decl": decl, "doc": doc,
                "required": wire in required, "schema": pschema, "secret": False,
                "description": pschema.get("description") if isinstance(pschema, dict) else None,
            })
        fields = [f for f in fields if f["required"]] + [f for f in fields if not f["required"]]

        body = [header(MODELS_NS)]
        body.extend(docblock(
            f"The `{escape(value)}` arm of {{@see {name}}} (`{tag}: \"{escape(value)}\"`).",
        ))
        body.append(f"final class {arm} implements {name}Variant")
        body.append("{")
        tags = [
            "@param {}{} ${} {}".format(
                f["doc"],
                "" if f["required"] or f["doc"] == "mixed" or f["doc"].endswith("|null") else "|null",
                f["name"],
                field_doc(f),
            )
            for f in fields
        ]
        body.extend(docblock(f"Constructs the `{escape(value)}` arm.", "    ", tags) if fields
                    else docblock(f"Constructs the `{escape(value)}` arm, which carries no fields.", "    "))
        if not fields:
            body.append("    public function __construct()")
            body.append("    {")
            body.append("    }")
        else:
            body.append("    public function __construct(")
            for f in fields:
                decl = f["decl"] if f["required"] else nullable(f["decl"])
                default = "" if f["required"] else " = null"
                body.append(f"        public readonly {decl} ${f['name']}{default},")
            body.append("    ) {")
            body.append("    }")
        body.append("")
        body.extend(docblock(
            f"Rebuilds the `{escape(value)}` arm from one decoded JSON object.",
            "    ",
            ["@param array<string,mixed> $data The raw wire object."],
        ))
        body.append("    public static function fromArray(array $data): self")
        body.append("    {")
        if not fields:
            body.append("        return new self();")
        else:
            body.append("        return new self(")
            for f in fields:
                src = f"$data['{f['wire']}']"
                need = f"ModelDecode::need($data, '{f['wire']}', self::class)"
                body.append(f"            {decode_expr(f, need)}," if f["required"]
                            else f"            isset({src}) ? {decode_expr(f, src)} : null,")
            body.append("        );")
        body.append("    }")
        body.append("")
        body.extend(docblock(
            f"Renders this arm to its wire form, re-attaching `{tag}: \"{escape(value)}\"`.",
            "    ",
            ["@return array<string,mixed>"],
        ))
        body.append("    public function toArray(): array")
        body.append("    {")
        body.append(f"        $out = ['{tag}' => '{value}'];")
        for f in fields:
            expr = encode_expr(f)
            if f["required"]:
                body.append(f"        $out['{f['wire']}'] = {expr};")
            else:
                body.append(f"        if ($this->{f['name']} !== null) {{")
                body.append(f"            $out['{f['wire']}'] = {expr};")
                body.append("        }")
        body.append("")
        body.append("        return $out;")
        body.append("    }")
        body.append("")
        body.extend(docblock(
            "Renders this arm for `json_encode()`.",
            "    ",
            ["@return array<string,mixed>"],
        ))
        body.append("    public function jsonSerialize(): array")
        body.append("    {")
        body.append("        return $this->toArray();")
        body.append("    }")
        body.append("}")
        files[f"{MODELS_DIR}/{arm}.php"] = "\n".join(body) + "\n"

    return files


def emit_models() -> dict[str, str]:
    """Every model file, keyed by repo-relative path."""
    secrets = sensitive_map()
    replacements = replacement_schemas()
    files: dict[str, str] = {}
    for name in schema_closure():
        schema = SCHEMAS.get(name) or {}
        rendered = pascal(name)
        if isinstance(schema.get("enum"), list):
            files[f"{MODELS_DIR}/{rendered}.php"] = emit_enum(rendered, schema)
            continue
        union = discriminated(schema)
        if union:
            files.update(emit_union(rendered, schema, union[0], union[1]))
            continue
        files[f"{MODELS_DIR}/{rendered}.php"] = emit_class(
            rendered, secrets.get(name, set()), name in replacements)
    return files


# ---------------------------------------------------------------------------
# Namespace handles
# ---------------------------------------------------------------------------


def path_param_names(op: dict[str, Any]) -> list[str]:
    """The `{placeholder}` names in an operation's path, in order."""
    return re.findall(r"\{([^}]+)\}", op["path"])


def implicit_params(namespace: str, op: dict[str, Any]) -> set[str]:
    """Which path params the handle fills in itself (§27.4 rule 3).

    `{org_id}` is always the client's. `{tenant_id}` is the client's only where it names
    the CONTEXT of the call; in `tenants` and the signing-CA routes it names the object
    being administered, and taking it implicitly there would make it impossible to
    address any tenant but your own.
    """
    names = set(path_param_names(op))
    implicit = {"org_id"} & names
    if "tenant_id" in names and namespace in IMPLICIT_TENANT_NAMESPACES:
        implicit.add("tenant_id")
    return implicit


def split_query(op: dict[str, Any]) -> tuple[list[str], list[str]]:
    """Query parameters split into (required, optional), paging excluded."""
    required, optional = [], []
    for q in op["query_params"]:
        if op["paginated"] and q["name"] in {"offset", "limit"}:
            continue
        (required if q["required"] else optional).append(q["name"])
    return required, optional


def query_type(op: dict[str, Any], name: str) -> str:
    """The PHP type for one query parameter."""
    for q in op["query_params"]:
        if q["name"] != name:
            continue
        # The registry copies the spec's `type`, which for an optional parameter is a
        # LIST (`["string", "null"]`) rather than a bare string.
        kind = q["type"]
        if isinstance(kind, list):
            kind = next((k for k in kind if k != "null"), "string")
        return {"integer": "int", "number": "float", "boolean": "bool"}.get(kind, "string")
    return "string"


def operation_params(namespace: str, op: dict[str, Any]) -> list[dict[str, str]]:
    """The generated method's parameter list, required before optional."""
    implicit = implicit_params(namespace, op)
    params: list[dict[str, str]] = []

    for name in path_param_names(op):
        if name in implicit:
            continue
        params.append({
            "name": camel(name), "decl": "string", "doc": "string",
            "kind": "path", "wire": name, "required": "1",
            "text": f"the `{{{name}}}` path parameter",
        })

    required_q, optional_q = split_query(op)
    for name in required_q:
        t = query_type(op, name)
        params.append({
            "name": camel(name), "decl": t, "doc": t, "kind": "query", "wire": name,
            "required": "1", "text": f"the required `{name}` query parameter",
        })

    if op["request_body"] != "none" and op["request_schema"]:
        model = pascal(op["request_schema"].lstrip("[]"))
        params.append({
            "name": "body", "decl": model, "doc": model, "kind": "body", "wire": "",
            "required": "1", "text": "the request body",
        })

    if op["paginated"]:
        params.append({
            "name": "page", "decl": "?PageRequest", "doc": "PageRequest|null",
            "kind": "page", "wire": "", "required": "",
            "text": "which page to fetch; defaults to the first",
        })

    for name in optional_q:
        t = query_type(op, name)
        params.append({
            "name": camel(name), "decl": f"?{t}", "doc": f"{t}|null", "kind": "query",
            "wire": name, "required": "", "text": f"the optional `{name}` query parameter",
        })

    return params


def response_php(op: dict[str, Any]) -> tuple[str, str]:
    """The method's ``(declared return type, docblock return type)``."""
    kind = op["response"]["kind"]
    schema = op["response"]["schema"]
    if kind == "none" or not schema:
        return ("void", "void")
    model = type_name(schema.lstrip("[]"))
    if kind == "page":
        return ("Page", f"Page<{model}>")
    if kind == "array":
        return ("array", f"list<{model}>")
    return (model, model)


def spec_description(op: dict[str, Any]) -> str | None:
    """The `summary`/`description` ``openapi.json`` gives this path+method, if any."""
    entry = (SPEC.get("paths") or {}).get(op["path"]) or {}
    node = entry.get(op["method"].lower()) or {}
    text = node.get("summary") or node.get("description")
    return escape(text) if text else None


def operation_doc(op: dict[str, Any], name: str) -> str:
    """The docblock summary for one generated operation."""
    described = spec_description(op)
    lead = described or f"`{op['method']} {op['path']}`."
    if described:
        lead = f"{described}\n\n`{op['method']} {op['path']}`."

    kind = op["response"]["kind"]
    if kind == "page":
        lead += (
            "\n\nReturns ONE page. `Page::$total` is the server's count across all pages "
            "and is not `count($page)` — see §27.4 rule 4."
        )
    elif kind == "array":
        lead += (
            "\n\nReturns the server's complete list. This endpoint is NOT paginated, so "
            "the result is a plain list and never a `Page` (§27.4 rule 4)."
        )
    elif kind == "none":
        lead += "\n\nReturns nothing; the server answers with an empty body."

    if op["method"] == "DELETE":
        lead += (
            "\n\nNOT idempotent (§27.4 rule 6): deleting something already deleted raises "
            "{@see \\Axiam\\Sdk\\Management\\NotFoundError} rather than succeeding quietly."
        )
    if op["sensitive_response_fields"]:
        fields = ", ".join(f"`{f}`" for f in op["sensitive_response_fields"])
        lead += (
            f"\n\nThe response carries a ONE-TIME secret ({fields}): the server will not "
            "return it again, so a caller that does not persist it here cannot recover it "
            "(§27.5)."
        )
    return lead


def emit_operation(namespace: str, opname: str, op: dict[str, Any]) -> list[str]:
    """One generated method on a namespace handle."""
    params = operation_params(namespace, op)
    decl_ret, doc_ret = response_php(op)
    name = method(opname)
    canonical = f"{namespace}.{opname}"

    tags = [f"@param {p['doc']} ${p['name']} {p['text']}" for p in params]
    if doc_ret != "void":
        tags.append(f"@return {doc_ret}")
    out = docblock(operation_doc(op, name), "    ", tags)

    if params:
        out.append(f"    public function {name}(")
        for p in params:
            default = "" if p["required"] else " = null"
            out.append(f"        {p['decl']} ${p['name']}{default},")
        out.append(f"    ): {decl_ret} {{")
    else:
        out.append(f"    public function {name}(): {decl_ret}")
        out.append("    {")

    implicit = implicit_params(namespace, op)
    path_values = []
    for pname in path_param_names(op):
        if pname == "org_id" and pname in implicit:
            path_values.append(f"'{pname}' => $this->orgId()")
        elif pname == "tenant_id" and pname in implicit:
            path_values.append(f"'{pname}' => $this->tenantId()")
        else:
            path_values.append(f"'{pname}' => ${camel(pname)}")
    pv = "[" + ", ".join(path_values) + "]" if path_values else "[]"

    query_entries = [f"'{p['wire']}' => ${p['name']}" for p in params if p["kind"] == "query"]
    qv = "[" + ", ".join(query_entries) + "]" if query_entries else "[]"

    body_param = next((p for p in params if p["kind"] == "body"), None)

    if op["response"]["kind"] == "page":
        model = pascal(op["response"]["schema"].lstrip("[]"))
        out.append(f"        return $this->transport->sendPage(")
        out.append(f"            '{canonical}',")
        out.append(f"            '{op['path']}',")
        out.append(f"            {pv},")
        out.append(f"            {qv},")
        out.append("            $page ?? new PageRequest(),")
        out.append(f"            static fn (array $item): {model} => {model}::fromArray($item),")
        out.append("        );")
        out.append("    }")
        return out

    call = [
        f"        $decoded = $this->transport->send(",
        f"            '{canonical}',",
        f"            '{op['method']}',",
        f"            '{op['path']}',",
        f"            {pv},",
        f"            {qv},",
    ]
    call.append(f"            ${body_param['name']}->toArray()," if body_param else "            null,")
    call.append("        );")

    if op["response"]["kind"] == "none":
        # The 36 no-content operations still go through send(); the decoded value is
        # simply discarded. Routing them past the transport instead would put them on a
        # different request path, which is exactly what §27.8 forbids.
        out.extend(line.replace("$decoded = ", "", 1) if "$decoded = " in line else line
                   for line in call)
        out.append("    }")
        return out

    out.extend(call)
    out.append("")
    model = pascal(op["response"]["schema"].lstrip("[]"))
    if op["response"]["kind"] == "array":
        out.append("        $items = [];")
        out.append("        foreach ($decoded ?? [] as $item) {")
        out.append("            if (is_array($item)) {")
        out.append(f"                $items[] = {model}::fromArray($item);")
        out.append("            }")
        out.append("        }")
        out.append("")
        out.append("        return $items;")
    else:
        out.append(f"        return {model}::fromArray($decoded ?? []);")
    out.append("    }")
    return out


def emit_namespace(namespace: str, nsdef: dict[str, Any]) -> str:
    """One namespace handle class (§27.2)."""
    cls = f"{pascal(namespace)}Api"
    # Both names, for a union: the code calls the DISPATCHER (`X::fromArray`) while the
    # signature declares the INTERFACE (`XVariant`). Importing only one leaves the other
    # resolving against this namespace, where it does not exist.
    uses: list[str] = []
    for op in nsdef["operations"].values():
        for schema in (op["response"]["schema"], op["request_schema"]):
            if not schema:
                continue
            bare = pascal(schema.lstrip("[]"))
            uses.append(f"{MODELS_NS}\\{bare}")
            if bare in UNIONS:
                uses.append(f"{MODELS_NS}\\{bare}Variant")

    out = [header(API_NS, uses)]
    out.extend(docblock(
        escape(nsdef["doc"]) +
        f"\n\nThe `{namespace}` namespace handle (CONTRACT.md §27.2), reached as "
        f"`$client->management()->{method(namespace)}()`. Every method here goes through the "
        "one shared {@see ManagementTransport}, so §3 CSRF, the §4 cookie jar, the §5 tenant "
        "header, §6 TLS, §16 retry and §19 telemetry apply without this class doing anything "
        "to opt in (§27.8)."
    ))
    out.append(f"final class {cls} extends ManagementSupport")
    out.append("{")
    bodies = []
    for opname, op in nsdef["operations"].items():
        bodies.append("\n".join(emit_operation(namespace, opname, op)))
    out.append("\n\n".join(bodies))
    out.append("}")
    return "\n".join(out) + "\n"


def emit_api() -> str:
    """The root ``ManagementApi`` with one accessor per namespace."""
    out = [header(API_NS)]
    out.extend(docblock(
        "The CONTRACT.md §27 management surface: 146 operations across 24 namespaces.\n\n"
        "Reached as `$client->management()`. This class holds nothing but the shared "
        "{@see ManagementTransport} and the client's default scope; each accessor below "
        "hands back a namespace handle (§27.2) that can be re-scoped per call with "
        "`->inOrg()` / `->forTenant()` (§27.4 rule 3).\n\n"
        "Handles are constructed on demand rather than cached. §27.4 rule 10 forbids "
        "caching RESPONSES, not handles — but a handle is two references and a scope, and "
        "building one per call keeps `->inOrg()` from having anything shared to mutate."
    ))
    out.append("final class ManagementApi")
    out.append("{")
    out.extend(docblock(
        "Wires the management surface onto the client's existing request path.",
        "    ",
        [
            "@param ManagementTransport $transport The one §27.8 wire path.",
            "@param string|null $orgId The client's organization id, or `null` if unset.",
            "@param string|null $tenantId The client's tenant id, or `null` if unset.",
        ],
    ))
    out.append("    public function __construct(")
    out.append("        private readonly ManagementTransport $transport,")
    out.append("        private readonly ?string $orgId = null,")
    out.append("        private readonly ?string $tenantId = null,")
    out.append("    ) {")
    out.append("    }")

    manifest_block = docblock(
        "The §27.6 declarative layer: plan and apply a manifest.\n\n"
        "`plan()` writes nothing; `apply()` performs the plan, stops at the first failure "
        "and does not roll back (§27.7). Hand-written rather than generated — the manifest "
        "layer is a convergence loop over the operations below, not an endpoint the "
        "registry describes.",
        "    ",
    )
    manifest_block.append("    public function manifest(): \\Axiam\\Sdk\\Management\\Manifest\\ManifestApi")
    manifest_block.append("    {")
    manifest_block.append("        return new \\Axiam\\Sdk\\Management\\Manifest\\ManifestApi($this);")
    manifest_block.append("    }")
    accessors = ["\n".join(manifest_block)]
    for namespace, nsdef in REGISTRY["namespaces"].items():
        cls = f"{pascal(namespace)}Api"
        block = docblock(escape(nsdef["doc"]), "    ")
        block.append(f"    public function {method(namespace)}(): {cls}")
        block.append("    {")
        block.append(f"        return new {cls}(")
        block.append("            $this->transport,")
        block.append("            new NamespaceScope(),")
        block.append("            $this->orgId,")
        block.append("            $this->tenantId,")
        block.append("        );")
        block.append("    }")
        accessors.append("\n".join(block))
    out.append("")
    out.append("\n\n".join(accessors))
    out.append("}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Generated tests
# ---------------------------------------------------------------------------


def example_json(schema: Any, depth: int = 0) -> Any:
    """A plausible wire value for ``schema`` — what a mounted fake server returns."""
    if depth > 6 or not isinstance(schema, dict):
        return None
    if "$ref" in schema:
        return example_for(schema["$ref"].split("/")[-1], depth + 1)
    inner = nullable_ref(schema)
    if inner:
        return example_for(inner, depth + 1)
    if isinstance(schema.get("allOf"), list) and len(schema["allOf"]) == 1:
        return example_json(schema["allOf"][0], depth)
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return schema["enum"][0]
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)
    if kind == "array":
        return [example_json(schema.get("items") or {}, depth + 1)]
    if kind == "integer":
        return 1
    if kind == "number":
        return 1.5
    if kind == "boolean":
        return True
    if kind == "string":
        fmt = schema.get("format")
        if fmt == "uuid":
            return EXAMPLE_UUID
        if fmt == "date-time":
            return EXAMPLE_TIME
        return "example"
    if kind == "object" or "properties" in schema or "additionalProperties" in schema:
        return {k: example_json(v, depth + 1) for k, v in (schema.get("properties") or {}).items()}
    return None


def example_for(name: str, depth: int = 0) -> Any:
    """A plausible wire object for the named schema."""
    if depth > 6:
        return None
    schema = SCHEMAS.get(name) or {}
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return schema["enum"][0]
    union = discriminated(schema)
    if union:
        tag, arms = union
        value, payload = arms[0]
        resolved = resolve_ref(payload) if "$ref" in payload else payload
        out = {tag: value}
        for key, sub in (resolved.get("properties") or {}).items():
            out[key] = example_json(sub, depth + 1)
        return out
    props, _, _ = flatten(name)
    return {k: example_json(v, depth + 1) for k, v in props.items()}


def php_literal(value: Any, indent: str = "") -> str:
    """Render a Python value as a PHP literal (used for mounted response bodies)."""
    pad = indent + "    "
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    if isinstance(value, list):
        if not value:
            return "[]"
        items = ",\n".join(f"{pad}{php_literal(v, pad)}" for v in value)
        return "[\n" + items + f",\n{indent}]"
    if isinstance(value, dict):
        if not value:
            return "[]"
        items = ",\n".join(
            f"{pad}'{k}' => {php_literal(v, pad)}" for k, v in value.items())
        return "[\n" + items + f",\n{indent}]"
    return "null"


def example_response(op: dict[str, Any]) -> Any:
    """The body a fake server returns for one operation, honouring `response.kind`.

    Reads ``response.kind`` and NEVER infers plurality from the schema NAME. The
    registry's ``response.schema`` carries no ``[]`` prefix, so a generator that guessed
    from the name typed all 13 bare-array reads as single objects — the exact bug the
    Kotlin port shipped and had to fix.
    """
    kind = op["response"]["kind"]
    schema = op["response"]["schema"]
    if kind == "none" or not schema:
        return None
    body = example_for(schema.lstrip("[]"))
    if kind == "page":
        return {"items": [body], "total": 1, "offset": 0, "limit": 50}
    if kind == "array":
        return [body]
    return body


def php_value_literal(schema: Any, secret: bool, depth: int = 0) -> str:
    """A PHP expression constructing one field's value, for a request-body fixture."""
    if secret:
        return "new \\Axiam\\Sdk\\Core\\Sensitive('s3cret')"
    if depth > 5 or not isinstance(schema, dict):
        return "null"
    if "$ref" in schema:
        return model_literal(schema["$ref"].split("/")[-1], depth + 1)
    inner = nullable_ref(schema)
    if inner:
        return model_literal(inner, depth + 1)
    if isinstance(schema.get("allOf"), list) and len(schema["allOf"]) == 1:
        return php_value_literal(schema["allOf"][0], False, depth)
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return "'" + str(schema["enum"][0]) + "'"
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)
    if kind == "array":
        return "[" + php_value_literal(schema.get("items") or {}, False, depth + 1) + "]"
    if kind == "integer":
        return "1"
    if kind == "number":
        return "1.5"
    if kind == "boolean":
        return "true"
    if kind == "string":
        fmt = schema.get("format")
        if fmt == "uuid":
            return f"'{EXAMPLE_UUID}'"
        if fmt == "date-time":
            return f"'{EXAMPLE_TIME}'"
        return "'example'"
    if kind == "object" or "properties" in schema or "additionalProperties" in schema:
        return "[]"
    # An untyped/free-form schema (`metadata: {}`) still needs a value a caller could
    # pass. `null` is the one thing it must NOT be: on a sparse body null means "omit",
    # so a fixture built from null cannot demonstrate that naming a field sends it.
    return "[]"


def model_literal(name: str, depth: int = 0) -> str:
    """A PHP expression constructing one model, for a request-body fixture."""
    if depth > 5:
        return "null"
    rendered = pascal(name)
    schema = SCHEMAS.get(name) or {}
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return f"Models\\{rendered}::{enum_case(str(schema['enum'][0]))}"
    union = discriminated(schema)
    if union:
        tag, arms = union
        value, payload = arms[0]
        arm = f"{rendered}{pascal(value)}"
        resolved = resolve_ref(payload) if "$ref" in payload else payload
        props = resolved.get("properties") or {}
        required = set(resolved.get("required") or [])
        args = [php_value_literal(s, False, depth + 1) for k, s in props.items() if k in required]
        return f"new Models\\{arm}(" + ", ".join(args) + ")"

    secrets = sensitive_map().get(name, set())
    fields, _ = field_list(name, secrets)
    args = [php_value_literal(f["schema"], f["secret"], depth + 1)
            for f in fields if f["required"]]
    return f"new Models\\{rendered}(" + ", ".join(args) + ")"


def call_arguments(namespace: str, op: dict[str, Any]) -> list[str]:
    """The arguments a generated test passes to one operation."""
    args = []
    for p in operation_params(namespace, op):
        if p["kind"] == "path":
            args.append(f"'{EXAMPLE_UUID}'")
        elif p["kind"] == "body":
            args.append(model_literal(op["request_schema"].lstrip("[]")))
        elif p["kind"] == "page":
            continue
        elif p["required"]:
            t = p["decl"]
            args.append({"int": "1", "float": "1.5", "bool": "true"}.get(t, "'example'"))
    return args


def expected_path(op: dict[str, Any]) -> str:
    """The concrete path a generated test expects on the wire."""
    return re.sub(r"\{[^}]+\}", EXAMPLE_UUID, op["path"])


def emit_surface_test() -> str:
    """One conformance case per operation: right method, right path, nothing dropped."""
    out = [BANNER + "\nnamespace Axiam\\Sdk\\Tests\\Management;\n"]
    out.append("use Axiam\\Sdk\\Management\\Models;")
    out.append("use Axiam\\Sdk\\Management\\Page;")
    out.append("")
    out.extend(docblock(
        "One case per CONTRACT.md §27 operation — all 146 of them.\n\n"
        "Each asserts three things about one operation: it issues the METHOD the registry "
        "names, against the PATH the registry names, and — where the operation returns a "
        "body — that every field `openapi.json` declares survives the decode. The third is "
        "the one that earns its keep: the first two pass even when a generator silently "
        "drops a field.\n\n"
        "Generated by `scripts/gen_management.py`; CI re-runs it with `--check`."
    ))
    out.append("final class ManagementSurfaceGeneratedTest extends ManagementTestCase")
    out.append("{")

    cases = []
    count = 0
    for namespace, nsdef in REGISTRY["namespaces"].items():
        for opname, op in nsdef["operations"].items():
            count += 1
            body = example_response(op)
            args = call_arguments(namespace, op)
            call = f"$client->management()->{method(namespace)}()->{method(opname)}(" + ", ".join(args) + ")"
            test_name = "test" + pascal(namespace) + pascal(opname) + "ReachesItsRoute"

            block = inline_doc(
                f"`{op['method']} {op['path']}` — the `{namespace}.{opname}` operation.", "    ")
            block.append(f"    public function {test_name}(): void")
            block.append("    {")
            if body is None:
                block.append("        $client = $this->signedInClient(204, null);")
                block.append(f"        {call};")
            else:
                block.append("        $mounted = " + php_literal(body, "        ") + ";")
                block.append("        $client = $this->signedInClient(200, $mounted);")
                block.append(f"        $result = {call};")
            block.append("")
            block.append("        $request = $this->lastRequest();")
            block.append(f"        self::assertSame('{op['method']}', $request->getMethod());")
            block.append(f"        self::assertSame('{expected_path(op)}', $request->getUri()->getPath());")

            kind = op["response"]["kind"]
            if kind == "page":
                block.append("        self::assertInstanceOf(Page::class, $result);")
                block.append("        self::assertSame(1, $result->total);")
                block.append("        self::assertCount(1, $result->items);")
                block.append("        $this->assertDecodedEveryField($mounted['items'][0], $result->items[0]);")
            elif kind == "array":
                block.append("        self::assertIsArray($result);")
                block.append("        self::assertCount(1, $result);")
                block.append("        $this->assertDecodedEveryField($mounted[0], $result[0]);")
            elif kind == "object":
                block.append("        $this->assertDecodedEveryField($mounted, $result);")
            block.append("    }")
            cases.append("\n".join(block))

    # §27.9: the count itself is an assertion, so an operation silently dropped from the
    # registry fails the build rather than quietly reducing coverage.
    tail = docblock(
        "§27.9: all 146 registry operations are covered by a case above.\n\n"
        "Counted reflectively rather than written as a literal on both sides — "
        "`assertSame(146, 146)` is a tautology, and a case removed by a bad regeneration "
        "would still pass it.",
        "    ",
    )
    tail.append("    public function testEveryRegistryOperationHasACase(): void")
    tail.append("    {")
    tail.append("        $reflection = new \\ReflectionClass(self::class);")
    tail.append("        $cases = array_filter(")
    tail.append("            $reflection->getMethods(\\ReflectionMethod::IS_PUBLIC),")
    tail.append("            static fn (\\ReflectionMethod $m): bool => str_ends_with($m->getName(), 'ReachesItsRoute'),")
    tail.append("        );")
    tail.append("")
    tail.append(f"        self::assertCount({count}, $cases);")
    tail.append("    }")
    cases.append("\n".join(tail))

    out.append("\n\n".join(cases))
    out.append("}")
    return "\n".join(out) + "\n"


def sparse_models() -> list[tuple[str, list[dict[str, Any]]]]:
    """Every request schema whose fields are all optional — the sparse bodies."""
    secrets = sensitive_map()
    replacements = replacement_schemas()
    seen: set[str] = set()
    out: list[tuple[str, list[dict[str, Any]]]] = []
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            name = op["request_schema"]
            if not name:
                continue
            name = name.lstrip("[]")
            if name in seen or name in replacements:
                continue
            seen.add(name)
            fields, _ = field_list(name, secrets.get(name, set()))
            if fields and all(not f["required"] for f in fields):
                out.append((pascal(name), fields))
    return out


def emit_sparse_test() -> str:
    """One case per sparse body: naming ONE field sends exactly that field."""
    out = [BANNER + "\nnamespace Axiam\\Sdk\\Tests\\Management;\n"]
    out.append("use Axiam\\Sdk\\Management\\Models;")
    out.append("")
    out.extend(docblock(
        "One case per SPARSE §27 request body (CONTRACT.md §27.4 rule 5).\n\n"
        "Each names exactly ONE field and asserts the rendered body contains that key and "
        "no other. That is the whole of rule 5: an unset field is ABSENT, not null. The "
        "distinction is not cosmetic — on a sparse update `null` means \"erase this\" and "
        "absence means \"leave it alone\", so a serializer that emits nulls for unset "
        "fields silently wipes every field the caller did not mention.\n\n"
        "Generated by `scripts/gen_management.py`; CI re-runs it with `--check`."
    ))
    out.append("final class ManagementSparseBodiesGeneratedTest extends ManagementTestCase")
    out.append("{")

    cases = []
    for name, fields in sparse_models():
        # Not simply fields[0]: the demonstration only works with a NON-null value,
        # because on a sparse body null is precisely what "omit this" looks like.
        chosen = next(
            (f for f in fields
             if php_value_literal(f["schema"], f["secret"]) != "null"),
            fields[0],
        )
        literal = php_value_literal(chosen["schema"], chosen["secret"])
        block = inline_doc(
            f"`{name}`: naming only `{chosen['wire']}` sends only `{chosen['wire']}`.", "    ")
        block.append(f"    public function test{name}OmitsWhatYouDidNotName(): void")
        block.append("    {")
        block.append(f"        $body = new Models\\{name}({chosen['name']}: {literal});")
        block.append("")
        block.append("        $rendered = $body->toArray();")
        block.append("")
        block.append(f"        self::assertSame(['{chosen['wire']}'], array_keys($rendered));")
        block.append("    }")
        cases.append("\n".join(block))

    tail = docblock(
        "Every sparse body renders empty when nothing is named.\n\n"
        "The degenerate case of rule 5, and the one a serializer with the wrong default "
        "gets wrong most visibly: a no-op update must send `{}`, not a body that nulls out "
        "every field on the object.",
        "    ",
    )
    tail.append("    public function testAnEmptySparseBodyRendersEmpty(): void")
    tail.append("    {")
    for name, _ in sparse_models():
        tail.append(f"        self::assertSame([], (new Models\\{name}())->toArray());")
    tail.append("    }")
    cases.append("\n".join(tail))

    out.append("\n\n".join(cases))
    out.append("}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build() -> dict[Path, str]:
    """Every file this generator owns, keyed by absolute path."""
    files: dict[str, str] = {}
    files.update(emit_models())
    for namespace, nsdef in REGISTRY["namespaces"].items():
        files[f"{API_DIR}/{pascal(namespace)}Api.php"] = emit_namespace(namespace, nsdef)
    files[f"{API_DIR}/ManagementApi.php"] = emit_api()
    files[f"{TEST_DIR}/ManagementSurfaceGeneratedTest.php"] = emit_surface_test()
    files[f"{TEST_DIR}/ManagementSparseBodiesGeneratedTest.php"] = emit_sparse_test()
    return {ROOT / path: text for path, text in files.items()}


def prune(files: dict[Path, str]) -> list[Path]:
    """Committed generated files this run did NOT produce — i.e. now stale.

    Only ever considers the models directory, whose entire contents this generator owns.
    A schema removed from the spec must take its model file with it, or `--check` passes
    on a tree that still ships a type the contract no longer has.
    """
    stale = []
    models = ROOT / MODELS_DIR
    if models.is_dir():
        hand_written = {models / "ModelDecode.php"}
        for path in sorted(models.glob("*.php")):
            if path not in files and path not in hand_written:
                stale.append(path)
    return stale


def main() -> int:
    """Write (or, with ``--check``, verify) the generated §27 surface."""
    check = "--check" in sys.argv
    files = build()
    stale = prune(files)

    if check:
        drifted = [p for p, text in sorted(files.items())
                   if not p.exists() or p.read_text() != text]
        if drifted or stale:
            for path in drifted:
                print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
            for path in stale:
                print(f"stale (no longer generated): {path.relative_to(ROOT)}", file=sys.stderr)
            print(
                "\nThe committed §27 surface disagrees with management-registry.json / "
                "openapi.json.\nRegenerate with `python3 scripts/gen_management.py` and "
                "commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"§27 surface is current ({len(files)} files).")
        return 0

    for path in stale:
        path.unlink()
        print(f"removed stale {path.relative_to(ROOT)}")

    for path, text in sorted(files.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
